using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Čeština.</summary>
    internal static class Cs
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Všechny programy",
            ["Search"] = "Hledat",
            ["SearchHint"] = "Prohledat programy",
            ["SearchFiles"] = "Hledat i v souborech",
            ["BestMatch"] = "Nejlepší shoda",
            ["AppsGroup"] = "Aplikace",
            ["SettingsGroup"] = "Nastavení",
            ["FilesGroup"] = "Soubory",
            ["Searching"] = "Prohledávání souborů…",
            ["NoIndex"] = "Hledání Windows není k dispozici",
            ["NoResults"] = "Žádné výsledky",
            ["Loading"] = "Načítání…",

            ["ProgramFilter"] = "Filtr:",
            ["ProgramGroups"] = "Skupiny",
            ["ProgramCount"] = "Programů: {0}",

            ["AdvancedSearch"] = "Rozšířené hledání",
            ["SearchFor"] = "Hledat:",
            ["Categories"] = "Hledá se",
            ["FileType"] = "Typ",
            ["AnyType"] = "Všechny soubory",
            ["TypeDocuments"] = "Dokumenty",
            ["TypePictures"] = "Obrázky",
            ["TypeMusic"] = "Hudba",
            ["TypeVideos"] = "Videa",
            ["TypeFolders"] = "Složky",
            ["Location"] = "Hledat v",
            ["AnyLocation"] = "Všude",
            ["Modified"] = "Změněno",
            ["AnyTime"] = "Kdykoli",
            ["Today"] = "Dnes",
            ["ThisWeek"] = "Tento týden",
            ["ThisMonth"] = "Tento měsíc",
            ["ThisYear"] = "Tento rok",
            ["Back"] = "Zpět",
            ["Hits"] = "{0} výsledků",

            ["Documents"] = "Dokumenty",
            ["RecentDocuments"] = "Poslední dokumenty",
            ["Pictures"] = "Obrázky",
            ["Music"] = "Hudba",
            ["Computer"] = "Tento počítač",
            ["ControlPanel"] = "Ovládací panely",
            ["SetProgramAccess"] = "Nastavit přístup k programům a výchozí programy",
            ["Connections"] = "Připojení",
            ["RemoteDesktop"] = "Vzdálená plocha",
            ["SshConnection"] = "Připojení SSH…",
            ["SshPrompt"] = "uživatel@počítač:",
            ["SshTitle"] = "Připojení SSH",
            ["SshSubtitle"] = "Připojuje klient OpenSSH, který je součástí Windows.",
            ["SshKey"] = "Soubor s klíčem:",
            ["SshKeyHint"] = "Klíče ze složky .ssh. Bez klíče se ssh zeptá na heslo.",
            ["SshNoKey"] = "(žádný – heslo)",
            ["SshBrowse"] = "Vybrat soubor s klíčem…",
            ["SshConnectButton"] = "Připojit",
            ["SftpConnection"] = "Připojení SFTP…",
            ["TelnetConnection"] = "Připojení Telnet…",
            ["FtpConnection"] = "Připojení FTP…",
            ["NetworkFolder"] = "Otevřít síťovou složku…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Port:",
            ["HostPrompt"] = "Počítač:",
            ["FolderPrompt"] = "\\\\server\\sdílení:",
            ["ConnectSubtitle"] = "Klienta si Windows přináší sám.",
            ["MapDrive"] = "Připojit síťovou jednotku…",
            ["AllConnections"] = "Zobrazit všechna připojení",
            ["PrintersAndFaxes"] = "Tiskárny a faxy",
            ["Help"] = "Nápověda a podpora",
            ["SearchPlace"] = "Hledat",
            ["Run"] = "Spustit...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Programy",
            ["Favorites"] = "Oblíbené položky",
            ["Internet"] = "Internet",
            ["Email"] = "E-mail",
            ["Empty"] = "(Prázdné)",

            ["LogOff"] = "Odhlásit",
            ["LogOffClassic"] = "Odhlásit…",
            ["ShutDownClassic"] = "Vypnout…",
            ["ShutDown"] = "Vypnout počítač",
            ["PowerTitle"] = "Vypnout počítač",
            ["Standby"] = "Úsporný režim",
            ["Hibernate"] = "Režim spánku",
            ["TurnOff"] = "Vypnout",
            ["Restart"] = "Restartovat",
            ["Lock"] = "Zamknout",
            ["SwitchUser"] = "Přepnout uživatele",
            ["LogOffTitle"] = "Odhlásit se ze systému Windows",
            ["Cancel"] = "Storno",
            ["PowerQuestion"] = "Co má počítač udělat?",

            ["Open"] = "Otevřít",
            ["RunAsAdmin"] = "Spustit jako správce",
            ["Pin"] = "Přidat k oblíbeným",
            ["Unpin"] = "Odebrat z oblíbených",
            ["MoveToFolder"] = "Přesunout do složky",
            ["NewFolder"] = "Nová složka…",
            ["FolderDefaultName"] = "Složka",
            ["OutOfFolder"] = "Vyjmout ze složky",
            ["RenameFolder"] = "Přejmenovat složku…",
            ["DissolveFolder"] = "Zrušit složku",
            ["FolderNamePrompt"] = "Název složky:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Odebrat z tohoto seznamu",
            ["OpenFileLocation"] = "Otevřít umístění souboru",

            ["TrayOpen"] = "Otevřít nabídku Start",
            ["TraySettings"] = "Nastavení…",
            ["TrayRefresh"] = "Znovu načíst seznam programů",
            ["TrayExit"] = "Ukončit",

            ["SettingsTitle"] = "Retro Menu – Nastavení",
            ["Appearance"] = "Vzhled",
            ["Theme"] = "Motiv",
            ["FollowRetroBar"] = "Převzít motiv z RetroBaru",
            ["Behaviour"] = "Chování",
            ["WinKey"] = "Klávesa Windows",
            ["WinKeyNeutralize"] = "Zachytávat (doporučeno)",
            ["WinKeySwallow"] = "Zcela pohltit",
            ["WinKeyOff"] = "Nechat být",
            ["FrequentCount"] = "Často používané: počet",
            ["ShowRecent"] = "Zobrazit naposledy spuštěné programy",
            ["ShowTiles"] = "Oblíbené jako dlaždice vpravo",
            ["ShowTilesHint"] = "Třetí panel ukazuje oblíbené položky a jejich složky jako dlaždice, podobně jako mřížka připnutých aplikací ve Windows 11.",
            ["TilesHeader"] = "Připnuto",
            ["ShowRecentHint"] = "V levém sloupci pak stojí to, co bylo spuštěno naposledy, místo toho, co se spouští nejčastěji.",
            ["ShowSearchBox"] = "Zobrazit pole hledání (XP ho nemělo)",
            ["SearchFilesSetting"] = "Hledání zahrnuje soubory",
            ["MenuScale"] = "Velikost nabídky",
            ["KeepTaskbar"] = "Zobrazit hlavní panel, dokud je nabídka otevřená",
            ["ShowStoreApps"] = "Vypsat i aplikace ze Storu",
            ["UseXpExplorer"] = "Otvírat složky v okně souborů ve stylu XP",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 je nainstalován a ukáže Dokumenty, "
                                    + "Tento počítač i ostatní místa ve starém kabátě.",
            ["UseXpExplorerMissing"] = "Nenalezeno. Bez windows-xp-explorer-win-11 otevírá složky "
                                       + "Průzkumník Windows.",
            ["UseXpExplorerBroken"] = "Nalezeno, ale instalace je neúplná, složky proto otevírá Průzkumník Windows.",
            ["AutoStart"] = "Spouštět s Windows",
            ["Language"] = "Jazyk",
            ["Close"] = "Zavřít",
            ["StoreApps"] = "Aplikace ze Storu",

            ["LangAutoWindows"] = "Automaticky (jazyk Windows)",
            ["LangAutoRetroBar"] = "Automaticky (RetroBar)",
            ["LangDetected"] = "Windows je nastaven na {0}.",
            ["LangShowing"] = "Nabídka mluví takto: {0}.",
            ["LangUntranslated"] = "{0} zatím není přeloženo, takže nastupuje angličtina.",
            ["RetroBarFound"] = "RetroBar nalezen – motiv „{0}“ → „{1}“.",
            ["RetroBarMissing"] = "RetroBar nebyl nalezen.",

            ["SetupTitle"] = "Instalace Retro Menu",
            ["SetupSubtitle"] = "Nabídka Start ve stylu starších verzí Windows.",
            ["SetupIntro"] = "Program se uloží do vaší vlastní uživatelské složky. Nejsou potřeba "
                             + "práva správce a v systému se nic nemění.",
            ["SetupTarget"] = "Cílová složka",
            ["SetupDuring"] = "Při instalaci",
            ["SetupStartMenu"] = "Vytvořit zástupce v nabídce Start",
            ["SetupDesktop"] = "Vytvořit zástupce na ploše",
            ["SetupRetroBar"] = "Nainstalovat i RetroBar – hlavní panel ve stylu XP",
            ["SetupRetroBarNote"] = "Stahuje se přímo z github.com/dremin/RetroBar. Kontrolní součet "
                                    + "staženého souboru se potom objeví v protokolu.",
            ["SetupRetroBarPresent"] = "RetroBar už je nainstalován",
            ["SetupInstall"] = "Nainstalovat",
            ["SetupUpdate"] = "Aktualizovat",
            ["SetupUpdateSubtitle"] = "Stávající instalace bude aktualizována.",
            ["SetupRemoveTitle"] = "Odebrat Retro Menu",
            ["SetupRemoveSubtitle"] = "Program bude odebrán z vaší uživatelské složky.",
            ["SetupRemoveButton"] = "Odebrat",
            ["SetupRemoveText"] = "Retro Menu bude ukončeno a odebráno z {0}. Vaše nastavení zůstane "
                                  + "zachováno, aby je pozdější instalace zase našla.",
            ["SetupWorking"] = "Probíhá instalace…",
            ["SetupRemoving"] = "Probíhá odebírání…",
            ["SetupDone"] = "Hotovo.",
            ["SetupRemoved"] = "Odebráno.",
            ["SetupErrors"] = "Dokončeno s chybami.",
            ["SetupFailed"] = "Selhalo: {0}",
            ["SetupStart"] = "Spustit",
        };
    }
}
