using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Dansk.</summary>
    internal static class Da
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Alle programmer",
            ["Search"] = "Søg",
            ["SearchHint"] = "Søg efter programmer",
            ["SearchFiles"] = "Søg også i filer",
            ["BestMatch"] = "Bedste resultat",
            ["AppsGroup"] = "Apps",
            ["SettingsGroup"] = "Indstillinger",
            ["FilesGroup"] = "Filer",
            ["Searching"] = "Søger i filerne…",
            ["NoIndex"] = "Windows Search er ikke tilgængelig",
            ["NoResults"] = "Ingen resultater",
            ["Loading"] = "Indlæser…",

            ["ProgramFilter"] = "Filter:",
            ["ProgramGroups"] = "Grupper",
            ["ProgramCount"] = "{0} programmer",

            ["AdvancedSearch"] = "Avanceret søgning",
            ["SearchFor"] = "Søg efter:",
            ["Categories"] = "Der søges efter",
            ["FileType"] = "Type",
            ["AnyType"] = "Alle filer",
            ["TypeDocuments"] = "Dokumenter",
            ["TypePictures"] = "Billeder",
            ["TypeMusic"] = "Musik",
            ["TypeVideos"] = "Videoer",
            ["TypeFolders"] = "Mapper",
            ["Location"] = "Søg i",
            ["AnyLocation"] = "Overalt",
            ["Modified"] = "Ændret",
            ["AnyTime"] = "Når som helst",
            ["Today"] = "I dag",
            ["ThisWeek"] = "Denne uge",
            ["ThisMonth"] = "Denne måned",
            ["ThisYear"] = "I år",
            ["Back"] = "Tilbage",
            ["Hits"] = "{0} resultater",

            ["Documents"] = "Dokumenter",
            ["RecentDocuments"] = "Seneste dokumenter",
            ["Pictures"] = "Billeder",
            ["Music"] = "Musik",
            ["Computer"] = "Denne computer",
            ["ControlPanel"] = "Kontrolpanel",
            ["SetProgramAccess"] = "Angiv programadgang og standardindstillinger",
            ["Connections"] = "Forbindelser",
            ["RemoteDesktop"] = "Fjernskrivebord",
            ["SshConnection"] = "SSH-forbindelse…",
            ["SshPrompt"] = "bruger@vært:",
            ["SshTitle"] = "SSH-forbindelse",
            ["SshSubtitle"] = "Der forbindes med Windows' egen OpenSSH-klient.",
            ["SshKey"] = "Nøglefil:",
            ["SshKeyHint"] = "Nøgler fra din .ssh-mappe. Uden en nøgle beder ssh om adgangskoden.",
            ["SshNoKey"] = "(ingen – adgangskode)",
            ["SshBrowse"] = "Vælg nøglefil…",
            ["SshConnectButton"] = "Opret forbindelse",
            ["SftpConnection"] = "SFTP-forbindelse…",
            ["TelnetConnection"] = "Telnet-forbindelse…",
            ["FtpConnection"] = "FTP-forbindelse…",
            ["NetworkFolder"] = "Åbn netværksmappe…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Port:",
            ["HostPrompt"] = "Computer:",
            ["FolderPrompt"] = "\\\\server\\share:",
            ["ConnectSubtitle"] = "Windows har selv klienten med.",
            ["MapDrive"] = "Tilknyt netværksdrev…",
            ["AllConnections"] = "Vis alle forbindelser",
            ["PrintersAndFaxes"] = "Printere og faxenheder",
            ["Help"] = "Hjælp og support",
            ["SearchPlace"] = "Søg",
            ["Run"] = "Kør...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Programmer",
            ["Favorites"] = "Favoritter",
            ["Internet"] = "Internet",
            ["Email"] = "E-mail",
            ["Empty"] = "(Tom)",

            ["LogOff"] = "Log af",
            ["LogOffClassic"] = "Log af…",
            ["ShutDownClassic"] = "Luk…",
            ["ShutDown"] = "Sluk computeren",
            ["PowerTitle"] = "Sluk computeren",
            ["Standby"] = "Standby",
            ["Hibernate"] = "Dvale",
            ["TurnOff"] = "Sluk",
            ["Restart"] = "Genstart",
            ["Lock"] = "Lås",
            ["Cancel"] = "Annuller",
            ["PowerQuestion"] = "Hvad skal computeren gøre?",

            ["Open"] = "Åbn",
            ["RunAsAdmin"] = "Kør som administrator",
            ["Pin"] = "Føj til favoritter",
            ["Unpin"] = "Fjern fra favoritter",
            ["MoveToFolder"] = "Flyt til mappe",
            ["NewFolder"] = "Ny mappe…",
            ["FolderDefaultName"] = "Mappe",
            ["OutOfFolder"] = "Flyt ud af mappen",
            ["RenameFolder"] = "Omdøb mappe…",
            ["DissolveFolder"] = "Opløs mappen",
            ["FolderNamePrompt"] = "Mappens navn:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Fjern fra denne liste",
            ["OpenFileLocation"] = "Åbn filens placering",

            ["TrayOpen"] = "Åbn menuen Start",
            ["TraySettings"] = "Indstillinger…",
            ["TrayRefresh"] = "Indlæs programlisten igen",
            ["TrayExit"] = "Afslut",

            ["SettingsTitle"] = "Retro Menu – Indstillinger",
            ["Appearance"] = "Udseende",
            ["Theme"] = "Tema",
            ["FollowRetroBar"] = "Overtag temaet fra RetroBar",
            ["Behaviour"] = "Opførsel",
            ["WinKey"] = "Windows-tasten",
            ["WinKeyNeutralize"] = "Opfang (anbefales)",
            ["WinKeySwallow"] = "Slug helt",
            ["WinKeyOff"] = "Lad den være",
            ["FrequentCount"] = "Ofte brugte: antal",
            ["ShowRecent"] = "Vis senest startede programmer",
            ["ShowTiles"] = "Favoritter som felter til højre",
            ["ShowTilesHint"] = "Et tredje panel viser favoritterne og deres mapper som felter, ligesom gitteret med fastgjorte apps i Windows 11.",
            ["TilesHeader"] = "Fastgjort",
            ["ShowRecentHint"] = "Den venstre kolonne viser så det, der blev startet sidst, i stedet for det, der startes oftest.",
            ["ShowSearchBox"] = "Vis søgefeltet (det havde XP ikke)",
            ["SearchFilesSetting"] = "Søgningen omfatter filer",
            ["MenuScale"] = "Menuens størrelse",
            ["KeepTaskbar"] = "Vis proceslinjen, mens menuen er åben",
            ["ShowStoreApps"] = "Tag Store-apps med",
            ["UseXpExplorer"] = "Åbn mapper i XP-filvinduet",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 er der og viser Dokumenter, "
                                    + "Denne computer og de øvrige steder i den gamle stil.",
            ["UseXpExplorerMissing"] = "Ikke fundet. Uden windows-xp-explorer-win-11 er det "
                                       + "Stifinder, der åbner mapperne.",
            ["UseXpExplorerBroken"] = "Fundet, men installationen er ufuldstændig, så mapperne åbnes af Stifinder.",
            ["AutoStart"] = "Start sammen med Windows",
            ["Language"] = "Sprog",
            ["Close"] = "Luk",
            ["StoreApps"] = "Store-apps",

            ["LangAutoWindows"] = "Automatisk (Windows-sprog)",
            ["LangAutoRetroBar"] = "Automatisk (RetroBar)",
            ["LangDetected"] = "Windows er indstillet til {0}.",
            ["LangShowing"] = "Menuen taler {0}.",
            ["LangUntranslated"] = "{0} er ikke oversat endnu, så engelsk træder til.",
            ["RetroBarFound"] = "RetroBar fundet – temaet ”{0}” → ”{1}”.",
            ["RetroBarMissing"] = "RetroBar blev ikke fundet.",

            ["SetupTitle"] = "Installer Retro Menu",
            ["SetupSubtitle"] = "En Start-menu i stil med ældre Windows-versioner.",
            ["SetupIntro"] = "Programmet lægges i din egen brugermappe. Der kræves ingen "
                             + "administratorrettigheder, og der ændres intet i systemet.",
            ["SetupTarget"] = "Destinationsmappe",
            ["SetupDuring"] = "Under installationen",
            ["SetupStartMenu"] = "Opret en genvej i menuen Start",
            ["SetupDesktop"] = "Opret en genvej på skrivebordet",
            ["SetupRetroBar"] = "Installer også RetroBar – proceslinjen i XP-stil",
            ["SetupRetroBarNote"] = "Hentes direkte fra github.com/dremin/RetroBar. Kontrolsummen "
                                    + "for filen står bagefter i loggen.",
            ["SetupRetroBarPresent"] = "RetroBar findes allerede",
            ["SetupInstall"] = "Installer",
            ["SetupUpdate"] = "Opdater",
            ["SetupUpdateSubtitle"] = "En eksisterende installation bliver opdateret.",
            ["SetupRemoveTitle"] = "Fjern Retro Menu",
            ["SetupRemoveSubtitle"] = "Programmet fjernes fra din brugermappe.",
            ["SetupRemoveButton"] = "Fjern",
            ["SetupRemoveText"] = "Retro Menu lukkes og fjernes fra {0}. Dine indstillinger bevares, "
                                  + "så en senere installation finder dem igen.",
            ["SetupWorking"] = "Installerer…",
            ["SetupRemoving"] = "Fjerner…",
            ["SetupDone"] = "Færdig.",
            ["SetupRemoved"] = "Fjernet.",
            ["SetupErrors"] = "Afsluttet med fejl.",
            ["SetupFailed"] = "Mislykkedes: {0}",
            ["SetupStart"] = "Start",
        };
    }
}
