using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Deutsch.</summary>
    internal static class De
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            // ---- menu and search ----
            ["AllPrograms"] = "Alle Programme",
            ["Search"] = "Suchen",
            ["SearchHint"] = "Programme durchsuchen",
            ["SearchFiles"] = "Dateien mitsuchen",
            ["BestMatch"] = "Beste Übereinstimmung",
            ["AppsGroup"] = "Apps",
            ["SettingsGroup"] = "Einstellungen",
            ["FilesGroup"] = "Dateien",
            ["Searching"] = "Sucht in den Dateien…",
            ["NoIndex"] = "Windows-Suche ist nicht verfügbar",
            ["NoResults"] = "Keine Treffer",
            ["Loading"] = "Wird geladen…",

            ["ProgramFilter"] = "Filtern:",
            ["ProgramGroups"] = "Gruppen",
            ["ProgramCount"] = "{0} Programme",

            ["AdvancedSearch"] = "Erweiterte Suche",
            ["SearchFor"] = "Suchen nach:",
            ["Categories"] = "Gesucht wird",
            ["FileType"] = "Art",
            ["AnyType"] = "Alle Dateien",
            ["TypeDocuments"] = "Dokumente",
            ["TypePictures"] = "Bilder",
            ["TypeMusic"] = "Musik",
            ["TypeVideos"] = "Videos",
            ["TypeFolders"] = "Ordner",
            ["Location"] = "Suchen in",
            ["AnyLocation"] = "Überall",
            ["Modified"] = "Geändert",
            ["AnyTime"] = "Egal wann",
            ["Today"] = "Heute",
            ["ThisWeek"] = "Diese Woche",
            ["ThisMonth"] = "Dieser Monat",
            ["ThisYear"] = "Dieses Jahr",
            ["Back"] = "Zurück",
            ["Hits"] = "{0} Treffer",

            // ---- the places on the right ----
            ["Documents"] = "Eigene Dateien",
            ["RecentDocuments"] = "Zuletzt verwendete Dokumente",
            ["Pictures"] = "Eigene Bilder",
            ["Music"] = "Eigene Musik",
            ["Computer"] = "Arbeitsplatz",
            ["ControlPanel"] = "Systemsteuerung",
            ["SetProgramAccess"] = "Programmzugriff und -standards festlegen",
            ["Connections"] = "Verbindungen",
            ["RemoteDesktop"] = "Remotedesktop",
            ["SshConnection"] = "SSH-Verbindung…",
            ["SshPrompt"] = "Benutzer@Rechner:",
            ["SshTitle"] = "SSH-Verbindung",
            ["SshSubtitle"] = "Verbunden wird mit dem OpenSSH von Windows.",
            ["SshKey"] = "Schlüsseldatei:",
            ["SshKeyHint"] = "Schlüssel aus deinem .ssh-Ordner. Ohne einen fragt ssh nach dem Kennwort.",
            ["SshNoKey"] = "(keiner – Kennwort)",
            ["SshBrowse"] = "Schlüsseldatei wählen…",
            ["SshConnectButton"] = "Verbinden",
            ["SftpConnection"] = "SFTP-Verbindung…",
            ["TelnetConnection"] = "Telnet-Verbindung…",
            ["FtpConnection"] = "FTP-Verbindung…",
            ["NetworkFolder"] = "Netzwerkordner öffnen…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Port:",
            ["HostPrompt"] = "Rechner:",
            ["FolderPrompt"] = "\\\\Server\\Freigabe:",
            ["ConnectSubtitle"] = "Den Client dafür bringt Windows selbst mit.",
            ["MapDrive"] = "Netzlaufwerk verbinden…",
            ["AllConnections"] = "Alle Verbindungen anzeigen",
            ["PrintersAndFaxes"] = "Drucker und Faxgeräte",
            ["Help"] = "Hilfe und Support",
            ["SearchPlace"] = "Suchen",
            ["Run"] = "Ausführen...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Programme",
            ["Favorites"] = "Favoriten",
            ["Internet"] = "Internet",
            ["Email"] = "E-Mail",
            ["Empty"] = "(Leer)",

            // ---- shutting down ----
            ["LogOff"] = "Abmelden",
            ["LogOffClassic"] = "Abmelden…",
            ["ShutDownClassic"] = "Beenden…",
            ["ShutDown"] = "Computer ausschalten",
            ["PowerTitle"] = "Computer ausschalten",
            ["Standby"] = "Standby",
            ["Hibernate"] = "Ruhezustand",
            ["TurnOff"] = "Ausschalten",
            ["Restart"] = "Neu starten",
            ["Lock"] = "Sperren",
            ["Cancel"] = "Abbrechen",
            ["PowerQuestion"] = "Was soll der Computer tun?",

            // ---- right-click menu ----
            ["Open"] = "Öffnen",
            ["RunAsAdmin"] = "Als Administrator ausführen",
            ["Pin"] = "Zu Favoriten hinzufügen",
            ["Unpin"] = "Aus Favoriten entfernen",
            ["MoveToFolder"] = "In Ordner verschieben",
            ["NewFolder"] = "Neuer Ordner…",
            ["FolderDefaultName"] = "Ordner",
            ["OutOfFolder"] = "Aus dem Ordner heraus",
            ["RenameFolder"] = "Ordner umbenennen…",
            ["DissolveFolder"] = "Ordner auflösen",
            ["FolderNamePrompt"] = "Name des Ordners:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Aus dieser Liste entfernen",
            ["OpenFileLocation"] = "Dateipfad öffnen",

            // ---- notification icon ----
            ["TrayOpen"] = "Startmenü öffnen",
            ["TraySettings"] = "Einstellungen…",
            ["TrayRefresh"] = "Programmliste neu einlesen",
            ["TrayExit"] = "Beenden",

            // ---- settings window ----
            ["SettingsTitle"] = "Retro-Menü – Einstellungen",
            ["Appearance"] = "Darstellung",
            ["Theme"] = "Design",
            ["FollowRetroBar"] = "Design von RetroBar übernehmen",
            ["Behaviour"] = "Verhalten",
            ["WinKey"] = "Windows-Taste",
            ["WinKeyNeutralize"] = "Abfangen (empfohlen)",
            ["WinKeySwallow"] = "Vollständig schlucken",
            ["WinKeyOff"] = "Nicht anfassen",
            ["FrequentCount"] = "Häufig verwendet: Anzahl",
            ["ShowRecent"] = "Zuletzt gestartete Programme zeigen",
            ["ShowTiles"] = "Favoriten als Kachelbereich rechts",
            ["ShowTilesHint"] = "Ein dritter Bereich zeigt die Favoriten und ihre Ordner als Kacheln, wie das Angeheftet-Raster von Windows 11.",
            ["TilesHeader"] = "Angeheftet",
            ["ShowRecentHint"] = "Statt der am häufigsten gestarteten steht dann in der linken Spalte, was zuletzt an der Reihe war.",
            ["ShowSearchBox"] = "Suchfeld anzeigen (hatte XP nicht)",
            ["SearchFilesSetting"] = "Suche schließt Dateien ein",
            ["MenuScale"] = "Menügröße",
            ["KeepTaskbar"] = "Taskleiste beim Öffnen einblenden",
            ["ShowStoreApps"] = "Store-Apps mit auflisten",
            ["UseXpExplorer"] = "Ordner im XP-Dateifenster öffnen",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 ist da und zeigt Eigene Dateien, "
                                    + "Arbeitsplatz und die anderen Orte im alten Anstrich.",
            ["UseXpExplorerMissing"] = "Nicht gefunden. Ohne windows-xp-explorer-win-11 öffnet "
                                       + "der Windows-Explorer die Ordner.",
            ["UseXpExplorerBroken"] = "Gefunden, aber die Installation ist unvollständig — die Ordner öffnet der Windows-Explorer.",
            ["AutoStart"] = "Mit Windows starten",
            ["Language"] = "Sprache",
            ["Close"] = "Schließen",
            ["StoreApps"] = "Store-Apps",

            // ---- picking a language ----
            ["LangAutoWindows"] = "Automatisch (Windows-Sprache)",
            ["LangAutoRetroBar"] = "Automatisch (RetroBar)",
            ["LangDetected"] = "Windows ist auf {0} eingestellt.",
            ["LangShowing"] = "Das Menü spricht {0}.",
            ["LangUntranslated"] = "Für {0} gibt es noch keine Übersetzung, deshalb springt Englisch ein.",
            ["RetroBarFound"] = "RetroBar gefunden – Design „{0}“ → „{1}“.",
            ["RetroBarMissing"] = "RetroBar wurde nicht gefunden.",

            // ---- setup wizard ----
            ["SetupTitle"] = "Retro Menu einrichten",
            ["SetupSubtitle"] = "Ein Startmenü im Stil älterer Windows-Versionen.",
            ["SetupIntro"] = "Das Programm wird in Ihren eigenen Benutzerordner gelegt. Es sind "
                             + "keine Administratorrechte nötig, und es wird nichts am System verändert.",
            ["SetupTarget"] = "Zielordner",
            ["SetupDuring"] = "Beim Einrichten",
            ["SetupStartMenu"] = "Verknüpfung im Startmenü anlegen",
            ["SetupDesktop"] = "Verknüpfung auf dem Desktop anlegen",
            ["SetupRetroBar"] = "RetroBar mitinstallieren – die Taskleiste im XP-Stil",
            ["SetupRetroBarNote"] = "Wird direkt von github.com/dremin/RetroBar geladen. Die "
                                    + "Prüfsumme des Downloads steht anschließend im Protokoll.",
            ["SetupRetroBarPresent"] = "RetroBar ist bereits vorhanden",
            ["SetupInstall"] = "Installieren",
            ["SetupUpdate"] = "Aktualisieren",
            ["SetupUpdateSubtitle"] = "Eine vorhandene Installation wird aktualisiert.",
            ["SetupRemoveTitle"] = "Retro Menu entfernen",
            ["SetupRemoveSubtitle"] = "Das Programm wird aus Ihrem Benutzerordner entfernt.",
            ["SetupRemoveButton"] = "Entfernen",
            ["SetupRemoveText"] = "Retro Menu wird beendet und aus {0} entfernt. Ihre Einstellungen "
                                  + "bleiben erhalten, damit eine spätere Installation sie wiederfindet.",
            ["SetupWorking"] = "Wird eingerichtet…",
            ["SetupRemoving"] = "Wird entfernt…",
            ["SetupDone"] = "Fertig.",
            ["SetupRemoved"] = "Entfernt.",
            ["SetupErrors"] = "Mit Fehlern beendet.",
            ["SetupFailed"] = "Fehlgeschlagen: {0}",
            ["SetupStart"] = "Starten",
        };
    }
}
