using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Ελληνικά.</summary>
    internal static class El
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Όλα τα προγράμματα",
            ["Search"] = "Αναζήτηση",
            ["SearchHint"] = "Αναζήτηση προγραμμάτων",
            ["SearchFiles"] = "Αναζήτηση και στα αρχεία",
            ["BestMatch"] = "Καλύτερο αποτέλεσμα",
            ["AppsGroup"] = "Εφαρμογές",
            ["SettingsGroup"] = "Ρυθμίσεις",
            ["FilesGroup"] = "Αρχεία",
            ["Searching"] = "Αναζήτηση στα αρχεία…",
            ["NoIndex"] = "Η Αναζήτηση των Windows δεν είναι διαθέσιμη",
            ["NoResults"] = "Κανένα αποτέλεσμα",
            ["Loading"] = "Φόρτωση…",

            ["ProgramFilter"] = "Φίλτρο:",
            ["ProgramGroups"] = "Ομάδες",
            ["ProgramCount"] = "{0} προγράμματα",

            ["AdvancedSearch"] = "Σύνθετη αναζήτηση",
            ["SearchFor"] = "Αναζήτηση για:",
            ["Categories"] = "Τι αναζητείται",
            ["FileType"] = "Τύπος",
            ["AnyType"] = "Όλα τα αρχεία",
            ["TypeDocuments"] = "Έγγραφα",
            ["TypePictures"] = "Εικόνες",
            ["TypeMusic"] = "Μουσική",
            ["TypeVideos"] = "Βίντεο",
            ["TypeFolders"] = "Φάκελοι",
            ["Location"] = "Αναζήτηση σε",
            ["AnyLocation"] = "Παντού",
            ["Modified"] = "Τροποποιήθηκε",
            ["AnyTime"] = "Οποτεδήποτε",
            ["Today"] = "Σήμερα",
            ["ThisWeek"] = "Αυτήν την εβδομάδα",
            ["ThisMonth"] = "Αυτόν τον μήνα",
            ["ThisYear"] = "Φέτος",
            ["Back"] = "Πίσω",
            ["Hits"] = "{0} αποτελέσματα",

            ["Documents"] = "Τα έγγραφά μου",
            ["RecentDocuments"] = "Πρόσφατα έγγραφα",
            ["Pictures"] = "Οι εικόνες μου",
            ["Music"] = "Η μουσική μου",
            ["Computer"] = "Ο υπολογιστής μου",
            ["ControlPanel"] = "Πίνακας Ελέγχου",
            ["SetProgramAccess"] = "Ορισμός πρόσβασης σε προγράμματα και προεπιλογών",
            ["Connections"] = "Συνδέσεις",
            ["RemoteDesktop"] = "Απομακρυσμένη επιφάνεια εργασίας",
            ["SshConnection"] = "Σύνδεση SSH…",
            ["SshPrompt"] = "χρήστης@υπολογιστής:",
            ["SshTitle"] = "Σύνδεση SSH",
            ["SshSubtitle"] = "Η σύνδεση γίνεται με τον OpenSSH των Windows.",
            ["SshKey"] = "Αρχείο κλειδιού:",
            ["SshKeyHint"] = "Κλειδιά από τον φάκελο .ssh. Χωρίς κλειδί, το ssh ζητά τον κωδικό.",
            ["SshNoKey"] = "(κανένα – κωδικός)",
            ["SshBrowse"] = "Επιλογή αρχείου κλειδιού…",
            ["SshConnectButton"] = "Σύνδεση",
            ["SftpConnection"] = "Σύνδεση SFTP…",
            ["TelnetConnection"] = "Σύνδεση Telnet…",
            ["FtpConnection"] = "Σύνδεση FTP…",
            ["NetworkFolder"] = "Άνοιγμα φακέλου δικτύου…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Θύρα:",
            ["HostPrompt"] = "Υπολογιστής:",
            ["FolderPrompt"] = "\\\\διακομιστής\\κοινόχρηστο:",
            ["ConnectSubtitle"] = "Τα Windows φέρνουν μόνα τους το πρόγραμμα.",
            ["MapDrive"] = "Αντιστοίχιση μονάδας δικτύου…",
            ["AllConnections"] = "Εμφάνιση όλων των συνδέσεων",
            ["PrintersAndFaxes"] = "Εκτυπωτές και φαξ",
            ["Help"] = "Βοήθεια και υποστήριξη",
            ["SearchPlace"] = "Αναζήτηση",
            ["Run"] = "Εκτέλεση...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Προγράμματα",
            ["Favorites"] = "Αγαπημένα",
            ["Internet"] = "Internet",
            ["Email"] = "Ηλεκτρονικό ταχυδρομείο",
            ["Empty"] = "(Κενό)",

            ["LogOff"] = "Αποσύνδεση",
            ["LogOffClassic"] = "Αποσύνδεση…",
            ["ShutDownClassic"] = "Τερματισμός…",
            ["ShutDown"] = "Τερματισμός λειτουργίας",
            ["PowerTitle"] = "Τερματισμός λειτουργίας",
            ["Standby"] = "Αναμονή",
            ["Hibernate"] = "Αδρανοποίηση",
            ["TurnOff"] = "Απενεργοποίηση",
            ["Restart"] = "Επανεκκίνηση",
            ["Lock"] = "Κλείδωμα",
            ["Cancel"] = "Άκυρο",
            ["PowerQuestion"] = "Τι πρέπει να κάνει ο υπολογιστής;",

            ["Open"] = "Άνοιγμα",
            ["RunAsAdmin"] = "Εκτέλεση ως διαχειριστής",
            ["Pin"] = "Προσθήκη στα αγαπημένα",
            ["Unpin"] = "Κατάργηση από τα αγαπημένα",
            ["MoveToFolder"] = "Μετακίνηση σε φάκελο",
            ["NewFolder"] = "Νέος φάκελος…",
            ["FolderDefaultName"] = "Φάκελος",
            ["OutOfFolder"] = "Έξοδος από τον φάκελο",
            ["RenameFolder"] = "Μετονομασία φακέλου…",
            ["DissolveFolder"] = "Διάλυση του φακέλου",
            ["FolderNamePrompt"] = "Όνομα φακέλου:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Κατάργηση από αυτήν τη λίστα",
            ["OpenFileLocation"] = "Άνοιγμα της θέσης του αρχείου",

            ["TrayOpen"] = "Άνοιγμα του μενού Έναρξη",
            ["TraySettings"] = "Ρυθμίσεις…",
            ["TrayRefresh"] = "Νέα ανάγνωση της λίστας προγραμμάτων",
            ["TrayExit"] = "Έξοδος",

            ["SettingsTitle"] = "Retro Menu – Ρυθμίσεις",
            ["Appearance"] = "Εμφάνιση",
            ["Theme"] = "Θέμα",
            ["FollowRetroBar"] = "Υιοθέτηση του θέματος του RetroBar",
            ["Behaviour"] = "Συμπεριφορά",
            ["WinKey"] = "Πλήκτρο Windows",
            ["WinKeyNeutralize"] = "Παρεμβολή (συνιστάται)",
            ["WinKeySwallow"] = "Πλήρης απορρόφηση",
            ["WinKeyOff"] = "Να μην πειραχτεί",
            ["FrequentCount"] = "Συχνά χρησιμοποιούμενα: πλήθος",
            ["ShowRecent"] = "Εμφάνιση των προγραμμάτων που ξεκίνησαν πρόσφατα",
            ["ShowTiles"] = "Αγαπημένα ως πλακίδια στα δεξιά",
            ["ShowTilesHint"] = "Ένα τρίτο τμήμα δείχνει τα αγαπημένα και τους φακέλους τους ως πλακίδια, όπως το πλέγμα καρφιτσωμένων εφαρμογών των Windows 11.",
            ["TilesHeader"] = "Καρφιτσωμένα",
            ["ShowRecentHint"] = "Στην αριστερή στήλη μπαίνει τότε ό,τι ξεκίνησε τελευταίο αντί για ό,τι ξεκινά συχνότερα.",
            ["ShowSearchBox"] = "Εμφάνιση πλαισίου αναζήτησης (τα XP δεν είχαν)",
            ["SearchFilesSetting"] = "Η αναζήτηση περιλαμβάνει αρχεία",
            ["MenuScale"] = "Μέγεθος του μενού",
            ["KeepTaskbar"] = "Εμφάνιση της γραμμής εργασιών όσο το μενού είναι ανοιχτό",
            ["ShowStoreApps"] = "Να συμπεριληφθούν και οι εφαρμογές του Store",
            ["UseXpExplorer"] = "Άνοιγμα των φακέλων στο παράθυρο αρχείων των XP",
            ["UseXpExplorerHint"] = "Το windows-xp-explorer-win-11 υπάρχει και θα δείξει Τα έγγραφά μου, "
                                    + "Τον υπολογιστή μου και τις υπόλοιπες θέσεις με την παλιά όψη.",
            ["UseXpExplorerMissing"] = "Δεν βρέθηκε. Χωρίς το windows-xp-explorer-win-11 τους "
                                       + "φακέλους τους ανοίγει η Εξερεύνηση των Windows.",
            ["UseXpExplorerBroken"] = "Βρέθηκε, αλλά η εγκατάσταση είναι ελλιπής, οπότε τους φακέλους τους ανοίγει η Εξερεύνηση των Windows.",
            ["AutoStart"] = "Εκκίνηση μαζί με τα Windows",
            ["Language"] = "Γλώσσα",
            ["Close"] = "Κλείσιμο",
            ["StoreApps"] = "Εφαρμογές του Store",

            ["LangAutoWindows"] = "Αυτόματα (γλώσσα των Windows)",
            ["LangAutoRetroBar"] = "Αυτόματα (RetroBar)",
            ["LangDetected"] = "Τα Windows είναι ρυθμισμένα στα {0}.",
            ["LangShowing"] = "Το μενού μιλάει {0}.",
            ["LangUntranslated"] = "Δεν υπάρχει ακόμη μετάφραση για {0}, οπότε μπαίνουν τα αγγλικά.",
            ["RetroBarFound"] = "Βρέθηκε το RetroBar – θέμα «{0}» → «{1}».",
            ["RetroBarMissing"] = "Το RetroBar δεν βρέθηκε.",

            ["SetupTitle"] = "Εγκατάσταση του Retro Menu",
            ["SetupSubtitle"] = "Ένα μενού Έναρξη στο ύφος παλαιότερων εκδόσεων των Windows.",
            ["SetupIntro"] = "Το πρόγραμμα τοποθετείται στον δικό σας φάκελο χρήστη. Δεν χρειάζονται "
                             + "δικαιώματα διαχειριστή και δεν αλλάζει τίποτα στο σύστημα.",
            ["SetupTarget"] = "Φάκελος προορισμού",
            ["SetupDuring"] = "Κατά την εγκατάσταση",
            ["SetupStartMenu"] = "Δημιουργία συντόμευσης στο μενού Έναρξη",
            ["SetupDesktop"] = "Δημιουργία συντόμευσης στην επιφάνεια εργασίας",
            ["SetupRetroBar"] = "Εγκατάσταση και του RetroBar – η γραμμή εργασιών σε ύφος XP",
            ["SetupRetroBarNote"] = "Λαμβάνεται απευθείας από το github.com/dremin/RetroBar. Το "
                                    + "άθροισμα ελέγχου της λήψης εμφανίζεται μετά στο αρχείο καταγραφής.",
            ["SetupRetroBarPresent"] = "Το RetroBar υπάρχει ήδη",
            ["SetupInstall"] = "Εγκατάσταση",
            ["SetupUpdate"] = "Ενημέρωση",
            ["SetupUpdateSubtitle"] = "Θα ενημερωθεί μια υπάρχουσα εγκατάσταση.",
            ["SetupRemoveTitle"] = "Κατάργηση του Retro Menu",
            ["SetupRemoveSubtitle"] = "Το πρόγραμμα θα καταργηθεί από τον φάκελο χρήστη σας.",
            ["SetupRemoveButton"] = "Κατάργηση",
            ["SetupRemoveText"] = "Το Retro Menu θα κλείσει και θα καταργηθεί από {0}. Οι ρυθμίσεις "
                                  + "σας διατηρούνται, ώστε μια μελλοντική εγκατάσταση να τις ξαναβρεί.",
            ["SetupWorking"] = "Γίνεται εγκατάσταση…",
            ["SetupRemoving"] = "Γίνεται κατάργηση…",
            ["SetupDone"] = "Έτοιμο.",
            ["SetupRemoved"] = "Καταργήθηκε.",
            ["SetupErrors"] = "Ολοκληρώθηκε με σφάλματα.",
            ["SetupFailed"] = "Απέτυχε: {0}",
            ["SetupStart"] = "Εκκίνηση",
        };
    }
}
