using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Español.</summary>
    internal static class Es
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Todos los programas",
            ["Search"] = "Buscar",
            ["SearchHint"] = "Buscar programas",
            ["SearchFiles"] = "Buscar también en los archivos",
            ["BestMatch"] = "Mejor resultado",
            ["AppsGroup"] = "Aplicaciones",
            ["SettingsGroup"] = "Configuración",
            ["FilesGroup"] = "Archivos",
            ["Searching"] = "Buscando en los archivos…",
            ["NoIndex"] = "La búsqueda de Windows no está disponible",
            ["NoResults"] = "Sin resultados",
            ["Loading"] = "Cargando…",

            ["ProgramFilter"] = "Filtro:",
            ["ProgramGroups"] = "Grupos",
            ["ProgramCount"] = "{0} programas",

            ["AdvancedSearch"] = "Búsqueda avanzada",
            ["SearchFor"] = "Buscar:",
            ["Categories"] = "Se busca",
            ["FileType"] = "Tipo",
            ["AnyType"] = "Todos los archivos",
            ["TypeDocuments"] = "Documentos",
            ["TypePictures"] = "Imágenes",
            ["TypeMusic"] = "Música",
            ["TypeVideos"] = "Vídeos",
            ["TypeFolders"] = "Carpetas",
            ["Location"] = "Buscar en",
            ["AnyLocation"] = "En todas partes",
            ["Modified"] = "Modificado",
            ["AnyTime"] = "En cualquier momento",
            ["Today"] = "Hoy",
            ["ThisWeek"] = "Esta semana",
            ["ThisMonth"] = "Este mes",
            ["ThisYear"] = "Este año",
            ["Back"] = "Atrás",
            ["Hits"] = "{0} resultados",

            ["Documents"] = "Mis documentos",
            ["RecentDocuments"] = "Documentos recientes",
            ["Pictures"] = "Mis imágenes",
            ["Music"] = "Mi música",
            ["Computer"] = "Mi PC",
            ["ControlPanel"] = "Panel de control",
            ["SetProgramAccess"] = "Configurar acceso y programas predeterminados",
            ["Connections"] = "Conexiones",
            ["RemoteDesktop"] = "Escritorio remoto",
            ["SshConnection"] = "Conexión SSH…",
            ["SshPrompt"] = "usuario@equipo:",
            ["SshTitle"] = "Conexión SSH",
            ["SshSubtitle"] = "Se conecta con el cliente OpenSSH de Windows.",
            ["SshKey"] = "Archivo de clave:",
            ["SshKeyHint"] = "Claves de tu carpeta .ssh. Sin una, ssh pedirá la contraseña.",
            ["SshNoKey"] = "(ninguna – contraseña)",
            ["SshBrowse"] = "Elegir archivo de clave…",
            ["SshConnectButton"] = "Conectar",
            ["SftpConnection"] = "Conexión SFTP…",
            ["TelnetConnection"] = "Conexión Telnet…",
            ["FtpConnection"] = "Conexión FTP…",
            ["NetworkFolder"] = "Abrir carpeta de red…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Puerto:",
            ["HostPrompt"] = "Equipo:",
            ["FolderPrompt"] = "\\\\servidor\\recurso:",
            ["ConnectSubtitle"] = "Windows ya trae el cliente necesario.",
            ["MapDrive"] = "Conectar a unidad de red…",
            ["AllConnections"] = "Mostrar todas las conexiones",
            ["PrintersAndFaxes"] = "Impresoras y faxes",
            ["Help"] = "Ayuda y soporte técnico",
            ["SearchPlace"] = "Buscar",
            ["Run"] = "Ejecutar...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Programas",
            ["Favorites"] = "Favoritos",
            ["Internet"] = "Internet",
            ["Email"] = "Correo electrónico",
            ["Empty"] = "(Vacío)",

            ["LogOff"] = "Cerrar sesión",
            ["LogOffClassic"] = "Cerrar sesión…",
            ["ShutDownClassic"] = "Apagar…",
            ["ShutDown"] = "Apagar equipo",
            ["PowerTitle"] = "Apagar equipo",
            ["Standby"] = "Suspender",
            ["Hibernate"] = "Hibernar",
            ["TurnOff"] = "Apagar",
            ["Restart"] = "Reiniciar",
            ["Lock"] = "Bloquear",
            ["Cancel"] = "Cancelar",
            ["PowerQuestion"] = "¿Qué debe hacer el equipo?",

            ["Open"] = "Abrir",
            ["RunAsAdmin"] = "Ejecutar como administrador",
            ["Pin"] = "Agregar a favoritos",
            ["Unpin"] = "Quitar de favoritos",
            ["MoveToFolder"] = "Mover a una carpeta",
            ["NewFolder"] = "Nueva carpeta…",
            ["FolderDefaultName"] = "Carpeta",
            ["OutOfFolder"] = "Sacar de la carpeta",
            ["RenameFolder"] = "Cambiar el nombre de la carpeta…",
            ["DissolveFolder"] = "Deshacer la carpeta",
            ["FolderNamePrompt"] = "Nombre de la carpeta:",
            ["Ok"] = "Aceptar",
            ["RemoveFromList"] = "Quitar de esta lista",
            ["OpenFileLocation"] = "Abrir la ubicación del archivo",

            ["TrayOpen"] = "Abrir el menú Inicio",
            ["TraySettings"] = "Configuración…",
            ["TrayRefresh"] = "Volver a leer la lista de programas",
            ["TrayExit"] = "Salir",

            ["SettingsTitle"] = "Retro Menu – Configuración",
            ["Appearance"] = "Apariencia",
            ["Theme"] = "Tema",
            ["FollowRetroBar"] = "Adoptar el tema de RetroBar",
            ["Behaviour"] = "Comportamiento",
            ["WinKey"] = "Tecla Windows",
            ["WinKeyNeutralize"] = "Interceptar (recomendado)",
            ["WinKeySwallow"] = "Absorber por completo",
            ["WinKeyOff"] = "No tocarla",
            ["FrequentCount"] = "Usados con frecuencia: cantidad",
            ["ShowRecent"] = "Mostrar los programas abiertos recientemente",
            ["ShowTiles"] = "Favoritos como panel de mosaicos a la derecha",
            ["ShowTilesHint"] = "Un tercer panel muestra los favoritos y sus carpetas como mosaicos, igual que la cuadrícula de aplicaciones ancladas de Windows 11.",
            ["TilesHeader"] = "Anclado",
            ["ShowRecentHint"] = "La columna izquierda mostrará entonces lo último que se abrió en lugar de lo que se abre más a menudo.",
            ["ShowSearchBox"] = "Mostrar el cuadro de búsqueda (XP no lo tenía)",
            ["SearchFilesSetting"] = "La búsqueda incluye archivos",
            ["MenuScale"] = "Tamaño del menú",
            ["KeepTaskbar"] = "Mostrar la barra de tareas al abrir",
            ["ShowStoreApps"] = "Incluir las aplicaciones de la Store",
            ["UseXpExplorer"] = "Abrir las carpetas en la ventana de archivos de XP",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 está instalado y mostrará Mis documentos, "
                                    + "Mi PC y los demás lugares con el aspecto antiguo.",
            ["UseXpExplorerMissing"] = "No se encuentra. Sin windows-xp-explorer-win-11, las carpetas "
                                       + "las abre el Explorador de Windows.",
            ["UseXpExplorerBroken"] = "Se encontró, pero la instalación está incompleta, así que las carpetas las abre el Explorador de Windows.",
            ["AutoStart"] = "Iniciar con Windows",
            ["Language"] = "Idioma",
            ["Close"] = "Cerrar",
            ["StoreApps"] = "Aplicaciones de la Store",

            ["LangAutoWindows"] = "Automático (idioma de Windows)",
            ["LangAutoRetroBar"] = "Automático (RetroBar)",
            ["LangDetected"] = "Windows está configurado en {0}.",
            ["LangShowing"] = "El menú habla {0}.",
            ["LangUntranslated"] = "{0} todavía no está traducido, así que se usa el inglés.",
            ["RetroBarFound"] = "RetroBar encontrado: tema «{0}» → «{1}».",
            ["RetroBarMissing"] = "No se encontró RetroBar.",

            ["SetupTitle"] = "Instalar Retro Menu",
            ["SetupSubtitle"] = "Un menú Inicio al estilo de las versiones antiguas de Windows.",
            ["SetupIntro"] = "El programa se coloca en su propia carpeta de usuario. No hacen falta "
                             + "permisos de administrador y no se modifica nada del sistema.",
            ["SetupTarget"] = "Carpeta de destino",
            ["SetupDuring"] = "Durante la instalación",
            ["SetupStartMenu"] = "Crear un acceso directo en el menú Inicio",
            ["SetupDesktop"] = "Crear un acceso directo en el escritorio",
            ["SetupRetroBar"] = "Instalar también RetroBar: la barra de tareas al estilo XP",
            ["SetupRetroBarNote"] = "Se descarga directamente de github.com/dremin/RetroBar. La suma "
                                    + "de comprobación de la descarga aparece después en el registro.",
            ["SetupRetroBarPresent"] = "RetroBar ya está instalado",
            ["SetupInstall"] = "Instalar",
            ["SetupUpdate"] = "Actualizar",
            ["SetupUpdateSubtitle"] = "Se actualizará una instalación existente.",
            ["SetupRemoveTitle"] = "Quitar Retro Menu",
            ["SetupRemoveSubtitle"] = "El programa se quitará de su carpeta de usuario.",
            ["SetupRemoveButton"] = "Quitar",
            ["SetupRemoveText"] = "Retro Menu se cerrará y se quitará de {0}. Su configuración se "
                                  + "conserva, para que una instalación posterior vuelva a encontrarla.",
            ["SetupWorking"] = "Instalando…",
            ["SetupRemoving"] = "Quitando…",
            ["SetupDone"] = "Listo.",
            ["SetupRemoved"] = "Quitado.",
            ["SetupErrors"] = "Finalizado con errores.",
            ["SetupFailed"] = "Error: {0}",
            ["SetupStart"] = "Iniciar",
        };
    }
}
