using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Suomi.</summary>
    internal static class Fi
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Kaikki ohjelmat",
            ["Search"] = "Etsi",
            ["SearchHint"] = "Etsi ohjelmia",
            ["SearchFiles"] = "Etsi myös tiedostoista",
            ["BestMatch"] = "Paras osuma",
            ["AppsGroup"] = "Sovellukset",
            ["SettingsGroup"] = "Asetukset",
            ["FilesGroup"] = "Tiedostot",
            ["Searching"] = "Etsitään tiedostoista…",
            ["NoIndex"] = "Windowsin haku ei ole käytettävissä",
            ["NoResults"] = "Ei osumia",
            ["Loading"] = "Ladataan…",

            ["ProgramFilter"] = "Suodatin:",
            ["ProgramGroups"] = "Ryhmät",
            ["ProgramCount"] = "{0} ohjelmaa",

            ["AdvancedSearch"] = "Tarkennettu haku",
            ["SearchFor"] = "Hae:",
            ["Categories"] = "Mitä haetaan",
            ["FileType"] = "Tyyppi",
            ["AnyType"] = "Kaikki tiedostot",
            ["TypeDocuments"] = "Asiakirjat",
            ["TypePictures"] = "Kuvat",
            ["TypeMusic"] = "Musiikki",
            ["TypeVideos"] = "Videot",
            ["TypeFolders"] = "Kansiot",
            ["Location"] = "Hae kohteesta",
            ["AnyLocation"] = "Kaikkialta",
            ["Modified"] = "Muutettu",
            ["AnyTime"] = "Milloin tahansa",
            ["Today"] = "Tänään",
            ["ThisWeek"] = "Tällä viikolla",
            ["ThisMonth"] = "Tässä kuussa",
            ["ThisYear"] = "Tänä vuonna",
            ["Back"] = "Takaisin",
            ["Hits"] = "{0} osumaa",

            ["Documents"] = "Omat tiedostot",
            ["RecentDocuments"] = "Viimeksi käytetyt tiedostot",
            ["Pictures"] = "Omat kuvatiedostot",
            ["Music"] = "Oma musiikki",
            ["Computer"] = "Oma tietokone",
            ["ControlPanel"] = "Ohjauspaneeli",
            ["SetProgramAccess"] = "Määritä ohjelmien käyttöoikeudet ja oletusarvot",
            ["Connections"] = "Yhteydet",
            ["RemoteDesktop"] = "Etätyöpöytä",
            ["SshConnection"] = "SSH-yhteys…",
            ["SshPrompt"] = "käyttäjä@kone:",
            ["SshTitle"] = "SSH-yhteys",
            ["SshSubtitle"] = "Yhteyden muodostaa Windowsin oma OpenSSH-asiakas.",
            ["SshKey"] = "Avaintiedosto:",
            ["SshKeyHint"] = "Avaimet .ssh-kansiostasi. Ilman avainta ssh kysyy salasanaa.",
            ["SshNoKey"] = "(ei mitään – salasana)",
            ["SshBrowse"] = "Valitse avaintiedosto…",
            ["SshConnectButton"] = "Yhdistä",
            ["SftpConnection"] = "SFTP-yhteys…",
            ["TelnetConnection"] = "Telnet-yhteys…",
            ["FtpConnection"] = "FTP-yhteys…",
            ["NetworkFolder"] = "Avaa verkkokansio…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Portti:",
            ["HostPrompt"] = "Tietokone:",
            ["FolderPrompt"] = "\\\\palvelin\\jako:",
            ["ConnectSubtitle"] = "Windows tuo asiakasohjelman mukanaan.",
            ["MapDrive"] = "Yhdistä verkkoasema…",
            ["AllConnections"] = "Näytä kaikki yhteydet",
            ["PrintersAndFaxes"] = "Tulostimet ja faksit",
            ["Help"] = "Ohje ja tuki",
            ["SearchPlace"] = "Etsi",
            ["Run"] = "Suorita...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Ohjelmat",
            ["Favorites"] = "Suosikit",
            ["Internet"] = "Internet",
            ["Email"] = "Sähköposti",
            ["Empty"] = "(Tyhjä)",

            ["LogOff"] = "Kirjaudu ulos",
            ["LogOffClassic"] = "Kirjaudu ulos…",
            ["ShutDownClassic"] = "Sammuta…",
            ["ShutDown"] = "Sammuta tietokone",
            ["PowerTitle"] = "Sammuta tietokone",
            ["Standby"] = "Valmiustila",
            ["Hibernate"] = "Lepotila",
            ["TurnOff"] = "Sammuta",
            ["Restart"] = "Käynnistä uudelleen",
            ["Lock"] = "Lukitse",
            ["Cancel"] = "Peruuta",
            ["PowerQuestion"] = "Mitä tietokoneen pitäisi tehdä?",

            ["Open"] = "Avaa",
            ["RunAsAdmin"] = "Suorita järjestelmänvalvojana",
            ["Pin"] = "Lisää suosikkeihin",
            ["Unpin"] = "Poista suosikeista",
            ["MoveToFolder"] = "Siirrä kansioon",
            ["NewFolder"] = "Uusi kansio…",
            ["FolderDefaultName"] = "Kansio",
            ["OutOfFolder"] = "Siirrä pois kansiosta",
            ["RenameFolder"] = "Nimeä kansio uudelleen…",
            ["DissolveFolder"] = "Pura kansio",
            ["FolderNamePrompt"] = "Kansion nimi:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Poista tästä luettelosta",
            ["OpenFileLocation"] = "Avaa tiedoston sijainti",

            ["TrayOpen"] = "Avaa Käynnistä-valikko",
            ["TraySettings"] = "Asetukset…",
            ["TrayRefresh"] = "Lue ohjelmaluettelo uudelleen",
            ["TrayExit"] = "Lopeta",

            ["SettingsTitle"] = "Retro Menu – Asetukset",
            ["Appearance"] = "Ulkoasu",
            ["Theme"] = "Teema",
            ["FollowRetroBar"] = "Käytä RetroBarin teemaa",
            ["Behaviour"] = "Toiminta",
            ["WinKey"] = "Windows-näppäin",
            ["WinKeyNeutralize"] = "Ota kiinni (suositus)",
            ["WinKeySwallow"] = "Niele kokonaan",
            ["WinKeyOff"] = "Älä koske",
            ["FrequentCount"] = "Usein käytetyt: määrä",
            ["ShowRecent"] = "Näytä viimeksi käynnistetyt ohjelmat",
            ["ShowTiles"] = "Suosikit ruutuina oikealla",
            ["ShowTilesHint"] = "Kolmas paneeli näyttää suosikit ja niiden kansiot ruutuina, samaan tapaan kuin Windows 11:n kiinnitettyjen sovellusten ruudukko.",
            ["TilesHeader"] = "Kiinnitetyt",
            ["ShowRecentHint"] = "Vasemmassa sarakkeessa on silloin viimeksi käynnistetty eikä useimmin käynnistetty.",
            ["ShowSearchBox"] = "Näytä hakukenttä (XP:ssä sitä ei ollut)",
            ["SearchFilesSetting"] = "Haku kattaa tiedostot",
            ["MenuScale"] = "Valikon koko",
            ["KeepTaskbar"] = "Näytä tehtäväpalkki, kun valikko on auki",
            ["ShowStoreApps"] = "Luettele myös Store-sovellukset",
            ["UseXpExplorer"] = "Avaa kansiot XP-tiedostoikkunassa",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 on asennettu ja näyttää Omat tiedostot, "
                                    + "Oman tietokoneen ja muut paikat vanhassa asussa.",
            ["UseXpExplorerMissing"] = "Ei löytynyt. Ilman windows-xp-explorer-win-11:tä kansiot "
                                       + "avaa Resurssienhallinta.",
            ["UseXpExplorerBroken"] = "Löytyi, mutta asennus on puutteellinen, joten kansiot avaa Resurssienhallinta.",
            ["AutoStart"] = "Käynnistä Windowsin mukana",
            ["Language"] = "Kieli",
            ["Close"] = "Sulje",
            ["StoreApps"] = "Store-sovellukset",

            ["LangAutoWindows"] = "Automaattinen (Windowsin kieli)",
            ["LangAutoRetroBar"] = "Automaattinen (RetroBar)",
            ["LangDetected"] = "Windowsin kieleksi on valittu {0}.",
            ["LangShowing"] = "Valikko puhuu kieltä {0}.",
            ["LangUntranslated"] = "Kielelle {0} ei ole vielä käännöstä, joten englanti astuu tilalle.",
            ["RetroBarFound"] = "RetroBar löytyi – teema ”{0}” → ”{1}”.",
            ["RetroBarMissing"] = "RetroBaria ei löytynyt.",

            ["SetupTitle"] = "Retro Menun asennus",
            ["SetupSubtitle"] = "Käynnistä-valikko vanhojen Windows-versioiden tyyliin.",
            ["SetupIntro"] = "Ohjelma sijoitetaan omaan käyttäjäkansioosi. Järjestelmänvalvojan "
                             + "oikeuksia ei tarvita eikä järjestelmään kosketa.",
            ["SetupTarget"] = "Kohdekansio",
            ["SetupDuring"] = "Asennuksen yhteydessä",
            ["SetupStartMenu"] = "Luo pikakuvake Käynnistä-valikkoon",
            ["SetupDesktop"] = "Luo pikakuvake työpöydälle",
            ["SetupRetroBar"] = "Asenna myös RetroBar – tehtäväpalkki XP:n tyyliin",
            ["SetupRetroBarNote"] = "Ladataan suoraan osoitteesta github.com/dremin/RetroBar. Latauksen "
                                    + "tarkistussumma näkyy jälkeenpäin lokissa.",
            ["SetupRetroBarPresent"] = "RetroBar on jo asennettu",
            ["SetupInstall"] = "Asenna",
            ["SetupUpdate"] = "Päivitä",
            ["SetupUpdateSubtitle"] = "Aiempi asennus päivitetään.",
            ["SetupRemoveTitle"] = "Poista Retro Menu",
            ["SetupRemoveSubtitle"] = "Ohjelma poistetaan käyttäjäkansiostasi.",
            ["SetupRemoveButton"] = "Poista",
            ["SetupRemoveText"] = "Retro Menu suljetaan ja poistetaan kansiosta {0}. Asetuksesi "
                                  + "säilyvät, jotta myöhempi asennus löytää ne uudelleen.",
            ["SetupWorking"] = "Asennetaan…",
            ["SetupRemoving"] = "Poistetaan…",
            ["SetupDone"] = "Valmis.",
            ["SetupRemoved"] = "Poistettu.",
            ["SetupErrors"] = "Päättyi virheisiin.",
            ["SetupFailed"] = "Epäonnistui: {0}",
            ["SetupStart"] = "Käynnistä",
        };
    }
}
