using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Français.</summary>
    internal static class Fr
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Tous les programmes",
            ["Search"] = "Rechercher",
            ["SearchHint"] = "Rechercher des programmes",
            ["SearchFiles"] = "Chercher aussi dans les fichiers",
            ["BestMatch"] = "Meilleur résultat",
            ["AppsGroup"] = "Applications",
            ["SettingsGroup"] = "Paramètres",
            ["FilesGroup"] = "Fichiers",
            ["Searching"] = "Recherche dans les fichiers…",
            ["NoIndex"] = "La recherche Windows n'est pas disponible",
            ["NoResults"] = "Aucun résultat",
            ["Loading"] = "Chargement…",

            ["ProgramFilter"] = "Filtre :",
            ["ProgramGroups"] = "Groupes",
            ["ProgramCount"] = "{0} programmes",

            ["AdvancedSearch"] = "Recherche avancée",
            ["SearchFor"] = "Rechercher :",
            ["Categories"] = "Ce qui est cherché",
            ["FileType"] = "Type",
            ["AnyType"] = "Tous les fichiers",
            ["TypeDocuments"] = "Documents",
            ["TypePictures"] = "Images",
            ["TypeMusic"] = "Musique",
            ["TypeVideos"] = "Vidéos",
            ["TypeFolders"] = "Dossiers",
            ["Location"] = "Rechercher dans",
            ["AnyLocation"] = "Partout",
            ["Modified"] = "Modifié",
            ["AnyTime"] = "N'importe quand",
            ["Today"] = "Aujourd'hui",
            ["ThisWeek"] = "Cette semaine",
            ["ThisMonth"] = "Ce mois-ci",
            ["ThisYear"] = "Cette année",
            ["Back"] = "Retour",
            ["Hits"] = "{0} résultats",

            ["Documents"] = "Mes documents",
            ["RecentDocuments"] = "Mes documents récents",
            ["Pictures"] = "Mes images",
            ["Music"] = "Ma musique",
            ["Computer"] = "Poste de travail",
            ["ControlPanel"] = "Panneau de configuration",
            ["SetProgramAccess"] = "Configurer l'accès aux programmes et les valeurs par défaut",
            ["Connections"] = "Connexions",
            ["RemoteDesktop"] = "Bureau à distance",
            ["SshConnection"] = "Connexion SSH…",
            ["SshPrompt"] = "utilisateur@hôte :",
            ["SshTitle"] = "Connexion SSH",
            ["SshSubtitle"] = "La connexion passe par le client OpenSSH de Windows.",
            ["SshKey"] = "Fichier de clé :",
            ["SshKeyHint"] = "Clés trouvées dans votre dossier .ssh. Sans clé, ssh demande le mot de passe.",
            ["SshNoKey"] = "(aucune – mot de passe)",
            ["SshBrowse"] = "Choisir un fichier de clé…",
            ["SshConnectButton"] = "Se connecter",
            ["SftpConnection"] = "Connexion SFTP…",
            ["TelnetConnection"] = "Connexion Telnet…",
            ["FtpConnection"] = "Connexion FTP…",
            ["NetworkFolder"] = "Ouvrir un dossier réseau…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Port :",
            ["HostPrompt"] = "Ordinateur :",
            ["FolderPrompt"] = "\\\\serveur\\partage :",
            ["ConnectSubtitle"] = "Windows fournit lui-même le client.",
            ["MapDrive"] = "Connecter un lecteur réseau…",
            ["AllConnections"] = "Afficher toutes les connexions",
            ["PrintersAndFaxes"] = "Imprimantes et télécopieurs",
            ["Help"] = "Aide et support",
            ["SearchPlace"] = "Rechercher",
            ["Run"] = "Exécuter...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Programmes",
            ["Favorites"] = "Favoris",
            ["Internet"] = "Internet",
            ["Email"] = "Courrier électronique",
            ["Empty"] = "(Vide)",

            ["LogOff"] = "Fermer la session",
            ["LogOffClassic"] = "Fermer la session…",
            ["ShutDownClassic"] = "Arrêter…",
            ["ShutDown"] = "Arrêter l'ordinateur",
            ["PowerTitle"] = "Arrêter l'ordinateur",
            ["Standby"] = "Mettre en veille",
            ["Hibernate"] = "Mettre en veille prolongée",
            ["TurnOff"] = "Arrêter",
            ["Restart"] = "Redémarrer",
            ["Lock"] = "Verrouiller",
            ["Cancel"] = "Annuler",
            ["PowerQuestion"] = "Que doit faire l'ordinateur ?",

            ["Open"] = "Ouvrir",
            ["RunAsAdmin"] = "Exécuter en tant qu'administrateur",
            ["Pin"] = "Ajouter aux favoris",
            ["Unpin"] = "Retirer des favoris",
            ["MoveToFolder"] = "Déplacer vers un dossier",
            ["NewFolder"] = "Nouveau dossier…",
            ["FolderDefaultName"] = "Dossier",
            ["OutOfFolder"] = "Sortir du dossier",
            ["RenameFolder"] = "Renommer le dossier…",
            ["DissolveFolder"] = "Dissoudre le dossier",
            ["FolderNamePrompt"] = "Nom du dossier :",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Retirer de cette liste",
            ["OpenFileLocation"] = "Ouvrir l'emplacement du fichier",

            ["TrayOpen"] = "Ouvrir le menu Démarrer",
            ["TraySettings"] = "Paramètres…",
            ["TrayRefresh"] = "Relire la liste des programmes",
            ["TrayExit"] = "Quitter",

            ["SettingsTitle"] = "Retro Menu – Paramètres",
            ["Appearance"] = "Apparence",
            ["Theme"] = "Thème",
            ["FollowRetroBar"] = "Reprendre le thème de RetroBar",
            ["Behaviour"] = "Comportement",
            ["WinKey"] = "Touche Windows",
            ["WinKeyNeutralize"] = "Intercepter (recommandé)",
            ["WinKeySwallow"] = "Absorber complètement",
            ["WinKeyOff"] = "Ne pas y toucher",
            ["FrequentCount"] = "Programmes fréquents : nombre",
            ["ShowRecent"] = "Afficher les programmes lancés récemment",
            ["ShowTiles"] = "Favoris en vignettes à droite",
            ["ShowTilesHint"] = "Un troisième volet montre les favoris et leurs dossiers sous forme de vignettes, comme la grille des applications épinglées de Windows 11.",
            ["TilesHeader"] = "Épinglé",
            ["ShowRecentHint"] = "La colonne de gauche montre alors ce qui a été lancé en dernier plutôt que ce qui est lancé le plus souvent.",
            ["ShowSearchBox"] = "Afficher la zone de recherche (XP n'en avait pas)",
            ["SearchFilesSetting"] = "La recherche inclut les fichiers",
            ["MenuScale"] = "Taille du menu",
            ["KeepTaskbar"] = "Afficher la barre des tâches à l'ouverture",
            ["ShowStoreApps"] = "Lister les applications du Store",
            ["UseXpExplorer"] = "Ouvrir les dossiers dans la fenêtre de fichiers XP",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 est installé et affichera Mes documents, "
                                    + "Poste de travail et les autres emplacements à l'ancienne.",
            ["UseXpExplorerMissing"] = "Introuvable. Sans windows-xp-explorer-win-11, c'est "
                                       + "l'Explorateur Windows qui ouvre les dossiers.",
            ["UseXpExplorerBroken"] = "Trouvé, mais l'installation est incomplète : c'est l'Explorateur Windows qui ouvre les dossiers.",
            ["AutoStart"] = "Démarrer avec Windows",
            ["Language"] = "Langue",
            ["Close"] = "Fermer",
            ["StoreApps"] = "Applications du Store",

            ["LangAutoWindows"] = "Automatique (langue de Windows)",
            ["LangAutoRetroBar"] = "Automatique (RetroBar)",
            ["LangDetected"] = "Windows est réglé sur {0}.",
            ["LangShowing"] = "Le menu parle {0}.",
            ["LangUntranslated"] = "{0} n'est pas encore traduit, l'anglais prend le relais.",
            ["RetroBarFound"] = "RetroBar trouvé – thème « {0} » → « {1} ».",
            ["RetroBarMissing"] = "RetroBar est introuvable.",

            ["SetupTitle"] = "Installer Retro Menu",
            ["SetupSubtitle"] = "Un menu Démarrer dans le style des anciennes versions de Windows.",
            ["SetupIntro"] = "Le programme est placé dans votre propre dossier utilisateur. Aucun "
                             + "droit d'administrateur n'est nécessaire et rien n'est modifié dans le système.",
            ["SetupTarget"] = "Dossier de destination",
            ["SetupDuring"] = "Pendant l'installation",
            ["SetupStartMenu"] = "Créer un raccourci dans le menu Démarrer",
            ["SetupDesktop"] = "Créer un raccourci sur le Bureau",
            ["SetupRetroBar"] = "Installer aussi RetroBar – la barre des tâches façon XP",
            ["SetupRetroBarNote"] = "Téléchargé directement depuis github.com/dremin/RetroBar. La "
                                    + "somme de contrôle du téléchargement apparaît ensuite dans le journal.",
            ["SetupRetroBarPresent"] = "RetroBar est déjà installé",
            ["SetupInstall"] = "Installer",
            ["SetupUpdate"] = "Mettre à jour",
            ["SetupUpdateSubtitle"] = "Une installation existante sera mise à jour.",
            ["SetupRemoveTitle"] = "Supprimer Retro Menu",
            ["SetupRemoveSubtitle"] = "Le programme sera retiré de votre dossier utilisateur.",
            ["SetupRemoveButton"] = "Supprimer",
            ["SetupRemoveText"] = "Retro Menu va être fermé et supprimé de {0}. Vos paramètres sont "
                                  + "conservés, afin qu'une installation ultérieure les retrouve.",
            ["SetupWorking"] = "Installation…",
            ["SetupRemoving"] = "Suppression…",
            ["SetupDone"] = "Terminé.",
            ["SetupRemoved"] = "Supprimé.",
            ["SetupErrors"] = "Terminé avec des erreurs.",
            ["SetupFailed"] = "Échec : {0}",
            ["SetupStart"] = "Démarrer",
        };
    }
}
