using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Magyar.</summary>
    internal static class Hu
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Minden program",
            ["Search"] = "Keresés",
            ["SearchHint"] = "Keresés a programok között",
            ["SearchFiles"] = "Keresés a fájlokban is",
            ["BestMatch"] = "Legjobb találat",
            ["AppsGroup"] = "Alkalmazások",
            ["SettingsGroup"] = "Beállítások",
            ["FilesGroup"] = "Fájlok",
            ["Searching"] = "Keresés a fájlokban…",
            ["NoIndex"] = "A Windows Keresés nem érhető el",
            ["NoResults"] = "Nincs találat",
            ["Loading"] = "Betöltés…",

            ["ProgramFilter"] = "Szűrő:",
            ["ProgramGroups"] = "Csoportok",
            ["ProgramCount"] = "{0} program",

            ["AdvancedSearch"] = "Speciális keresés",
            ["SearchFor"] = "Keresés:",
            ["Categories"] = "Mit keresünk",
            ["FileType"] = "Típus",
            ["AnyType"] = "Minden fájl",
            ["TypeDocuments"] = "Dokumentumok",
            ["TypePictures"] = "Képek",
            ["TypeMusic"] = "Zene",
            ["TypeVideos"] = "Videók",
            ["TypeFolders"] = "Mappák",
            ["Location"] = "Hol keressen",
            ["AnyLocation"] = "Mindenhol",
            ["Modified"] = "Módosítva",
            ["AnyTime"] = "Bármikor",
            ["Today"] = "Ma",
            ["ThisWeek"] = "Ezen a héten",
            ["ThisMonth"] = "Ebben a hónapban",
            ["ThisYear"] = "Idén",
            ["Back"] = "Vissza",
            ["Hits"] = "{0} találat",

            ["Documents"] = "Dokumentumok",
            ["RecentDocuments"] = "Legutóbbi dokumentumok",
            ["Pictures"] = "Képek",
            ["Music"] = "Zene",
            ["Computer"] = "Sajátgép",
            ["ControlPanel"] = "Vezérlőpult",
            ["SetProgramAccess"] = "Programok és alapértelmezések beállítása",
            ["Connections"] = "Kapcsolatok",
            ["RemoteDesktop"] = "Távoli asztal",
            ["SshConnection"] = "SSH-kapcsolat…",
            ["SshPrompt"] = "felhasználó@gép:",
            ["SshTitle"] = "SSH-kapcsolat",
            ["SshSubtitle"] = "A kapcsolatot a Windows OpenSSH kliense hozza létre.",
            ["SshKey"] = "Kulcsfájl:",
            ["SshKeyHint"] = "A .ssh mappában talált kulcsok. Kulcs nélkül az ssh jelszót kér.",
            ["SshNoKey"] = "(nincs – jelszó)",
            ["SshBrowse"] = "Kulcsfájl választása…",
            ["SshConnectButton"] = "Kapcsolódás",
            ["SftpConnection"] = "SFTP-kapcsolat…",
            ["TelnetConnection"] = "Telnet-kapcsolat…",
            ["FtpConnection"] = "FTP-kapcsolat…",
            ["NetworkFolder"] = "Hálózati mappa megnyitása…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Port:",
            ["HostPrompt"] = "Számítógép:",
            ["FolderPrompt"] = "\\\\kiszolgáló\\megosztás:",
            ["ConnectSubtitle"] = "Az ügyfélprogramot a Windows hozza magával.",
            ["MapDrive"] = "Hálózati meghajtó csatlakoztatása…",
            ["AllConnections"] = "Az összes kapcsolat megjelenítése",
            ["PrintersAndFaxes"] = "Nyomtatók és faxok",
            ["Help"] = "Súgó és támogatás",
            ["SearchPlace"] = "Keresés",
            ["Run"] = "Futtatás...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Programok",
            ["Favorites"] = "Kedvencek",
            ["Internet"] = "Internet",
            ["Email"] = "E-mail",
            ["Empty"] = "(Üres)",

            ["LogOff"] = "Kijelentkezés",
            ["LogOffClassic"] = "Kijelentkezés…",
            ["ShutDownClassic"] = "Leállítás…",
            ["ShutDown"] = "A számítógép kikapcsolása",
            ["PowerTitle"] = "A számítógép kikapcsolása",
            ["Standby"] = "Készenlét",
            ["Hibernate"] = "Hibernálás",
            ["TurnOff"] = "Kikapcsolás",
            ["Restart"] = "Újraindítás",
            ["Lock"] = "Zárolás",
            ["Cancel"] = "Mégse",
            ["PowerQuestion"] = "Mit tegyen a számítógép?",

            ["Open"] = "Megnyitás",
            ["RunAsAdmin"] = "Futtatás rendszergazdaként",
            ["Pin"] = "Hozzáadás a kedvencekhez",
            ["Unpin"] = "Eltávolítás a kedvencekből",
            ["MoveToFolder"] = "Áthelyezés mappába",
            ["NewFolder"] = "Új mappa…",
            ["FolderDefaultName"] = "Mappa",
            ["OutOfFolder"] = "Kivétel a mappából",
            ["RenameFolder"] = "Mappa átnevezése…",
            ["DissolveFolder"] = "Mappa feloldása",
            ["FolderNamePrompt"] = "A mappa neve:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Eltávolítás ebből a listából",
            ["OpenFileLocation"] = "Fájl helyének megnyitása",

            ["TrayOpen"] = "A Start menü megnyitása",
            ["TraySettings"] = "Beállítások…",
            ["TrayRefresh"] = "A programlista újraolvasása",
            ["TrayExit"] = "Kilépés",

            ["SettingsTitle"] = "Retro Menu – Beállítások",
            ["Appearance"] = "Megjelenés",
            ["Theme"] = "Téma",
            ["FollowRetroBar"] = "A RetroBar témájának átvétele",
            ["Behaviour"] = "Viselkedés",
            ["WinKey"] = "Windows billentyű",
            ["WinKeyNeutralize"] = "Elfogás (ajánlott)",
            ["WinKeySwallow"] = "Teljes elnyelés",
            ["WinKeyOff"] = "Ne nyúljon hozzá",
            ["FrequentCount"] = "Gyakran használt: darabszám",
            ["ShowRecent"] = "A legutóbb indított programok mutatása",
            ["ShowTiles"] = "Kedvencek csempeként a jobb oldalon",
            ["ShowTilesHint"] = "Egy harmadik panel csempeként mutatja a kedvenceket és mappáikat, ahogy a Windows 11 rendezi a kitűzött alkalmazásokat.",
            ["TilesHeader"] = "Kitűzve",
            ["ShowRecentHint"] = "A bal oldali oszlopban ekkor az áll, amit utoljára indítottak, nem pedig az, amit a leggyakrabban.",
            ["ShowSearchBox"] = "Keresőmező megjelenítése (az XP-ben nem volt)",
            ["SearchFilesSetting"] = "A keresés kiterjed a fájlokra",
            ["MenuScale"] = "A menü mérete",
            ["KeepTaskbar"] = "A tálca mutatása, amíg a menü nyitva van",
            ["ShowStoreApps"] = "A Store-alkalmazások felsorolása is",
            ["UseXpExplorer"] = "A mappák megnyitása az XP-fájlablakban",
            ["UseXpExplorerHint"] = "A windows-xp-explorer-win-11 megvan, és a Dokumentumokat, a "
                                    + "Sajátgépet és a többi helyet a régi külsővel mutatja.",
            ["UseXpExplorerMissing"] = "Nem található. A windows-xp-explorer-win-11 nélkül a "
                                       + "mappákat az Intéző nyitja meg.",
            ["UseXpExplorerBroken"] = "Megvan, de a telepítés hiányos, ezért a mappákat az Intéző nyitja meg.",
            ["AutoStart"] = "Indítás a Windowszal",
            ["Language"] = "Nyelv",
            ["Close"] = "Bezárás",
            ["StoreApps"] = "Store-alkalmazások",

            ["LangAutoWindows"] = "Automatikus (a Windows nyelve)",
            ["LangAutoRetroBar"] = "Automatikus (RetroBar)",
            ["LangDetected"] = "A Windows nyelve: {0}.",
            ["LangShowing"] = "A menü nyelve: {0}.",
            ["LangUntranslated"] = "A(z) {0} nyelvhez még nincs fordítás, ezért az angol ugrik be.",
            ["RetroBarFound"] = "RetroBar megtalálva – téma: „{0}” → „{1}”.",
            ["RetroBarMissing"] = "A RetroBar nem található.",

            ["SetupTitle"] = "A Retro Menu telepítése",
            ["SetupSubtitle"] = "Start menü a régebbi Windows-változatok stílusában.",
            ["SetupIntro"] = "A program a saját felhasználói mappájába kerül. Nincs szükség "
                             + "rendszergazdai jogokra, és a rendszerben semmi nem változik.",
            ["SetupTarget"] = "Célmappa",
            ["SetupDuring"] = "A telepítés során",
            ["SetupStartMenu"] = "Parancsikon létrehozása a Start menüben",
            ["SetupDesktop"] = "Parancsikon létrehozása az asztalon",
            ["SetupRetroBar"] = "A RetroBar telepítése is – a tálca XP stílusban",
            ["SetupRetroBarNote"] = "Közvetlenül a github.com/dremin/RetroBar címről töltődik le. A "
                                    + "letöltés ellenőrzőösszege utána megjelenik a naplóban.",
            ["SetupRetroBarPresent"] = "A RetroBar már megvan",
            ["SetupInstall"] = "Telepítés",
            ["SetupUpdate"] = "Frissítés",
            ["SetupUpdateSubtitle"] = "Egy meglévő telepítés frissül.",
            ["SetupRemoveTitle"] = "A Retro Menu eltávolítása",
            ["SetupRemoveSubtitle"] = "A program eltűnik a felhasználói mappájából.",
            ["SetupRemoveButton"] = "Eltávolítás",
            ["SetupRemoveText"] = "A Retro Menu bezárul, és eltűnik innen: {0}. A beállításai "
                                  + "megmaradnak, hogy egy későbbi telepítés újra megtalálja őket.",
            ["SetupWorking"] = "Telepítés…",
            ["SetupRemoving"] = "Eltávolítás…",
            ["SetupDone"] = "Kész.",
            ["SetupRemoved"] = "Eltávolítva.",
            ["SetupErrors"] = "Hibákkal fejeződött be.",
            ["SetupFailed"] = "Sikertelen: {0}",
            ["SetupStart"] = "Indítás",
        };
    }
}
