using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Italiano.</summary>
    internal static class It
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Tutti i programmi",
            ["Search"] = "Cerca",
            ["SearchHint"] = "Cerca tra i programmi",
            ["SearchFiles"] = "Cerca anche nei file",
            ["BestMatch"] = "Risultato migliore",
            ["AppsGroup"] = "App",
            ["SettingsGroup"] = "Impostazioni",
            ["FilesGroup"] = "File",
            ["Searching"] = "Ricerca nei file…",
            ["NoIndex"] = "La ricerca di Windows non è disponibile",
            ["NoResults"] = "Nessun risultato",
            ["Loading"] = "Caricamento…",

            ["ProgramFilter"] = "Filtro:",
            ["ProgramGroups"] = "Gruppi",
            ["ProgramCount"] = "{0} programmi",

            ["AdvancedSearch"] = "Ricerca avanzata",
            ["SearchFor"] = "Cerca:",
            ["Categories"] = "Che cosa cercare",
            ["FileType"] = "Tipo",
            ["AnyType"] = "Tutti i file",
            ["TypeDocuments"] = "Documenti",
            ["TypePictures"] = "Immagini",
            ["TypeMusic"] = "Musica",
            ["TypeVideos"] = "Video",
            ["TypeFolders"] = "Cartelle",
            ["Location"] = "Cerca in",
            ["AnyLocation"] = "Ovunque",
            ["Modified"] = "Modificato",
            ["AnyTime"] = "In qualsiasi momento",
            ["Today"] = "Oggi",
            ["ThisWeek"] = "Questa settimana",
            ["ThisMonth"] = "Questo mese",
            ["ThisYear"] = "Quest'anno",
            ["Back"] = "Indietro",
            ["Hits"] = "{0} risultati",

            ["Documents"] = "Documenti",
            ["RecentDocuments"] = "Documenti recenti",
            ["Pictures"] = "Immagini",
            ["Music"] = "Musica",
            ["Computer"] = "Risorse del computer",
            ["ControlPanel"] = "Pannello di controllo",
            ["SetProgramAccess"] = "Impostazioni accesso ai programmi",
            ["Connections"] = "Connessioni",
            ["RemoteDesktop"] = "Desktop remoto",
            ["SshConnection"] = "Connessione SSH…",
            ["SshPrompt"] = "utente@host:",
            ["SshTitle"] = "Connessione SSH",
            ["SshSubtitle"] = "Si collega con il client OpenSSH di Windows.",
            ["SshKey"] = "File di chiave:",
            ["SshKeyHint"] = "Chiavi dalla cartella .ssh. Senza chiave ssh chiede la password.",
            ["SshNoKey"] = "(nessuna – password)",
            ["SshBrowse"] = "Scegli un file di chiave…",
            ["SshConnectButton"] = "Connetti",
            ["SftpConnection"] = "Connessione SFTP…",
            ["TelnetConnection"] = "Connessione Telnet…",
            ["FtpConnection"] = "Connessione FTP…",
            ["NetworkFolder"] = "Apri cartella di rete…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Porta:",
            ["HostPrompt"] = "Computer:",
            ["FolderPrompt"] = "\\\\server\\condivisione:",
            ["ConnectSubtitle"] = "Il client lo porta Windows stesso.",
            ["MapDrive"] = "Connetti unità di rete…",
            ["AllConnections"] = "Mostra tutte le connessioni",
            ["PrintersAndFaxes"] = "Stampanti e fax",
            ["Help"] = "Guida in linea e supporto tecnico",
            ["SearchPlace"] = "Cerca",
            ["Run"] = "Esegui...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Programmi",
            ["Favorites"] = "Preferiti",
            ["Internet"] = "Internet",
            ["Email"] = "Posta elettronica",
            ["Empty"] = "(Vuoto)",

            ["LogOff"] = "Disconnetti",
            ["LogOffClassic"] = "Disconnetti…",
            ["ShutDownClassic"] = "Spegni…",
            ["ShutDown"] = "Spegni computer",
            ["PowerTitle"] = "Spegni computer",
            ["Standby"] = "Standby",
            ["Hibernate"] = "Sospensione",
            ["TurnOff"] = "Spegni",
            ["Restart"] = "Riavvia",
            ["Lock"] = "Blocca",
            ["SwitchUser"] = "Cambia utente",
            ["LogOffTitle"] = "Disconnessione da Windows",
            ["Cancel"] = "Annulla",
            ["PowerQuestion"] = "Che cosa deve fare il computer?",

            ["Open"] = "Apri",
            ["RunAsAdmin"] = "Esegui come amministratore",
            ["Pin"] = "Aggiungi ai preferiti",
            ["Unpin"] = "Rimuovi dai preferiti",
            ["MoveToFolder"] = "Sposta in una cartella",
            ["NewFolder"] = "Nuova cartella…",
            ["FolderDefaultName"] = "Cartella",
            ["OutOfFolder"] = "Porta fuori dalla cartella",
            ["RenameFolder"] = "Rinomina cartella…",
            ["DissolveFolder"] = "Sciogli la cartella",
            ["FolderNamePrompt"] = "Nome della cartella:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Rimuovi da questo elenco",
            ["OpenFileLocation"] = "Apri percorso file",

            ["TrayOpen"] = "Apri il menu Start",
            ["TraySettings"] = "Impostazioni…",
            ["TrayRefresh"] = "Rileggi l'elenco dei programmi",
            ["TrayExit"] = "Esci",

            ["SettingsTitle"] = "Retro Menu – Impostazioni",
            ["Appearance"] = "Aspetto",
            ["Theme"] = "Tema",
            ["FollowRetroBar"] = "Usa il tema di RetroBar",
            ["Behaviour"] = "Comportamento",
            ["WinKey"] = "Tasto Windows",
            ["WinKeyNeutralize"] = "Intercetta (consigliato)",
            ["WinKeySwallow"] = "Assorbi completamente",
            ["WinKeyOff"] = "Non toccarlo",
            ["FrequentCount"] = "Usati di frequente: quantità",
            ["ShowRecent"] = "Mostra i programmi avviati di recente",
            ["ShowTiles"] = "Preferiti come riquadri a destra",
            ["ShowTilesHint"] = "Un terzo pannello mostra i preferiti e le loro cartelle come riquadri, come la griglia delle app aggiunte di Windows 11.",
            ["TilesHeader"] = "Aggiunti",
            ["ShowRecentHint"] = "La colonna di sinistra elenca allora ciò che è stato avviato per ultimo invece di ciò che si avvia più spesso.",
            ["ShowSearchBox"] = "Mostra la casella di ricerca (XP non l'aveva)",
            ["SearchFilesSetting"] = "La ricerca include i file",
            ["MenuScale"] = "Dimensione del menu",
            ["KeepTaskbar"] = "Mostra la barra delle applicazioni all'apertura",
            ["ShowStoreApps"] = "Elenca anche le app dello Store",
            ["UseXpExplorer"] = "Apri le cartelle nella finestra file di XP",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 è presente e mostrerà Documenti, "
                                    + "Risorse del computer e gli altri percorsi con l'aspetto di un tempo.",
            ["UseXpExplorerMissing"] = "Non trovato. Senza windows-xp-explorer-win-11 le cartelle "
                                       + "vengono aperte da Esplora risorse.",
            ["UseXpExplorerBroken"] = "Trovato, ma l'installazione è incompleta: le cartelle vengono aperte da Esplora risorse.",
            ["AutoStart"] = "Avvia con Windows",
            ["Language"] = "Lingua",
            ["Close"] = "Chiudi",
            ["StoreApps"] = "App dello Store",

            ["LangAutoWindows"] = "Automatico (lingua di Windows)",
            ["LangAutoRetroBar"] = "Automatico (RetroBar)",
            ["LangDetected"] = "Windows è impostato su {0}.",
            ["LangShowing"] = "Il menu parla {0}.",
            ["LangUntranslated"] = "{0} non è ancora tradotto, quindi subentra l'inglese.",
            ["RetroBarFound"] = "RetroBar trovato – tema «{0}» → «{1}».",
            ["RetroBarMissing"] = "RetroBar non è stato trovato.",

            ["SetupTitle"] = "Installazione di Retro Menu",
            ["SetupSubtitle"] = "Un menu Start nello stile delle vecchie versioni di Windows.",
            ["SetupIntro"] = "Il programma viene messo nella tua cartella utente. Non servono "
                             + "diritti di amministratore e non viene modificato nulla nel sistema.",
            ["SetupTarget"] = "Cartella di destinazione",
            ["SetupDuring"] = "Durante l'installazione",
            ["SetupStartMenu"] = "Crea un collegamento nel menu Start",
            ["SetupDesktop"] = "Crea un collegamento sul desktop",
            ["SetupRetroBar"] = "Installa anche RetroBar – la barra delle applicazioni in stile XP",
            ["SetupRetroBarNote"] = "Viene scaricato direttamente da github.com/dremin/RetroBar. Il "
                                    + "codice di controllo del download compare poi nel registro.",
            ["SetupRetroBarPresent"] = "RetroBar è già presente",
            ["SetupInstall"] = "Installa",
            ["SetupUpdate"] = "Aggiorna",
            ["SetupUpdateSubtitle"] = "Verrà aggiornata un'installazione esistente.",
            ["SetupRemoveTitle"] = "Rimuovi Retro Menu",
            ["SetupRemoveSubtitle"] = "Il programma verrà rimosso dalla tua cartella utente.",
            ["SetupRemoveButton"] = "Rimuovi",
            ["SetupRemoveText"] = "Retro Menu verrà chiuso e rimosso da {0}. Le tue impostazioni "
                                  + "restano, così una futura installazione le ritrova.",
            ["SetupWorking"] = "Installazione in corso…",
            ["SetupRemoving"] = "Rimozione in corso…",
            ["SetupDone"] = "Fatto.",
            ["SetupRemoved"] = "Rimosso.",
            ["SetupErrors"] = "Terminato con errori.",
            ["SetupFailed"] = "Non riuscito: {0}",
            ["SetupStart"] = "Avvia",
        };
    }
}
