using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>日本語.</summary>
    internal static class Ja
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "すべてのプログラム",
            ["Search"] = "検索",
            ["SearchHint"] = "プログラムを検索",
            ["SearchFiles"] = "ファイルも検索する",
            ["BestMatch"] = "最も一致するもの",
            ["AppsGroup"] = "アプリ",
            ["SettingsGroup"] = "設定",
            ["FilesGroup"] = "ファイル",
            ["Searching"] = "ファイルを検索しています…",
            ["NoIndex"] = "Windows Search を利用できません",
            ["NoResults"] = "該当なし",
            ["Loading"] = "読み込んでいます…",

            ["ProgramFilter"] = "絞り込み:",
            ["ProgramGroups"] = "グループ",
            ["ProgramCount"] = "{0} 個のプログラム",

            ["AdvancedSearch"] = "詳細検索",
            ["SearchFor"] = "検索する語:",
            ["Categories"] = "探すもの",
            ["FileType"] = "種類",
            ["AnyType"] = "すべてのファイル",
            ["TypeDocuments"] = "ドキュメント",
            ["TypePictures"] = "画像",
            ["TypeMusic"] = "音楽",
            ["TypeVideos"] = "ビデオ",
            ["TypeFolders"] = "フォルダ",
            ["Location"] = "探す場所",
            ["AnyLocation"] = "すべての場所",
            ["Modified"] = "更新日時",
            ["AnyTime"] = "いつでも",
            ["Today"] = "今日",
            ["ThisWeek"] = "今週",
            ["ThisMonth"] = "今月",
            ["ThisYear"] = "今年",
            ["Back"] = "戻る",
            ["Hits"] = "{0} 件",

            ["Documents"] = "マイ ドキュメント",
            ["RecentDocuments"] = "最近使ったファイル",
            ["Pictures"] = "マイ ピクチャ",
            ["Music"] = "マイ ミュージック",
            ["Computer"] = "マイ コンピュータ",
            ["ControlPanel"] = "コントロール パネル",
            ["SetProgramAccess"] = "プログラムのアクセスと既定の設定",
            ["Connections"] = "接続",
            ["RemoteDesktop"] = "リモート デスクトップ",
            ["SshConnection"] = "SSH 接続…",
            ["SshPrompt"] = "ユーザー@ホスト:",
            ["SshTitle"] = "SSH 接続",
            ["SshSubtitle"] = "接続には Windows 付属の OpenSSH を使います。",
            ["SshKey"] = "鍵ファイル:",
            ["SshKeyHint"] = ".ssh フォルダにある鍵です。鍵がなければ ssh がパスワードを尋ねます。",
            ["SshNoKey"] = "(なし – パスワード)",
            ["SshBrowse"] = "鍵ファイルを選ぶ…",
            ["SshConnectButton"] = "接続",
            ["SftpConnection"] = "SFTP 接続…",
            ["TelnetConnection"] = "Telnet 接続…",
            ["FtpConnection"] = "FTP 接続…",
            ["NetworkFolder"] = "ネットワーク フォルダーを開く…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "ポート:",
            ["HostPrompt"] = "コンピューター:",
            ["FolderPrompt"] = "\\\\サーバー\\共有:",
            ["ConnectSubtitle"] = "クライアントは Windows に付属しています。",
            ["MapDrive"] = "ネットワーク ドライブの割り当て…",
            ["AllConnections"] = "すべての接続を表示",
            ["PrintersAndFaxes"] = "プリンタと FAX",
            ["Help"] = "ヘルプとサポート",
            ["SearchPlace"] = "検索",
            ["Run"] = "ファイル名を指定して実行...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "プログラム",
            ["Favorites"] = "お気に入り",
            ["Internet"] = "インターネット",
            ["Email"] = "電子メール",
            ["Empty"] = "(空)",

            ["LogOff"] = "ログオフ",
            ["LogOffClassic"] = "ログオフ…",
            ["ShutDownClassic"] = "終了オプション…",
            ["ShutDown"] = "コンピュータの電源を切る",
            ["PowerTitle"] = "コンピュータの電源を切る",
            ["Standby"] = "スタンバイ",
            ["Hibernate"] = "休止状態",
            ["TurnOff"] = "電源を切る",
            ["Restart"] = "再起動",
            ["Lock"] = "ロック",
            ["SwitchUser"] = "ユーザーの切り替え",
            ["LogOffTitle"] = "Windows のログオフ",
            ["Cancel"] = "キャンセル",
            ["PowerQuestion"] = "コンピュータをどうしますか?",

            ["Open"] = "開く",
            ["RunAsAdmin"] = "管理者として実行",
            ["Pin"] = "お気に入りに追加",
            ["Unpin"] = "お気に入りから削除",
            ["MoveToFolder"] = "フォルダへ移動",
            ["NewFolder"] = "新しいフォルダ…",
            ["FolderDefaultName"] = "フォルダ",
            ["OutOfFolder"] = "フォルダから出す",
            ["RenameFolder"] = "フォルダ名の変更…",
            ["DissolveFolder"] = "フォルダを解除",
            ["FolderNamePrompt"] = "フォルダの名前:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "この一覧から削除",
            ["OpenFileLocation"] = "ファイルの場所を開く",

            ["TrayOpen"] = "スタート メニューを開く",
            ["TraySettings"] = "設定…",
            ["TrayRefresh"] = "プログラム一覧を読み直す",
            ["TrayExit"] = "終了",

            ["SettingsTitle"] = "Retro Menu – 設定",
            ["Appearance"] = "表示",
            ["Theme"] = "テーマ",
            ["FollowRetroBar"] = "RetroBar のテーマに合わせる",
            ["Behaviour"] = "動作",
            ["WinKey"] = "Windows キー",
            ["WinKeyNeutralize"] = "横取りする (推奨)",
            ["WinKeySwallow"] = "完全に飲み込む",
            ["WinKeyOff"] = "手を触れない",
            ["FrequentCount"] = "よく使うプログラム: 個数",
            ["ShowRecent"] = "最近起動したプログラムを表示する",
            ["ShowTiles"] = "お気に入りを右側にタイルで並べる",
            ["ShowTilesHint"] = "3 つ目の領域が、お気に入りとそのフォルダを Windows 11 のピン留め一覧のようにタイルで並べます。",
            ["TilesHeader"] = "ピン留め済み",
            ["ShowRecentHint"] = "左の列には、よく使うものではなく最後に起動したものが並びます。",
            ["ShowSearchBox"] = "検索ボックスを表示する (XP にはありません)",
            ["SearchFilesSetting"] = "検索にファイルを含める",
            ["MenuScale"] = "メニューの大きさ",
            ["KeepTaskbar"] = "メニューを開いている間はタスク バーを表示する",
            ["ShowStoreApps"] = "ストア アプリも一覧に入れる",
            ["UseXpExplorer"] = "フォルダを XP 風のファイル ウィンドウで開く",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 があり、マイ ドキュメントやマイ コンピュータ"
                                    + "などの場所を昔の装いで表示します。",
            ["UseXpExplorerMissing"] = "見つかりません。windows-xp-explorer-win-11 がないと、"
                                       + "フォルダは Windows のエクスプローラが開きます。",
            ["UseXpExplorerBroken"] = "見つかりましたが、インストールが不完全なため、フォルダは Windows のエクスプローラが開きます。",
            ["AutoStart"] = "Windows と一緒に起動する",
            ["Language"] = "言語",
            ["Close"] = "閉じる",
            ["StoreApps"] = "ストア アプリ",

            ["LangAutoWindows"] = "自動 (Windows の言語)",
            ["LangAutoRetroBar"] = "自動 (RetroBar)",
            ["LangDetected"] = "Windows の言語は {0} です。",
            ["LangShowing"] = "メニューの言語は {0} です。",
            ["LangUntranslated"] = "{0} はまだ翻訳がないため、英語で表示します。",
            ["RetroBarFound"] = "RetroBar が見つかりました – テーマ「{0}」→「{1}」。",
            ["RetroBarMissing"] = "RetroBar は見つかりませんでした。",

            ["SetupTitle"] = "Retro Menu のセットアップ",
            ["SetupSubtitle"] = "古い Windows の装いのスタート メニューです。",
            ["SetupIntro"] = "プログラムはご自身のユーザー フォルダに置かれます。管理者権限は不要で、"
                             + "システムには何も変更を加えません。",
            ["SetupTarget"] = "インストール先フォルダ",
            ["SetupDuring"] = "セットアップ時に行うこと",
            ["SetupStartMenu"] = "スタート メニューにショートカットを作る",
            ["SetupDesktop"] = "デスクトップにショートカットを作る",
            ["SetupRetroBar"] = "RetroBar も一緒に入れる – XP 風のタスク バー",
            ["SetupRetroBarNote"] = "github.com/dremin/RetroBar から直接取得します。ダウンロードの"
                                    + "チェックサムは、あとでログに表示されます。",
            ["SetupRetroBarPresent"] = "RetroBar はすでに入っています",
            ["SetupInstall"] = "インストール",
            ["SetupUpdate"] = "更新",
            ["SetupUpdateSubtitle"] = "既存のインストールを更新します。",
            ["SetupRemoveTitle"] = "Retro Menu の削除",
            ["SetupRemoveSubtitle"] = "プログラムをユーザー フォルダから削除します。",
            ["SetupRemoveButton"] = "削除",
            ["SetupRemoveText"] = "Retro Menu を終了し、{0} から削除します。設定は残るので、"
                                  + "あとで入れ直したときにまた見つかります。",
            ["SetupWorking"] = "セットアップしています…",
            ["SetupRemoving"] = "削除しています…",
            ["SetupDone"] = "完了しました。",
            ["SetupRemoved"] = "削除しました。",
            ["SetupErrors"] = "エラーがあって終了しました。",
            ["SetupFailed"] = "失敗しました: {0}",
            ["SetupStart"] = "起動",
        };
    }
}
