using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>한국어.</summary>
    internal static class Ko
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "모든 프로그램",
            ["Search"] = "검색",
            ["SearchHint"] = "프로그램 검색",
            ["SearchFiles"] = "파일도 함께 검색",
            ["BestMatch"] = "가장 잘 맞는 항목",
            ["AppsGroup"] = "앱",
            ["SettingsGroup"] = "설정",
            ["FilesGroup"] = "파일",
            ["Searching"] = "파일에서 검색하는 중…",
            ["NoIndex"] = "Windows 검색을 사용할 수 없습니다",
            ["NoResults"] = "결과 없음",
            ["Loading"] = "불러오는 중…",

            ["ProgramFilter"] = "필터:",
            ["ProgramGroups"] = "그룹",
            ["ProgramCount"] = "프로그램 {0}개",

            ["AdvancedSearch"] = "고급 검색",
            ["SearchFor"] = "검색어:",
            ["Categories"] = "찾을 대상",
            ["FileType"] = "종류",
            ["AnyType"] = "모든 파일",
            ["TypeDocuments"] = "문서",
            ["TypePictures"] = "그림",
            ["TypeMusic"] = "음악",
            ["TypeVideos"] = "비디오",
            ["TypeFolders"] = "폴더",
            ["Location"] = "찾을 위치",
            ["AnyLocation"] = "모든 위치",
            ["Modified"] = "수정한 날짜",
            ["AnyTime"] = "제한 없음",
            ["Today"] = "오늘",
            ["ThisWeek"] = "이번 주",
            ["ThisMonth"] = "이번 달",
            ["ThisYear"] = "올해",
            ["Back"] = "뒤로",
            ["Hits"] = "{0}개",

            ["Documents"] = "내 문서",
            ["RecentDocuments"] = "내 최근 문서",
            ["Pictures"] = "내 그림",
            ["Music"] = "내 음악",
            ["Computer"] = "내 컴퓨터",
            ["ControlPanel"] = "제어판",
            ["SetProgramAccess"] = "프로그램 액세스 및 기본값 설정",
            ["Connections"] = "연결",
            ["RemoteDesktop"] = "원격 데스크톱",
            ["SshConnection"] = "SSH 연결…",
            ["SshPrompt"] = "사용자@호스트:",
            ["SshTitle"] = "SSH 연결",
            ["SshSubtitle"] = "Windows에 들어 있는 OpenSSH로 연결합니다.",
            ["SshKey"] = "키 파일:",
            ["SshKeyHint"] = ".ssh 폴더에 있는 키입니다. 키가 없으면 ssh가 암호를 묻습니다.",
            ["SshNoKey"] = "(없음 – 암호)",
            ["SshBrowse"] = "키 파일 선택…",
            ["SshConnectButton"] = "연결",
            ["SftpConnection"] = "SFTP 연결…",
            ["TelnetConnection"] = "Telnet 연결…",
            ["FtpConnection"] = "FTP 연결…",
            ["NetworkFolder"] = "네트워크 폴더 열기…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "포트:",
            ["HostPrompt"] = "컴퓨터:",
            ["FolderPrompt"] = "\\\\서버\\공유:",
            ["ConnectSubtitle"] = "클라이언트는 Windows에 들어 있습니다.",
            ["MapDrive"] = "네트워크 드라이브 연결…",
            ["AllConnections"] = "모든 연결 표시",
            ["PrintersAndFaxes"] = "프린터 및 팩스",
            ["Help"] = "도움말 및 지원",
            ["SearchPlace"] = "검색",
            ["Run"] = "실행...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "프로그램",
            ["Favorites"] = "즐겨찾기",
            ["Internet"] = "인터넷",
            ["Email"] = "전자 메일",
            ["Empty"] = "(비어 있음)",

            ["LogOff"] = "로그오프",
            ["LogOffClassic"] = "로그오프…",
            ["ShutDownClassic"] = "시스템 종료…",
            ["ShutDown"] = "컴퓨터 끄기",
            ["PowerTitle"] = "컴퓨터 끄기",
            ["Standby"] = "대기 모드",
            ["Hibernate"] = "최대 절전 모드",
            ["TurnOff"] = "끄기",
            ["Restart"] = "다시 시작",
            ["Lock"] = "잠금",
            ["SwitchUser"] = "사용자 전환",
            ["LogOffTitle"] = "Windows 로그오프",
            ["Cancel"] = "취소",
            ["PowerQuestion"] = "컴퓨터를 어떻게 할까요?",

            ["Open"] = "열기",
            ["RunAsAdmin"] = "관리자 권한으로 실행",
            ["Pin"] = "즐겨찾기에 추가",
            ["Unpin"] = "즐겨찾기에서 제거",
            ["MoveToFolder"] = "폴더로 이동",
            ["NewFolder"] = "새 폴더…",
            ["FolderDefaultName"] = "폴더",
            ["OutOfFolder"] = "폴더에서 꺼내기",
            ["RenameFolder"] = "폴더 이름 바꾸기…",
            ["DissolveFolder"] = "폴더 해제",
            ["FolderNamePrompt"] = "폴더 이름:",
            ["Ok"] = "확인",
            ["RemoveFromList"] = "이 목록에서 제거",
            ["OpenFileLocation"] = "파일 위치 열기",

            ["TrayOpen"] = "시작 메뉴 열기",
            ["TraySettings"] = "설정…",
            ["TrayRefresh"] = "프로그램 목록 다시 읽기",
            ["TrayExit"] = "끝내기",

            ["SettingsTitle"] = "Retro Menu – 설정",
            ["Appearance"] = "모양",
            ["Theme"] = "테마",
            ["FollowRetroBar"] = "RetroBar의 테마 따르기",
            ["Behaviour"] = "동작",
            ["WinKey"] = "Windows 키",
            ["WinKeyNeutralize"] = "가로채기 (권장)",
            ["WinKeySwallow"] = "완전히 삼키기",
            ["WinKeyOff"] = "건드리지 않기",
            ["FrequentCount"] = "자주 사용하는 프로그램: 개수",
            ["ShowRecent"] = "최근에 실행한 프로그램 표시",
            ["ShowTiles"] = "즐겨찾기를 오른쪽에 타일로 표시",
            ["ShowTilesHint"] = "세 번째 영역이 즐겨찾기와 그 폴더를 타일로 보여 줍니다. Windows 11의 고정된 앱 배열과 같은 방식입니다.",
            ["TilesHeader"] = "고정됨",
            ["ShowRecentHint"] = "그러면 왼쪽 열에는 가장 자주 실행한 것이 아니라 마지막에 실행한 것이 놓입니다.",
            ["ShowSearchBox"] = "검색 상자 표시 (XP에는 없었습니다)",
            ["SearchFilesSetting"] = "검색에 파일 포함",
            ["MenuScale"] = "메뉴 크기",
            ["KeepTaskbar"] = "메뉴가 열려 있는 동안 작업 표시줄 보이기",
            ["ShowStoreApps"] = "스토어 앱도 목록에 넣기",
            ["UseXpExplorer"] = "폴더를 XP 파일 창에서 열기",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11이 설치되어 있어 내 문서, 내 컴퓨터 등의 "
                                    + "위치를 옛 모습으로 보여 줍니다.",
            ["UseXpExplorerMissing"] = "찾을 수 없습니다. windows-xp-explorer-win-11이 없으면 폴더는 "
                                       + "Windows 탐색기가 엽니다.",
            ["UseXpExplorerBroken"] = "찾았지만 설치가 불완전해서 폴더는 Windows 탐색기가 엽니다.",
            ["AutoStart"] = "Windows와 함께 시작",
            ["Language"] = "언어",
            ["Close"] = "닫기",
            ["StoreApps"] = "스토어 앱",

            ["LangAutoWindows"] = "자동 (Windows 언어)",
            ["LangAutoRetroBar"] = "자동 (RetroBar)",
            ["LangDetected"] = "Windows 언어는 {0}입니다.",
            ["LangShowing"] = "메뉴 언어는 {0}입니다.",
            ["LangUntranslated"] = "{0}은(는) 아직 번역이 없어 영어로 표시합니다.",
            ["RetroBarFound"] = "RetroBar를 찾았습니다 – 테마 \"{0}\" → \"{1}\".",
            ["RetroBarMissing"] = "RetroBar를 찾지 못했습니다.",

            ["SetupTitle"] = "Retro Menu 설치",
            ["SetupSubtitle"] = "옛 Windows 방식의 시작 메뉴입니다.",
            ["SetupIntro"] = "프로그램은 사용자 폴더에 놓입니다. 관리자 권한이 필요 없으며 시스템은 "
                             + "아무것도 바뀌지 않습니다.",
            ["SetupTarget"] = "대상 폴더",
            ["SetupDuring"] = "설치할 때",
            ["SetupStartMenu"] = "시작 메뉴에 바로 가기 만들기",
            ["SetupDesktop"] = "바탕 화면에 바로 가기 만들기",
            ["SetupRetroBar"] = "RetroBar도 함께 설치 – XP 방식의 작업 표시줄",
            ["SetupRetroBarNote"] = "github.com/dremin/RetroBar에서 바로 내려받습니다. 내려받은 파일의 "
                                    + "체크섬은 이후 로그에 표시됩니다.",
            ["SetupRetroBarPresent"] = "RetroBar가 이미 설치되어 있습니다",
            ["SetupInstall"] = "설치",
            ["SetupUpdate"] = "업데이트",
            ["SetupUpdateSubtitle"] = "기존 설치를 업데이트합니다.",
            ["SetupRemoveTitle"] = "Retro Menu 제거",
            ["SetupRemoveSubtitle"] = "프로그램을 사용자 폴더에서 제거합니다.",
            ["SetupRemoveButton"] = "제거",
            ["SetupRemoveText"] = "Retro Menu를 끝내고 {0}에서 제거합니다. 설정은 그대로 남아 나중에 "
                                  + "다시 설치하면 찾을 수 있습니다.",
            ["SetupWorking"] = "설치하는 중…",
            ["SetupRemoving"] = "제거하는 중…",
            ["SetupDone"] = "완료되었습니다.",
            ["SetupRemoved"] = "제거되었습니다.",
            ["SetupErrors"] = "오류와 함께 끝났습니다.",
            ["SetupFailed"] = "실패: {0}",
            ["SetupStart"] = "시작",
        };
    }
}
