using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Norsk bokmål.</summary>
    internal static class Nb
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Alle programmer",
            ["Search"] = "Søk",
            ["SearchHint"] = "Søk etter programmer",
            ["SearchFiles"] = "Søk også i filer",
            ["BestMatch"] = "Beste treff",
            ["AppsGroup"] = "Apper",
            ["SettingsGroup"] = "Innstillinger",
            ["FilesGroup"] = "Filer",
            ["Searching"] = "Søker i filene…",
            ["NoIndex"] = "Windows Search er ikke tilgjengelig",
            ["NoResults"] = "Ingen treff",
            ["Loading"] = "Laster inn…",

            ["ProgramFilter"] = "Filter:",
            ["ProgramGroups"] = "Grupper",
            ["ProgramCount"] = "{0} programmer",

            ["AdvancedSearch"] = "Avansert søk",
            ["SearchFor"] = "Søk etter:",
            ["Categories"] = "Det søkes etter",
            ["FileType"] = "Type",
            ["AnyType"] = "Alle filer",
            ["TypeDocuments"] = "Dokumenter",
            ["TypePictures"] = "Bilder",
            ["TypeMusic"] = "Musikk",
            ["TypeVideos"] = "Videoer",
            ["TypeFolders"] = "Mapper",
            ["Location"] = "Søk i",
            ["AnyLocation"] = "Overalt",
            ["Modified"] = "Endret",
            ["AnyTime"] = "Når som helst",
            ["Today"] = "I dag",
            ["ThisWeek"] = "Denne uken",
            ["ThisMonth"] = "Denne måneden",
            ["ThisYear"] = "I år",
            ["Back"] = "Tilbake",
            ["Hits"] = "{0} treff",

            ["Documents"] = "Mine dokumenter",
            ["RecentDocuments"] = "Nylig brukte dokumenter",
            ["Pictures"] = "Mine bilder",
            ["Music"] = "Min musikk",
            ["Computer"] = "Min datamaskin",
            ["ControlPanel"] = "Kontrollpanel",
            ["SetProgramAccess"] = "Angi programtilgang og standardvalg",
            ["Connections"] = "Tilkoblinger",
            ["RemoteDesktop"] = "Eksternt skrivebord",
            ["SshConnection"] = "SSH-tilkobling…",
            ["SshPrompt"] = "bruker@vert:",
            ["SshTitle"] = "SSH-tilkobling",
            ["SshSubtitle"] = "Tilkoblingen går via Windows' egen OpenSSH-klient.",
            ["SshKey"] = "Nøkkelfil:",
            ["SshKeyHint"] = "Nøkler fra .ssh-mappen din. Uten nøkkel spør ssh om passordet.",
            ["SshNoKey"] = "(ingen – passord)",
            ["SshBrowse"] = "Velg nøkkelfil…",
            ["SshConnectButton"] = "Koble til",
            ["SftpConnection"] = "SFTP-tilkobling…",
            ["TelnetConnection"] = "Telnet-tilkobling…",
            ["FtpConnection"] = "FTP-tilkobling…",
            ["NetworkFolder"] = "Åpne nettverksmappe…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Port:",
            ["HostPrompt"] = "Datamaskin:",
            ["FolderPrompt"] = "\\\\server\\deling:",
            ["ConnectSubtitle"] = "Windows har klienten med selv.",
            ["MapDrive"] = "Koble til nettverksstasjon…",
            ["AllConnections"] = "Vis alle tilkoblinger",
            ["PrintersAndFaxes"] = "Skrivere og telefakser",
            ["Help"] = "Hjelp og støtte",
            ["SearchPlace"] = "Søk",
            ["Run"] = "Kjør...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Programmer",
            ["Favorites"] = "Favoritter",
            ["Internet"] = "Internett",
            ["Email"] = "E-post",
            ["Empty"] = "(Tom)",

            ["LogOff"] = "Logg av",
            ["LogOffClassic"] = "Logg av…",
            ["ShutDownClassic"] = "Avslutt…",
            ["ShutDown"] = "Slå av datamaskinen",
            ["PowerTitle"] = "Slå av datamaskinen",
            ["Standby"] = "Ventemodus",
            ["Hibernate"] = "Dvalemodus",
            ["TurnOff"] = "Slå av",
            ["Restart"] = "Start på nytt",
            ["Lock"] = "Lås",
            ["SwitchUser"] = "Bytt bruker",
            ["LogOffTitle"] = "Logg av Windows",
            ["Cancel"] = "Avbryt",
            ["PowerQuestion"] = "Hva skal datamaskinen gjøre?",

            ["Open"] = "Åpne",
            ["RunAsAdmin"] = "Kjør som administrator",
            ["Pin"] = "Legg til i favoritter",
            ["Unpin"] = "Fjern fra favoritter",
            ["MoveToFolder"] = "Flytt til mappe",
            ["NewFolder"] = "Ny mappe…",
            ["FolderDefaultName"] = "Mappe",
            ["OutOfFolder"] = "Flytt ut av mappen",
            ["RenameFolder"] = "Gi mappen nytt navn…",
            ["DissolveFolder"] = "Løs opp mappen",
            ["FolderNamePrompt"] = "Navn på mappen:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Fjern fra denne listen",
            ["OpenFileLocation"] = "Åpne filplasseringen",

            ["TrayOpen"] = "Åpne Start-menyen",
            ["TraySettings"] = "Innstillinger…",
            ["TrayRefresh"] = "Les inn programlisten på nytt",
            ["TrayExit"] = "Avslutt",

            ["SettingsTitle"] = "Retro Menu – Innstillinger",
            ["Appearance"] = "Utseende",
            ["Theme"] = "Tema",
            ["FollowRetroBar"] = "Overta temaet fra RetroBar",
            ["Behaviour"] = "Oppførsel",
            ["WinKey"] = "Windows-tasten",
            ["WinKeyNeutralize"] = "Fang opp (anbefalt)",
            ["WinKeySwallow"] = "Svelg helt",
            ["WinKeyOff"] = "La den være",
            ["FrequentCount"] = "Ofte brukte: antall",
            ["ShowRecent"] = "Vis programmer som nylig er startet",
            ["ShowTiles"] = "Favoritter som fliser til høyre",
            ["ShowTilesHint"] = "Et tredje panel viser favorittene og mappene deres som fliser, slik rutenettet med festede apper i Windows 11 gjør.",
            ["TilesHeader"] = "Festet",
            ["ShowRecentHint"] = "Den venstre kolonnen viser da det som ble startet sist, i stedet for det som startes oftest.",
            ["ShowSearchBox"] = "Vis søkefeltet (XP hadde ikke noe)",
            ["SearchFilesSetting"] = "Søket omfatter filer",
            ["MenuScale"] = "Menyens størrelse",
            ["KeepTaskbar"] = "Vis oppgavelinjen mens menyen er åpen",
            ["ShowStoreApps"] = "Ta med Store-apper",
            ["UseXpExplorer"] = "Åpne mapper i XP-filvinduet",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 finnes og viser Mine dokumenter, "
                                    + "Min datamaskin og de andre stedene i gammel drakt.",
            ["UseXpExplorerMissing"] = "Ikke funnet. Uten windows-xp-explorer-win-11 er det "
                                       + "Windows Utforsker som åpner mappene.",
            ["UseXpExplorerBroken"] = "Funnet, men installasjonen er ufullstendig, så mappene åpnes av Windows Utforsker.",
            ["AutoStart"] = "Start sammen med Windows",
            ["Language"] = "Språk",
            ["Close"] = "Lukk",
            ["StoreApps"] = "Store-apper",

            ["LangAutoWindows"] = "Automatisk (Windows-språk)",
            ["LangAutoRetroBar"] = "Automatisk (RetroBar)",
            ["LangDetected"] = "Windows er satt til {0}.",
            ["LangShowing"] = "Menyen snakker {0}.",
            ["LangUntranslated"] = "{0} er ikke oversatt ennå, så engelsk trår til.",
            ["RetroBarFound"] = "RetroBar funnet – temaet «{0}» → «{1}».",
            ["RetroBarMissing"] = "RetroBar ble ikke funnet.",

            ["SetupTitle"] = "Installer Retro Menu",
            ["SetupSubtitle"] = "En Start-meny i stil med eldre Windows-versjoner.",
            ["SetupIntro"] = "Programmet legges i din egen brukermappe. Det trengs ingen "
                             + "administratorrettigheter, og ingenting i systemet endres.",
            ["SetupTarget"] = "Målmappe",
            ["SetupDuring"] = "Under installeringen",
            ["SetupStartMenu"] = "Lag en snarvei på Start-menyen",
            ["SetupDesktop"] = "Lag en snarvei på skrivebordet",
            ["SetupRetroBar"] = "Installer RetroBar også – oppgavelinjen i XP-stil",
            ["SetupRetroBarNote"] = "Lastes ned direkte fra github.com/dremin/RetroBar. Kontrollsummen "
                                    + "for nedlastingen står etterpå i loggen.",
            ["SetupRetroBarPresent"] = "RetroBar finnes allerede",
            ["SetupInstall"] = "Installer",
            ["SetupUpdate"] = "Oppdater",
            ["SetupUpdateSubtitle"] = "En eksisterende installasjon blir oppdatert.",
            ["SetupRemoveTitle"] = "Fjern Retro Menu",
            ["SetupRemoveSubtitle"] = "Programmet fjernes fra brukermappen din.",
            ["SetupRemoveButton"] = "Fjern",
            ["SetupRemoveText"] = "Retro Menu blir avsluttet og fjernet fra {0}. Innstillingene dine "
                                  + "beholdes, slik at en senere installasjon finner dem igjen.",
            ["SetupWorking"] = "Installerer…",
            ["SetupRemoving"] = "Fjerner…",
            ["SetupDone"] = "Ferdig.",
            ["SetupRemoved"] = "Fjernet.",
            ["SetupErrors"] = "Avsluttet med feil.",
            ["SetupFailed"] = "Mislyktes: {0}",
            ["SetupStart"] = "Start",
        };
    }
}
