using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Nederlands.</summary>
    internal static class Nl
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Alle programma's",
            ["Search"] = "Zoeken",
            ["SearchHint"] = "Programma's zoeken",
            ["SearchFiles"] = "Ook in bestanden zoeken",
            ["BestMatch"] = "Beste resultaat",
            ["AppsGroup"] = "Apps",
            ["SettingsGroup"] = "Instellingen",
            ["FilesGroup"] = "Bestanden",
            ["Searching"] = "Bezig met zoeken in bestanden…",
            ["NoIndex"] = "Windows Search is niet beschikbaar",
            ["NoResults"] = "Geen resultaten",
            ["Loading"] = "Bezig met laden…",

            ["ProgramFilter"] = "Filter:",
            ["ProgramGroups"] = "Groepen",
            ["ProgramCount"] = "{0} programma's",

            ["AdvancedSearch"] = "Geavanceerd zoeken",
            ["SearchFor"] = "Zoeken naar:",
            ["Categories"] = "Waarnaar gezocht wordt",
            ["FileType"] = "Type",
            ["AnyType"] = "Alle bestanden",
            ["TypeDocuments"] = "Documenten",
            ["TypePictures"] = "Afbeeldingen",
            ["TypeMusic"] = "Muziek",
            ["TypeVideos"] = "Video's",
            ["TypeFolders"] = "Mappen",
            ["Location"] = "Zoeken in",
            ["AnyLocation"] = "Overal",
            ["Modified"] = "Gewijzigd",
            ["AnyTime"] = "Wanneer dan ook",
            ["Today"] = "Vandaag",
            ["ThisWeek"] = "Deze week",
            ["ThisMonth"] = "Deze maand",
            ["ThisYear"] = "Dit jaar",
            ["Back"] = "Terug",
            ["Hits"] = "{0} resultaten",

            ["Documents"] = "Mijn documenten",
            ["RecentDocuments"] = "Onlangs geopende documenten",
            ["Pictures"] = "Mijn afbeeldingen",
            ["Music"] = "Mijn muziek",
            ["Computer"] = "Deze computer",
            ["ControlPanel"] = "Configuratiescherm",
            ["SetProgramAccess"] = "Programmatoegang en -standaardinstellingen",
            ["Connections"] = "Verbindingen",
            ["RemoteDesktop"] = "Extern bureaublad",
            ["SshConnection"] = "SSH-verbinding…",
            ["SshPrompt"] = "gebruiker@host:",
            ["SshTitle"] = "SSH-verbinding",
            ["SshSubtitle"] = "Er wordt verbonden met de OpenSSH-client van Windows.",
            ["SshKey"] = "Sleutelbestand:",
            ["SshKeyHint"] = "Sleutels uit je .ssh-map. Zonder sleutel vraagt ssh om het wachtwoord.",
            ["SshNoKey"] = "(geen – wachtwoord)",
            ["SshBrowse"] = "Sleutelbestand kiezen…",
            ["SshConnectButton"] = "Verbinden",
            ["SftpConnection"] = "SFTP-verbinding…",
            ["TelnetConnection"] = "Telnet-verbinding…",
            ["FtpConnection"] = "FTP-verbinding…",
            ["NetworkFolder"] = "Netwerkmap openen…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Poort:",
            ["HostPrompt"] = "Computer:",
            ["FolderPrompt"] = "\\\\server\\share:",
            ["ConnectSubtitle"] = "Windows levert de client zelf mee.",
            ["MapDrive"] = "Netwerkverbinding maken…",
            ["AllConnections"] = "Alle verbindingen weergeven",
            ["PrintersAndFaxes"] = "Printers en faxapparaten",
            ["Help"] = "Help en ondersteuning",
            ["SearchPlace"] = "Zoeken",
            ["Run"] = "Uitvoeren...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Programma's",
            ["Favorites"] = "Favorieten",
            ["Internet"] = "Internet",
            ["Email"] = "E-mail",
            ["Empty"] = "(Leeg)",

            ["LogOff"] = "Afmelden",
            ["LogOffClassic"] = "Afmelden…",
            ["ShutDownClassic"] = "Afsluiten…",
            ["ShutDown"] = "Computer uitschakelen",
            ["PowerTitle"] = "Computer uitschakelen",
            ["Standby"] = "Stand-by",
            ["Hibernate"] = "Slaapstand",
            ["TurnOff"] = "Uitschakelen",
            ["Restart"] = "Opnieuw opstarten",
            ["Lock"] = "Vergrendelen",
            ["SwitchUser"] = "Gebruiker wisselen",
            ["LogOffTitle"] = "Afmelden bij Windows",
            ["Cancel"] = "Annuleren",
            ["PowerQuestion"] = "Wat moet de computer doen?",

            ["Open"] = "Openen",
            ["RunAsAdmin"] = "Als administrator uitvoeren",
            ["Pin"] = "Aan favorieten toevoegen",
            ["Unpin"] = "Uit favorieten verwijderen",
            ["MoveToFolder"] = "Naar map verplaatsen",
            ["NewFolder"] = "Nieuwe map…",
            ["FolderDefaultName"] = "Map",
            ["OutOfFolder"] = "Uit de map halen",
            ["RenameFolder"] = "Map hernoemen…",
            ["DissolveFolder"] = "Map opheffen",
            ["FolderNamePrompt"] = "Naam van de map:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Uit deze lijst verwijderen",
            ["OpenFileLocation"] = "Bestandslocatie openen",

            ["TrayOpen"] = "Startmenu openen",
            ["TraySettings"] = "Instellingen…",
            ["TrayRefresh"] = "Programmalijst opnieuw inlezen",
            ["TrayExit"] = "Afsluiten",

            ["SettingsTitle"] = "Retro Menu – Instellingen",
            ["Appearance"] = "Weergave",
            ["Theme"] = "Thema",
            ["FollowRetroBar"] = "Thema van RetroBar overnemen",
            ["Behaviour"] = "Gedrag",
            ["WinKey"] = "Windows-toets",
            ["WinKeyNeutralize"] = "Onderscheppen (aanbevolen)",
            ["WinKeySwallow"] = "Volledig opslokken",
            ["WinKeyOff"] = "Niet aanraken",
            ["FrequentCount"] = "Vaak gebruikt: aantal",
            ["ShowRecent"] = "Onlangs gestarte programma's tonen",
            ["ShowTiles"] = "Favorieten als tegelpaneel rechts",
            ["ShowTilesHint"] = "Een derde paneel toont de favorieten en hun mappen als tegels, net als het raster met vastgemaakte apps van Windows 11.",
            ["TilesHeader"] = "Vastgemaakt",
            ["ShowRecentHint"] = "De linkerkolom toont dan wat het laatst is gestart in plaats van wat het vaakst wordt gestart.",
            ["ShowSearchBox"] = "Zoekvak tonen (XP had er geen)",
            ["SearchFilesSetting"] = "Zoeken omvat bestanden",
            ["MenuScale"] = "Menugrootte",
            ["KeepTaskbar"] = "Taakbalk tonen zolang het menu open is",
            ["ShowStoreApps"] = "Store-apps meenemen",
            ["UseXpExplorer"] = "Mappen in het XP-bestandsvenster openen",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 is aanwezig en toont Mijn documenten, "
                                    + "Deze computer en de andere locaties in het oude jasje.",
            ["UseXpExplorerMissing"] = "Niet gevonden. Zonder windows-xp-explorer-win-11 opent "
                                       + "Windows Verkenner de mappen.",
            ["UseXpExplorerBroken"] = "Gevonden, maar de installatie is onvolledig, dus Windows Verkenner opent de mappen.",
            ["AutoStart"] = "Met Windows starten",
            ["Language"] = "Taal",
            ["Close"] = "Sluiten",
            ["StoreApps"] = "Store-apps",

            ["LangAutoWindows"] = "Automatisch (taal van Windows)",
            ["LangAutoRetroBar"] = "Automatisch (RetroBar)",
            ["LangDetected"] = "Windows staat op {0}.",
            ["LangShowing"] = "Het menu spreekt {0}.",
            ["LangUntranslated"] = "{0} is nog niet vertaald, dus springt het Engels bij.",
            ["RetroBarFound"] = "RetroBar gevonden – thema '{0}' → '{1}'.",
            ["RetroBarMissing"] = "RetroBar is niet gevonden.",

            ["SetupTitle"] = "Retro Menu instellen",
            ["SetupSubtitle"] = "Een startmenu in de stijl van oudere Windows-versies.",
            ["SetupIntro"] = "Het programma komt in je eigen gebruikersmap te staan. Er zijn geen "
                             + "administratorrechten nodig en er verandert niets aan het systeem.",
            ["SetupTarget"] = "Doelmap",
            ["SetupDuring"] = "Tijdens het instellen",
            ["SetupStartMenu"] = "Snelkoppeling in het startmenu maken",
            ["SetupDesktop"] = "Snelkoppeling op het bureaublad maken",
            ["SetupRetroBar"] = "RetroBar er meteen bij installeren – de taakbalk in XP-stijl",
            ["SetupRetroBarNote"] = "Wordt rechtstreeks van github.com/dremin/RetroBar gehaald. De "
                                    + "controlesom van de download staat daarna in het logboek.",
            ["SetupRetroBarPresent"] = "RetroBar is al aanwezig",
            ["SetupInstall"] = "Installeren",
            ["SetupUpdate"] = "Bijwerken",
            ["SetupUpdateSubtitle"] = "Een bestaande installatie wordt bijgewerkt.",
            ["SetupRemoveTitle"] = "Retro Menu verwijderen",
            ["SetupRemoveSubtitle"] = "Het programma wordt uit je gebruikersmap verwijderd.",
            ["SetupRemoveButton"] = "Verwijderen",
            ["SetupRemoveText"] = "Retro Menu wordt afgesloten en uit {0} verwijderd. Je instellingen "
                                  + "blijven bewaard, zodat een latere installatie ze terugvindt.",
            ["SetupWorking"] = "Bezig met instellen…",
            ["SetupRemoving"] = "Bezig met verwijderen…",
            ["SetupDone"] = "Klaar.",
            ["SetupRemoved"] = "Verwijderd.",
            ["SetupErrors"] = "Beëindigd met fouten.",
            ["SetupFailed"] = "Mislukt: {0}",
            ["SetupStart"] = "Starten",
        };
    }
}
