using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Polski.</summary>
    internal static class Pl
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Wszystkie programy",
            ["Search"] = "Szukaj",
            ["SearchHint"] = "Przeszukaj programy",
            ["SearchFiles"] = "Szukaj także w plikach",
            ["BestMatch"] = "Najlepszy wynik",
            ["AppsGroup"] = "Aplikacje",
            ["SettingsGroup"] = "Ustawienia",
            ["FilesGroup"] = "Pliki",
            ["Searching"] = "Przeszukiwanie plików…",
            ["NoIndex"] = "Wyszukiwanie Windows jest niedostępne",
            ["NoResults"] = "Brak wyników",
            ["Loading"] = "Ładowanie…",

            ["ProgramFilter"] = "Filtr:",
            ["ProgramGroups"] = "Grupy",
            ["ProgramCount"] = "Programów: {0}",

            ["AdvancedSearch"] = "Wyszukiwanie zaawansowane",
            ["SearchFor"] = "Szukaj:",
            ["Categories"] = "Czego szukamy",
            ["FileType"] = "Typ",
            ["AnyType"] = "Wszystkie pliki",
            ["TypeDocuments"] = "Dokumenty",
            ["TypePictures"] = "Obrazy",
            ["TypeMusic"] = "Muzyka",
            ["TypeVideos"] = "Wideo",
            ["TypeFolders"] = "Foldery",
            ["Location"] = "Szukaj w",
            ["AnyLocation"] = "Wszędzie",
            ["Modified"] = "Zmieniono",
            ["AnyTime"] = "Kiedykolwiek",
            ["Today"] = "Dzisiaj",
            ["ThisWeek"] = "W tym tygodniu",
            ["ThisMonth"] = "W tym miesiącu",
            ["ThisYear"] = "W tym roku",
            ["Back"] = "Wstecz",
            ["Hits"] = "{0} wyników",

            ["Documents"] = "Moje dokumenty",
            ["RecentDocuments"] = "Ostatnio używane dokumenty",
            ["Pictures"] = "Moje obrazy",
            ["Music"] = "Moja muzyka",
            ["Computer"] = "Mój komputer",
            ["ControlPanel"] = "Panel sterowania",
            ["SetProgramAccess"] = "Ustaw dostęp do programów i ich ustawienia domyślne",
            ["Connections"] = "Połączenia",
            ["RemoteDesktop"] = "Pulpit zdalny",
            ["SshConnection"] = "Połączenie SSH…",
            ["SshPrompt"] = "użytkownik@host:",
            ["SshTitle"] = "Połączenie SSH",
            ["SshSubtitle"] = "Łączy klient OpenSSH wbudowany w Windows.",
            ["SshKey"] = "Plik klucza:",
            ["SshKeyHint"] = "Klucze z twojego folderu .ssh. Bez klucza ssh poprosi o hasło.",
            ["SshNoKey"] = "(brak – hasło)",
            ["SshBrowse"] = "Wybierz plik klucza…",
            ["SshConnectButton"] = "Połącz",
            ["SftpConnection"] = "Połączenie SFTP…",
            ["TelnetConnection"] = "Połączenie Telnet…",
            ["FtpConnection"] = "Połączenie FTP…",
            ["NetworkFolder"] = "Otwórz folder sieciowy…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Port:",
            ["HostPrompt"] = "Komputer:",
            ["FolderPrompt"] = "\\\\serwer\\udział:",
            ["ConnectSubtitle"] = "Klienta dostarcza sam system Windows.",
            ["MapDrive"] = "Mapuj dysk sieciowy…",
            ["AllConnections"] = "Pokaż wszystkie połączenia",
            ["PrintersAndFaxes"] = "Drukarki i faksy",
            ["Help"] = "Pomoc i obsługa techniczna",
            ["SearchPlace"] = "Wyszukaj",
            ["Run"] = "Uruchom...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Programy",
            ["Favorites"] = "Ulubione",
            ["Internet"] = "Internet",
            ["Email"] = "Poczta e-mail",
            ["Empty"] = "(Puste)",

            ["LogOff"] = "Wyloguj",
            ["LogOffClassic"] = "Wyloguj…",
            ["ShutDownClassic"] = "Wyłącz…",
            ["ShutDown"] = "Wyłącz komputer",
            ["PowerTitle"] = "Wyłącz komputer",
            ["Standby"] = "Stan wstrzymania",
            ["Hibernate"] = "Hibernacja",
            ["TurnOff"] = "Wyłącz",
            ["Restart"] = "Uruchom ponownie",
            ["Lock"] = "Zablokuj",
            ["SwitchUser"] = "Przełącz użytkownika",
            ["LogOffTitle"] = "Wylogowywanie z systemu Windows",
            ["Cancel"] = "Anuluj",
            ["PowerQuestion"] = "Co ma zrobić komputer?",

            ["Open"] = "Otwórz",
            ["RunAsAdmin"] = "Uruchom jako administrator",
            ["Pin"] = "Dodaj do ulubionych",
            ["Unpin"] = "Usuń z ulubionych",
            ["MoveToFolder"] = "Przenieś do folderu",
            ["NewFolder"] = "Nowy folder…",
            ["FolderDefaultName"] = "Folder",
            ["OutOfFolder"] = "Wyjmij z folderu",
            ["RenameFolder"] = "Zmień nazwę folderu…",
            ["DissolveFolder"] = "Rozwiąż folder",
            ["FolderNamePrompt"] = "Nazwa folderu:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Usuń z tej listy",
            ["OpenFileLocation"] = "Otwórz lokalizację pliku",

            ["TrayOpen"] = "Otwórz menu Start",
            ["TraySettings"] = "Ustawienia…",
            ["TrayRefresh"] = "Wczytaj listę programów ponownie",
            ["TrayExit"] = "Zakończ",

            ["SettingsTitle"] = "Retro Menu – Ustawienia",
            ["Appearance"] = "Wygląd",
            ["Theme"] = "Motyw",
            ["FollowRetroBar"] = "Przejmij motyw RetroBar",
            ["Behaviour"] = "Zachowanie",
            ["WinKey"] = "Klawisz Windows",
            ["WinKeyNeutralize"] = "Przechwytuj (zalecane)",
            ["WinKeySwallow"] = "Połykaj całkowicie",
            ["WinKeyOff"] = "Nie ruszaj",
            ["FrequentCount"] = "Często używane: liczba",
            ["ShowRecent"] = "Pokaż ostatnio uruchamiane programy",
            ["ShowTiles"] = "Ulubione jako kafelki po prawej",
            ["ShowTilesHint"] = "Trzeci panel pokazuje ulubione i ich foldery jako kafelki, tak jak siatka przypiętych aplikacji w Windows 11.",
            ["TilesHeader"] = "Przypięte",
            ["ShowRecentHint"] = "W lewej kolumnie znajdzie się wtedy to, co uruchomiono ostatnio, zamiast tego, co uruchamiane jest najczęściej.",
            ["ShowSearchBox"] = "Pokaż pole wyszukiwania (XP go nie miał)",
            ["SearchFilesSetting"] = "Wyszukiwanie obejmuje pliki",
            ["MenuScale"] = "Rozmiar menu",
            ["KeepTaskbar"] = "Pokaż pasek zadań na czas otwarcia",
            ["ShowStoreApps"] = "Wypisz też aplikacje ze Sklepu",
            ["UseXpExplorer"] = "Otwieraj foldery w oknie plików XP",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 jest zainstalowany i pokaże Moje dokumenty, "
                                    + "Mój komputer i pozostałe miejsca w dawnym wyglądzie.",
            ["UseXpExplorerMissing"] = "Nie znaleziono. Bez windows-xp-explorer-win-11 foldery "
                                       + "otwiera Eksplorator Windows.",
            ["UseXpExplorerBroken"] = "Znaleziono, ale instalacja jest niepełna, więc foldery otwiera Eksplorator Windows.",
            ["AutoStart"] = "Uruchamiaj z Windows",
            ["Language"] = "Język",
            ["Close"] = "Zamknij",
            ["StoreApps"] = "Aplikacje ze Sklepu",

            ["LangAutoWindows"] = "Automatycznie (język Windows)",
            ["LangAutoRetroBar"] = "Automatycznie (RetroBar)",
            ["LangDetected"] = "Windows jest ustawiony na {0}.",
            ["LangShowing"] = "Menu mówi po: {0}.",
            ["LangUntranslated"] = "{0} nie ma jeszcze tłumaczenia, więc wkracza angielski.",
            ["RetroBarFound"] = "Znaleziono RetroBar – motyw „{0}” → „{1}”.",
            ["RetroBarMissing"] = "Nie znaleziono RetroBar.",

            ["SetupTitle"] = "Instalacja Retro Menu",
            ["SetupSubtitle"] = "Menu Start w stylu starszych wersji Windows.",
            ["SetupIntro"] = "Program trafia do twojego własnego folderu użytkownika. Nie są "
                             + "potrzebne uprawnienia administratora i nic w systemie się nie zmienia.",
            ["SetupTarget"] = "Folder docelowy",
            ["SetupDuring"] = "Podczas instalacji",
            ["SetupStartMenu"] = "Utwórz skrót w menu Start",
            ["SetupDesktop"] = "Utwórz skrót na pulpicie",
            ["SetupRetroBar"] = "Zainstaluj też RetroBar – pasek zadań w stylu XP",
            ["SetupRetroBarNote"] = "Pobierany wprost z github.com/dremin/RetroBar. Suma kontrolna "
                                    + "pobranego pliku pojawi się potem w dzienniku.",
            ["SetupRetroBarPresent"] = "RetroBar jest już zainstalowany",
            ["SetupInstall"] = "Zainstaluj",
            ["SetupUpdate"] = "Zaktualizuj",
            ["SetupUpdateSubtitle"] = "Istniejąca instalacja zostanie zaktualizowana.",
            ["SetupRemoveTitle"] = "Usuwanie Retro Menu",
            ["SetupRemoveSubtitle"] = "Program zostanie usunięty z twojego folderu użytkownika.",
            ["SetupRemoveButton"] = "Usuń",
            ["SetupRemoveText"] = "Retro Menu zostanie zamknięte i usunięte z {0}. Twoje ustawienia "
                                  + "pozostaną, żeby późniejsza instalacja je odnalazła.",
            ["SetupWorking"] = "Instalowanie…",
            ["SetupRemoving"] = "Usuwanie…",
            ["SetupDone"] = "Gotowe.",
            ["SetupRemoved"] = "Usunięto.",
            ["SetupErrors"] = "Zakończono z błędami.",
            ["SetupFailed"] = "Niepowodzenie: {0}",
            ["SetupStart"] = "Uruchom",
        };
    }
}
