using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Português (Portugal).</summary>
    internal static class Pt
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Todos os programas",
            ["Search"] = "Procurar",
            ["SearchHint"] = "Procurar programas",
            ["SearchFiles"] = "Procurar também nos ficheiros",
            ["BestMatch"] = "Melhor correspondência",
            ["AppsGroup"] = "Aplicações",
            ["SettingsGroup"] = "Definições",
            ["FilesGroup"] = "Ficheiros",
            ["Searching"] = "A procurar nos ficheiros…",
            ["NoIndex"] = "A Procura do Windows não está disponível",
            ["NoResults"] = "Sem resultados",
            ["Loading"] = "A carregar…",

            ["ProgramFilter"] = "Filtro:",
            ["ProgramGroups"] = "Grupos",
            ["ProgramCount"] = "{0} programas",

            ["AdvancedSearch"] = "Procura avançada",
            ["SearchFor"] = "Procurar:",
            ["Categories"] = "O que se procura",
            ["FileType"] = "Tipo",
            ["AnyType"] = "Todos os ficheiros",
            ["TypeDocuments"] = "Documentos",
            ["TypePictures"] = "Imagens",
            ["TypeMusic"] = "Música",
            ["TypeVideos"] = "Vídeos",
            ["TypeFolders"] = "Pastas",
            ["Location"] = "Procurar em",
            ["AnyLocation"] = "Em todo o lado",
            ["Modified"] = "Alterado",
            ["AnyTime"] = "Em qualquer altura",
            ["Today"] = "Hoje",
            ["ThisWeek"] = "Esta semana",
            ["ThisMonth"] = "Este mês",
            ["ThisYear"] = "Este ano",
            ["Back"] = "Voltar",
            ["Hits"] = "{0} resultados",

            ["Documents"] = "Os meus documentos",
            ["RecentDocuments"] = "Documentos recentes",
            ["Pictures"] = "As minhas imagens",
            ["Music"] = "A minha música",
            ["Computer"] = "O meu computador",
            ["ControlPanel"] = "Painel de controlo",
            ["SetProgramAccess"] = "Definir acesso a programas e predefinições",
            ["Connections"] = "Ligações",
            ["RemoteDesktop"] = "Ambiente de trabalho remoto",
            ["SshConnection"] = "Ligação SSH…",
            ["SshPrompt"] = "utilizador@anfitrião:",
            ["SshTitle"] = "Ligação SSH",
            ["SshSubtitle"] = "A ligação é feita pelo cliente OpenSSH do Windows.",
            ["SshKey"] = "Ficheiro de chave:",
            ["SshKeyHint"] = "Chaves da sua pasta .ssh. Sem chave, o ssh pede a palavra-passe.",
            ["SshNoKey"] = "(nenhuma – palavra-passe)",
            ["SshBrowse"] = "Escolher ficheiro de chave…",
            ["SshConnectButton"] = "Ligar",
            ["SftpConnection"] = "Ligação SFTP…",
            ["TelnetConnection"] = "Ligação Telnet…",
            ["FtpConnection"] = "Ligação FTP…",
            ["NetworkFolder"] = "Abrir pasta de rede…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Porta:",
            ["HostPrompt"] = "Computador:",
            ["FolderPrompt"] = "\\\\servidor\\partilha:",
            ["ConnectSubtitle"] = "O cliente vem com o próprio Windows.",
            ["MapDrive"] = "Ligar unidade de rede…",
            ["AllConnections"] = "Mostrar todas as ligações",
            ["PrintersAndFaxes"] = "Impressoras e faxes",
            ["Help"] = "Ajuda e suporte",
            ["SearchPlace"] = "Procurar",
            ["Run"] = "Executar...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Programas",
            ["Favorites"] = "Favoritos",
            ["Internet"] = "Internet",
            ["Email"] = "Correio eletrónico",
            ["Empty"] = "(Vazio)",

            ["LogOff"] = "Terminar sessão",
            ["LogOffClassic"] = "Terminar sessão…",
            ["ShutDownClassic"] = "Encerrar…",
            ["ShutDown"] = "Encerrar o computador",
            ["PowerTitle"] = "Encerrar o computador",
            ["Standby"] = "Suspender",
            ["Hibernate"] = "Hibernar",
            ["TurnOff"] = "Desligar",
            ["Restart"] = "Reiniciar",
            ["Lock"] = "Bloquear",
            ["Cancel"] = "Cancelar",
            ["PowerQuestion"] = "O que deve fazer o computador?",

            ["Open"] = "Abrir",
            ["RunAsAdmin"] = "Executar como administrador",
            ["Pin"] = "Adicionar aos favoritos",
            ["Unpin"] = "Remover dos favoritos",
            ["MoveToFolder"] = "Mover para uma pasta",
            ["NewFolder"] = "Nova pasta…",
            ["FolderDefaultName"] = "Pasta",
            ["OutOfFolder"] = "Retirar da pasta",
            ["RenameFolder"] = "Mudar o nome da pasta…",
            ["DissolveFolder"] = "Desfazer a pasta",
            ["FolderNamePrompt"] = "Nome da pasta:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Remover desta lista",
            ["OpenFileLocation"] = "Abrir a localização do ficheiro",

            ["TrayOpen"] = "Abrir o menu Iniciar",
            ["TraySettings"] = "Definições…",
            ["TrayRefresh"] = "Reler a lista de programas",
            ["TrayExit"] = "Sair",

            ["SettingsTitle"] = "Retro Menu – Definições",
            ["Appearance"] = "Aspeto",
            ["Theme"] = "Tema",
            ["FollowRetroBar"] = "Adotar o tema do RetroBar",
            ["Behaviour"] = "Comportamento",
            ["WinKey"] = "Tecla Windows",
            ["WinKeyNeutralize"] = "Intercetar (recomendado)",
            ["WinKeySwallow"] = "Absorver por completo",
            ["WinKeyOff"] = "Não mexer",
            ["FrequentCount"] = "Usados com frequência: quantidade",
            ["ShowRecent"] = "Mostrar os programas abertos recentemente",
            ["ShowTiles"] = "Favoritos como mosaicos à direita",
            ["ShowTilesHint"] = "Um terceiro painel mostra os favoritos e as suas pastas como mosaicos, tal como a grelha de aplicações afixadas do Windows 11.",
            ["TilesHeader"] = "Afixado",
            ["ShowRecentHint"] = "A coluna da esquerda mostra então o que foi aberto por último em vez do que é aberto mais vezes.",
            ["ShowSearchBox"] = "Mostrar a caixa de procura (o XP não tinha)",
            ["SearchFilesSetting"] = "A procura inclui ficheiros",
            ["MenuScale"] = "Tamanho do menu",
            ["KeepTaskbar"] = "Mostrar a barra de tarefas enquanto está aberto",
            ["ShowStoreApps"] = "Listar as aplicações da Store",
            ["UseXpExplorer"] = "Abrir as pastas na janela de ficheiros do XP",
            ["UseXpExplorerHint"] = "O windows-xp-explorer-win-11 está instalado e mostrará Os meus documentos, "
                                    + "O meu computador e os restantes locais com o aspeto antigo.",
            ["UseXpExplorerMissing"] = "Não encontrado. Sem o windows-xp-explorer-win-11 é o "
                                       + "Explorador do Windows que abre as pastas.",
            ["UseXpExplorerBroken"] = "Encontrado, mas a instalação está incompleta, por isso é o Explorador do Windows que abre as pastas.",
            ["AutoStart"] = "Iniciar com o Windows",
            ["Language"] = "Idioma",
            ["Close"] = "Fechar",
            ["StoreApps"] = "Aplicações da Store",

            ["LangAutoWindows"] = "Automático (idioma do Windows)",
            ["LangAutoRetroBar"] = "Automático (RetroBar)",
            ["LangDetected"] = "O Windows está definido para {0}.",
            ["LangShowing"] = "O menu fala {0}.",
            ["LangUntranslated"] = "{0} ainda não está traduzido, por isso entra o inglês.",
            ["RetroBarFound"] = "RetroBar encontrado – tema «{0}» → «{1}».",
            ["RetroBarMissing"] = "O RetroBar não foi encontrado.",

            ["SetupTitle"] = "Instalar o Retro Menu",
            ["SetupSubtitle"] = "Um menu Iniciar ao estilo das versões antigas do Windows.",
            ["SetupIntro"] = "O programa é colocado na sua própria pasta de utilizador. Não são "
                             + "precisos direitos de administrador e nada é alterado no sistema.",
            ["SetupTarget"] = "Pasta de destino",
            ["SetupDuring"] = "Durante a instalação",
            ["SetupStartMenu"] = "Criar um atalho no menu Iniciar",
            ["SetupDesktop"] = "Criar um atalho no ambiente de trabalho",
            ["SetupRetroBar"] = "Instalar também o RetroBar – a barra de tarefas ao estilo XP",
            ["SetupRetroBarNote"] = "É transferido diretamente de github.com/dremin/RetroBar. A soma "
                                    + "de verificação da transferência aparece depois no registo.",
            ["SetupRetroBarPresent"] = "O RetroBar já está instalado",
            ["SetupInstall"] = "Instalar",
            ["SetupUpdate"] = "Atualizar",
            ["SetupUpdateSubtitle"] = "Uma instalação existente será atualizada.",
            ["SetupRemoveTitle"] = "Remover o Retro Menu",
            ["SetupRemoveSubtitle"] = "O programa será removido da sua pasta de utilizador.",
            ["SetupRemoveButton"] = "Remover",
            ["SetupRemoveText"] = "O Retro Menu será fechado e removido de {0}. As suas definições "
                                  + "mantêm-se, para que uma instalação posterior volte a encontrá-las.",
            ["SetupWorking"] = "A instalar…",
            ["SetupRemoving"] = "A remover…",
            ["SetupDone"] = "Concluído.",
            ["SetupRemoved"] = "Removido.",
            ["SetupErrors"] = "Terminado com erros.",
            ["SetupFailed"] = "Falhou: {0}",
            ["SetupStart"] = "Iniciar",
        };
    }
}
