using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Português (Brasil).</summary>
    internal static class PtBr
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Todos os programas",
            ["Search"] = "Pesquisar",
            ["SearchHint"] = "Pesquisar programas",
            ["SearchFiles"] = "Pesquisar também nos arquivos",
            ["BestMatch"] = "Melhor resultado",
            ["AppsGroup"] = "Aplicativos",
            ["SettingsGroup"] = "Configurações",
            ["FilesGroup"] = "Arquivos",
            ["Searching"] = "Pesquisando nos arquivos…",
            ["NoIndex"] = "A Pesquisa do Windows não está disponível",
            ["NoResults"] = "Nenhum resultado",
            ["Loading"] = "Carregando…",

            ["ProgramFilter"] = "Filtro:",
            ["ProgramGroups"] = "Grupos",
            ["ProgramCount"] = "{0} programas",

            ["AdvancedSearch"] = "Pesquisa avançada",
            ["SearchFor"] = "Pesquisar:",
            ["Categories"] = "O que procurar",
            ["FileType"] = "Tipo",
            ["AnyType"] = "Todos os arquivos",
            ["TypeDocuments"] = "Documentos",
            ["TypePictures"] = "Imagens",
            ["TypeMusic"] = "Músicas",
            ["TypeVideos"] = "Vídeos",
            ["TypeFolders"] = "Pastas",
            ["Location"] = "Pesquisar em",
            ["AnyLocation"] = "Em todo lugar",
            ["Modified"] = "Alterado",
            ["AnyTime"] = "A qualquer momento",
            ["Today"] = "Hoje",
            ["ThisWeek"] = "Esta semana",
            ["ThisMonth"] = "Este mês",
            ["ThisYear"] = "Este ano",
            ["Back"] = "Voltar",
            ["Hits"] = "{0} resultados",

            ["Documents"] = "Meus documentos",
            ["RecentDocuments"] = "Documentos recentes",
            ["Pictures"] = "Minhas imagens",
            ["Music"] = "Minhas músicas",
            ["Computer"] = "Meu computador",
            ["ControlPanel"] = "Painel de controle",
            ["SetProgramAccess"] = "Definir acesso a programas e padrões",
            ["Connections"] = "Conexões",
            ["RemoteDesktop"] = "Área de trabalho remota",
            ["SshConnection"] = "Conexão SSH…",
            ["SshPrompt"] = "usuário@host:",
            ["SshTitle"] = "Conexão SSH",
            ["SshSubtitle"] = "A conexão é feita pelo cliente OpenSSH do Windows.",
            ["SshKey"] = "Arquivo de chave:",
            ["SshKeyHint"] = "Chaves da sua pasta .ssh. Sem chave, o ssh pede a senha.",
            ["SshNoKey"] = "(nenhuma – senha)",
            ["SshBrowse"] = "Escolher arquivo de chave…",
            ["SshConnectButton"] = "Conectar",
            ["SftpConnection"] = "Conexão SFTP…",
            ["TelnetConnection"] = "Conexão Telnet…",
            ["FtpConnection"] = "Conexão FTP…",
            ["NetworkFolder"] = "Abrir pasta de rede…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Porta:",
            ["HostPrompt"] = "Computador:",
            ["FolderPrompt"] = "\\\\servidor\\compartilhamento:",
            ["ConnectSubtitle"] = "O cliente vem com o próprio Windows.",
            ["MapDrive"] = "Mapear unidade de rede…",
            ["AllConnections"] = "Mostrar todas as conexões",
            ["PrintersAndFaxes"] = "Impressoras e aparelhos de fax",
            ["Help"] = "Ajuda e suporte",
            ["SearchPlace"] = "Pesquisar",
            ["Run"] = "Executar...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Programas",
            ["Favorites"] = "Favoritos",
            ["Internet"] = "Internet",
            ["Email"] = "E-mail",
            ["Empty"] = "(Vazio)",

            ["LogOff"] = "Fazer logoff",
            ["LogOffClassic"] = "Fazer logoff…",
            ["ShutDownClassic"] = "Desligar…",
            ["ShutDown"] = "Desligar o computador",
            ["PowerTitle"] = "Desligar o computador",
            ["Standby"] = "Em espera",
            ["Hibernate"] = "Hibernar",
            ["TurnOff"] = "Desligar",
            ["Restart"] = "Reiniciar",
            ["Lock"] = "Bloquear",
            ["Cancel"] = "Cancelar",
            ["PowerQuestion"] = "O que o computador deve fazer?",

            ["Open"] = "Abrir",
            ["RunAsAdmin"] = "Executar como administrador",
            ["Pin"] = "Adicionar aos favoritos",
            ["Unpin"] = "Remover dos favoritos",
            ["MoveToFolder"] = "Mover para uma pasta",
            ["NewFolder"] = "Nova pasta…",
            ["FolderDefaultName"] = "Pasta",
            ["OutOfFolder"] = "Tirar da pasta",
            ["RenameFolder"] = "Renomear pasta…",
            ["DissolveFolder"] = "Desfazer a pasta",
            ["FolderNamePrompt"] = "Nome da pasta:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Remover desta lista",
            ["OpenFileLocation"] = "Abrir o local do arquivo",

            ["TrayOpen"] = "Abrir o menu Iniciar",
            ["TraySettings"] = "Configurações…",
            ["TrayRefresh"] = "Reler a lista de programas",
            ["TrayExit"] = "Sair",

            ["SettingsTitle"] = "Retro Menu – Configurações",
            ["Appearance"] = "Aparência",
            ["Theme"] = "Tema",
            ["FollowRetroBar"] = "Adotar o tema do RetroBar",
            ["Behaviour"] = "Comportamento",
            ["WinKey"] = "Tecla Windows",
            ["WinKeyNeutralize"] = "Interceptar (recomendado)",
            ["WinKeySwallow"] = "Absorver por completo",
            ["WinKeyOff"] = "Não mexer",
            ["FrequentCount"] = "Usados com frequência: quantidade",
            ["ShowRecent"] = "Mostrar os programas abertos recentemente",
            ["ShowTiles"] = "Favoritos como blocos à direita",
            ["ShowTilesHint"] = "Um terceiro painel mostra os favoritos e suas pastas como blocos, do jeito que o Windows 11 organiza os aplicativos fixados.",
            ["TilesHeader"] = "Fixado",
            ["ShowRecentHint"] = "A coluna da esquerda passa a mostrar o que foi aberto por último, em vez do que é aberto com mais frequência.",
            ["ShowSearchBox"] = "Mostrar a caixa de pesquisa (o XP não tinha)",
            ["SearchFilesSetting"] = "A pesquisa inclui arquivos",
            ["MenuScale"] = "Tamanho do menu",
            ["KeepTaskbar"] = "Mostrar a barra de tarefas enquanto estiver aberto",
            ["ShowStoreApps"] = "Listar os aplicativos da Store",
            ["UseXpExplorer"] = "Abrir as pastas na janela de arquivos do XP",
            ["UseXpExplorerHint"] = "O windows-xp-explorer-win-11 está instalado e vai mostrar Meus documentos, "
                                    + "Meu computador e os demais locais com a cara antiga.",
            ["UseXpExplorerMissing"] = "Não encontrado. Sem o windows-xp-explorer-win-11 quem abre "
                                       + "as pastas é o Windows Explorer.",
            ["UseXpExplorerBroken"] = "Encontrado, mas a instalação está incompleta, então quem abre as pastas é o Windows Explorer.",
            ["AutoStart"] = "Iniciar com o Windows",
            ["Language"] = "Idioma",
            ["Close"] = "Fechar",
            ["StoreApps"] = "Aplicativos da Store",

            ["LangAutoWindows"] = "Automático (idioma do Windows)",
            ["LangAutoRetroBar"] = "Automático (RetroBar)",
            ["LangDetected"] = "O Windows está definido como {0}.",
            ["LangShowing"] = "O menu fala {0}.",
            ["LangUntranslated"] = "{0} ainda não tem tradução, então o inglês entra no lugar.",
            ["RetroBarFound"] = "RetroBar encontrado – tema \"{0}\" → \"{1}\".",
            ["RetroBarMissing"] = "O RetroBar não foi encontrado.",

            ["SetupTitle"] = "Instalar o Retro Menu",
            ["SetupSubtitle"] = "Um menu Iniciar no estilo das versões antigas do Windows.",
            ["SetupIntro"] = "O programa é colocado na sua própria pasta de usuário. Não são "
                             + "necessários direitos de administrador e nada é alterado no sistema.",
            ["SetupTarget"] = "Pasta de destino",
            ["SetupDuring"] = "Durante a instalação",
            ["SetupStartMenu"] = "Criar um atalho no menu Iniciar",
            ["SetupDesktop"] = "Criar um atalho na área de trabalho",
            ["SetupRetroBar"] = "Instalar também o RetroBar – a barra de tarefas no estilo XP",
            ["SetupRetroBarNote"] = "Baixado direto de github.com/dremin/RetroBar. A soma de "
                                    + "verificação do download aparece depois no registro.",
            ["SetupRetroBarPresent"] = "O RetroBar já está instalado",
            ["SetupInstall"] = "Instalar",
            ["SetupUpdate"] = "Atualizar",
            ["SetupUpdateSubtitle"] = "Uma instalação existente será atualizada.",
            ["SetupRemoveTitle"] = "Remover o Retro Menu",
            ["SetupRemoveSubtitle"] = "O programa será removido da sua pasta de usuário.",
            ["SetupRemoveButton"] = "Remover",
            ["SetupRemoveText"] = "O Retro Menu será fechado e removido de {0}. Suas configurações "
                                  + "continuam guardadas, para que uma instalação posterior as encontre.",
            ["SetupWorking"] = "Instalando…",
            ["SetupRemoving"] = "Removendo…",
            ["SetupDone"] = "Pronto.",
            ["SetupRemoved"] = "Removido.",
            ["SetupErrors"] = "Concluído com erros.",
            ["SetupFailed"] = "Falhou: {0}",
            ["SetupStart"] = "Iniciar",
        };
    }
}
