using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Română.</summary>
    internal static class Ro
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Toate programele",
            ["Search"] = "Căutare",
            ["SearchHint"] = "Caută printre programe",
            ["SearchFiles"] = "Caută și în fișiere",
            ["BestMatch"] = "Cea mai bună potrivire",
            ["AppsGroup"] = "Aplicații",
            ["SettingsGroup"] = "Setări",
            ["FilesGroup"] = "Fișiere",
            ["Searching"] = "Se caută în fișiere…",
            ["NoIndex"] = "Căutarea Windows nu este disponibilă",
            ["NoResults"] = "Niciun rezultat",
            ["Loading"] = "Se încarcă…",

            ["ProgramFilter"] = "Filtru:",
            ["ProgramGroups"] = "Grupuri",
            ["ProgramCount"] = "{0} programe",

            ["AdvancedSearch"] = "Căutare avansată",
            ["SearchFor"] = "Căutare după:",
            ["Categories"] = "Ce se caută",
            ["FileType"] = "Tip",
            ["AnyType"] = "Toate fișierele",
            ["TypeDocuments"] = "Documente",
            ["TypePictures"] = "Imagini",
            ["TypeMusic"] = "Muzică",
            ["TypeVideos"] = "Videoclipuri",
            ["TypeFolders"] = "Foldere",
            ["Location"] = "Căutare în",
            ["AnyLocation"] = "Peste tot",
            ["Modified"] = "Modificat",
            ["AnyTime"] = "Oricând",
            ["Today"] = "Astăzi",
            ["ThisWeek"] = "Săptămâna aceasta",
            ["ThisMonth"] = "Luna aceasta",
            ["ThisYear"] = "Anul acesta",
            ["Back"] = "Înapoi",
            ["Hits"] = "{0} rezultate",

            ["Documents"] = "Documentele mele",
            ["RecentDocuments"] = "Documente recente",
            ["Pictures"] = "Imaginile mele",
            ["Music"] = "Muzica mea",
            ["Computer"] = "Computerul meu",
            ["ControlPanel"] = "Panou de control",
            ["SetProgramAccess"] = "Stabilire acces la programe și valori implicite",
            ["Connections"] = "Conexiuni",
            ["RemoteDesktop"] = "Desktop la distanță",
            ["SshConnection"] = "Conexiune SSH…",
            ["SshPrompt"] = "utilizator@gazdă:",
            ["SshTitle"] = "Conexiune SSH",
            ["SshSubtitle"] = "Conectarea se face cu clientul OpenSSH din Windows.",
            ["SshKey"] = "Fișier de cheie:",
            ["SshKeyHint"] = "Chei din folderul .ssh. Fără cheie, ssh cere parola.",
            ["SshNoKey"] = "(niciuna – parolă)",
            ["SshBrowse"] = "Alegeți un fișier de cheie…",
            ["SshConnectButton"] = "Conectare",
            ["SftpConnection"] = "Conexiune SFTP…",
            ["TelnetConnection"] = "Conexiune Telnet…",
            ["FtpConnection"] = "Conexiune FTP…",
            ["NetworkFolder"] = "Deschide un dosar din rețea…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Port:",
            ["HostPrompt"] = "Computer:",
            ["FolderPrompt"] = "\\\\server\\partajare:",
            ["ConnectSubtitle"] = "Clientul vine chiar cu Windows.",
            ["MapDrive"] = "Conectare unitate de rețea…",
            ["AllConnections"] = "Afișare toate conexiunile",
            ["PrintersAndFaxes"] = "Imprimante și faxuri",
            ["Help"] = "Ajutor și asistență",
            ["SearchPlace"] = "Căutare",
            ["Run"] = "Executare...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Programe",
            ["Favorites"] = "Preferințe",
            ["Internet"] = "Internet",
            ["Email"] = "Poștă electronică",
            ["Empty"] = "(Gol)",

            ["LogOff"] = "Deconectare",
            ["LogOffClassic"] = "Deconectare…",
            ["ShutDownClassic"] = "Închidere…",
            ["ShutDown"] = "Închidere computer",
            ["PowerTitle"] = "Închidere computer",
            ["Standby"] = "Repaus",
            ["Hibernate"] = "Hibernare",
            ["TurnOff"] = "Închidere",
            ["Restart"] = "Repornire",
            ["Lock"] = "Blocare",
            ["SwitchUser"] = "Comutare utilizator",
            ["LogOffTitle"] = "Deconectare de la Windows",
            ["Cancel"] = "Revocare",
            ["PowerQuestion"] = "Ce trebuie să facă computerul?",

            ["Open"] = "Deschidere",
            ["RunAsAdmin"] = "Executare ca administrator",
            ["Pin"] = "Adaugă la preferințe",
            ["Unpin"] = "Elimină din preferințe",
            ["MoveToFolder"] = "Mută într-un folder",
            ["NewFolder"] = "Folder nou…",
            ["FolderDefaultName"] = "Folder",
            ["OutOfFolder"] = "Scoate din folder",
            ["RenameFolder"] = "Redenumire folder…",
            ["DissolveFolder"] = "Desfacere folder",
            ["FolderNamePrompt"] = "Numele folderului:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Elimină din această listă",
            ["OpenFileLocation"] = "Deschide locația fișierului",

            ["TrayOpen"] = "Deschide meniul Start",
            ["TraySettings"] = "Setări…",
            ["TrayRefresh"] = "Recitește lista de programe",
            ["TrayExit"] = "Ieșire",

            ["SettingsTitle"] = "Retro Menu – Setări",
            ["Appearance"] = "Aspect",
            ["Theme"] = "Temă",
            ["FollowRetroBar"] = "Preia tema din RetroBar",
            ["Behaviour"] = "Comportament",
            ["WinKey"] = "Tasta Windows",
            ["WinKeyNeutralize"] = "Interceptare (recomandat)",
            ["WinKeySwallow"] = "Înghițire completă",
            ["WinKeyOff"] = "Nu o atinge",
            ["FrequentCount"] = "Folosite des: număr",
            ["ShowRecent"] = "Arată programele pornite recent",
            ["ShowTiles"] = "Preferințele ca dale în dreapta",
            ["ShowTilesHint"] = "Un al treilea panou arată preferințele și folderele lor ca dale, la fel ca grila de aplicații fixate din Windows 11.",
            ["TilesHeader"] = "Fixate",
            ["ShowRecentHint"] = "În coloana din stânga apare atunci ce a fost pornit ultima dată, nu ce se pornește cel mai des.",
            ["ShowSearchBox"] = "Arată caseta de căutare (XP nu avea)",
            ["SearchFilesSetting"] = "Căutarea cuprinde și fișierele",
            ["MenuScale"] = "Mărimea meniului",
            ["KeepTaskbar"] = "Arată bara de activități cât timp meniul e deschis",
            ["ShowStoreApps"] = "Enumeră și aplicațiile din Store",
            ["UseXpExplorer"] = "Deschide folderele în fereastra de fișiere XP",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 există și va arăta Documentele mele, "
                                    + "Computerul meu și celelalte locuri în hainele vechi.",
            ["UseXpExplorerMissing"] = "Nu a fost găsit. Fără windows-xp-explorer-win-11 folderele "
                                       + "sunt deschise de Explorer.",
            ["UseXpExplorerBroken"] = "Găsit, dar instalarea este incompletă, așa că folderele sunt deschise de Explorer.",
            ["AutoStart"] = "Pornește odată cu Windows",
            ["Language"] = "Limbă",
            ["Close"] = "Închidere",
            ["StoreApps"] = "Aplicații din Store",

            ["LangAutoWindows"] = "Automat (limba Windows)",
            ["LangAutoRetroBar"] = "Automat (RetroBar)",
            ["LangDetected"] = "Windows este setat pe {0}.",
            ["LangShowing"] = "Meniul vorbește {0}.",
            ["LangUntranslated"] = "{0} nu este încă tradus, așa că intervine engleza.",
            ["RetroBarFound"] = "RetroBar găsit – tema „{0}” → „{1}”.",
            ["RetroBarMissing"] = "RetroBar nu a fost găsit.",

            ["SetupTitle"] = "Instalarea Retro Menu",
            ["SetupSubtitle"] = "Un meniu Start în stilul versiunilor mai vechi de Windows.",
            ["SetupIntro"] = "Programul este pus în propriul dumneavoastră folder de utilizator. Nu "
                             + "sunt necesare drepturi de administrator și nu se schimbă nimic în sistem.",
            ["SetupTarget"] = "Folder de destinație",
            ["SetupDuring"] = "La instalare",
            ["SetupStartMenu"] = "Creează o comandă rapidă în meniul Start",
            ["SetupDesktop"] = "Creează o comandă rapidă pe desktop",
            ["SetupRetroBar"] = "Instalează și RetroBar – bara de activități în stil XP",
            ["SetupRetroBarNote"] = "Se descarcă direct de la github.com/dremin/RetroBar. Suma de "
                                    + "control a descărcării apare apoi în jurnal.",
            ["SetupRetroBarPresent"] = "RetroBar există deja",
            ["SetupInstall"] = "Instalare",
            ["SetupUpdate"] = "Actualizare",
            ["SetupUpdateSubtitle"] = "O instalare existentă va fi actualizată.",
            ["SetupRemoveTitle"] = "Eliminarea Retro Menu",
            ["SetupRemoveSubtitle"] = "Programul va fi eliminat din folderul dumneavoastră de utilizator.",
            ["SetupRemoveButton"] = "Eliminare",
            ["SetupRemoveText"] = "Retro Menu va fi închis și eliminat din {0}. Setările "
                                  + "dumneavoastră rămân, ca o instalare ulterioară să le găsească din nou.",
            ["SetupWorking"] = "Se instalează…",
            ["SetupRemoving"] = "Se elimină…",
            ["SetupDone"] = "Gata.",
            ["SetupRemoved"] = "Eliminat.",
            ["SetupErrors"] = "Terminat cu erori.",
            ["SetupFailed"] = "Nereușit: {0}",
            ["SetupStart"] = "Pornire",
        };
    }
}
