using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Русский.</summary>
    internal static class Ru
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Все программы",
            ["Search"] = "Найти",
            ["SearchHint"] = "Поиск программ",
            ["SearchFiles"] = "Искать также в файлах",
            ["BestMatch"] = "Лучшее совпадение",
            ["AppsGroup"] = "Приложения",
            ["SettingsGroup"] = "Параметры",
            ["FilesGroup"] = "Файлы",
            ["Searching"] = "Поиск в файлах…",
            ["NoIndex"] = "Поиск Windows недоступен",
            ["NoResults"] = "Ничего не найдено",
            ["Loading"] = "Загрузка…",

            ["ProgramFilter"] = "Фильтр:",
            ["ProgramGroups"] = "Группы",
            ["ProgramCount"] = "Программ: {0}",

            ["AdvancedSearch"] = "Расширенный поиск",
            ["SearchFor"] = "Искать:",
            ["Categories"] = "Что ищем",
            ["FileType"] = "Тип",
            ["AnyType"] = "Все файлы",
            ["TypeDocuments"] = "Документы",
            ["TypePictures"] = "Изображения",
            ["TypeMusic"] = "Музыка",
            ["TypeVideos"] = "Видео",
            ["TypeFolders"] = "Папки",
            ["Location"] = "Искать в",
            ["AnyLocation"] = "Везде",
            ["Modified"] = "Изменён",
            ["AnyTime"] = "Когда угодно",
            ["Today"] = "Сегодня",
            ["ThisWeek"] = "На этой неделе",
            ["ThisMonth"] = "В этом месяце",
            ["ThisYear"] = "В этом году",
            ["Back"] = "Назад",
            ["Hits"] = "Найдено: {0}",

            ["Documents"] = "Мои документы",
            ["RecentDocuments"] = "Недавние документы",
            ["Pictures"] = "Мои рисунки",
            ["Music"] = "Моя музыка",
            ["Computer"] = "Мой компьютер",
            ["ControlPanel"] = "Панель управления",
            ["SetProgramAccess"] = "Выбор программ по умолчанию",
            ["Connections"] = "Подключения",
            ["RemoteDesktop"] = "Удалённый рабочий стол",
            ["SshConnection"] = "Подключение по SSH…",
            ["SshPrompt"] = "пользователь@узел:",
            ["SshTitle"] = "Подключение по SSH",
            ["SshSubtitle"] = "Подключается клиент OpenSSH, встроенный в Windows.",
            ["SshKey"] = "Файл ключа:",
            ["SshKeyHint"] = "Ключи из папки .ssh. Без ключа ssh спросит пароль.",
            ["SshNoKey"] = "(нет — пароль)",
            ["SshBrowse"] = "Выбрать файл ключа…",
            ["SshConnectButton"] = "Подключиться",
            ["SftpConnection"] = "SFTP-соединение…",
            ["TelnetConnection"] = "Telnet-соединение…",
            ["FtpConnection"] = "FTP-соединение…",
            ["NetworkFolder"] = "Открыть сетевую папку…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Порт:",
            ["HostPrompt"] = "Компьютер:",
            ["FolderPrompt"] = "\\\\сервер\\ресурс:",
            ["ConnectSubtitle"] = "Клиент входит в состав Windows.",
            ["MapDrive"] = "Подключить сетевой диск…",
            ["AllConnections"] = "Отобразить все подключения",
            ["PrintersAndFaxes"] = "Принтеры и факсы",
            ["Help"] = "Справка и поддержка",
            ["SearchPlace"] = "Поиск",
            ["Run"] = "Выполнить...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Программы",
            ["Favorites"] = "Избранное",
            ["Internet"] = "Интернет",
            ["Email"] = "Электронная почта",
            ["Empty"] = "(Пусто)",

            ["LogOff"] = "Выход из системы",
            ["LogOffClassic"] = "Выход из системы…",
            ["ShutDownClassic"] = "Завершение работы…",
            ["ShutDown"] = "Выключить компьютер",
            ["PowerTitle"] = "Выключить компьютер",
            ["Standby"] = "Ждущий режим",
            ["Hibernate"] = "Спящий режим",
            ["TurnOff"] = "Выключить",
            ["Restart"] = "Перезагрузка",
            ["Lock"] = "Блокировать",
            ["Cancel"] = "Отмена",
            ["PowerQuestion"] = "Что должен сделать компьютер?",

            ["Open"] = "Открыть",
            ["RunAsAdmin"] = "Запуск от имени администратора",
            ["Pin"] = "Добавить в избранное",
            ["Unpin"] = "Удалить из избранного",
            ["MoveToFolder"] = "Переместить в папку",
            ["NewFolder"] = "Новая папка…",
            ["FolderDefaultName"] = "Папка",
            ["OutOfFolder"] = "Вынести из папки",
            ["RenameFolder"] = "Переименовать папку…",
            ["DissolveFolder"] = "Расформировать папку",
            ["FolderNamePrompt"] = "Имя папки:",
            ["Ok"] = "ОК",
            ["RemoveFromList"] = "Удалить из этого списка",
            ["OpenFileLocation"] = "Открыть расположение файла",

            ["TrayOpen"] = "Открыть меню «Пуск»",
            ["TraySettings"] = "Параметры…",
            ["TrayRefresh"] = "Перечитать список программ",
            ["TrayExit"] = "Выход",

            ["SettingsTitle"] = "Retro Menu – параметры",
            ["Appearance"] = "Оформление",
            ["Theme"] = "Тема",
            ["FollowRetroBar"] = "Брать тему из RetroBar",
            ["Behaviour"] = "Поведение",
            ["WinKey"] = "Клавиша Windows",
            ["WinKeyNeutralize"] = "Перехватывать (рекомендуется)",
            ["WinKeySwallow"] = "Полностью поглощать",
            ["WinKeyOff"] = "Не трогать",
            ["FrequentCount"] = "Часто используемые: количество",
            ["ShowRecent"] = "Показывать недавно запущенные программы",
            ["ShowTiles"] = "Избранное плитками справа",
            ["ShowTilesHint"] = "Третья панель показывает избранное и его папки плитками — так же, как сетка закреплённых приложений в Windows 11.",
            ["TilesHeader"] = "Закреплено",
            ["ShowRecentHint"] = "Тогда в левом столбце окажется то, что запускали в последний раз, а не то, что запускают чаще всего.",
            ["ShowSearchBox"] = "Показывать поле поиска (в XP его не было)",
            ["SearchFilesSetting"] = "Поиск включает файлы",
            ["MenuScale"] = "Размер меню",
            ["KeepTaskbar"] = "Показывать панель задач, пока меню открыто",
            ["ShowStoreApps"] = "Перечислять приложения из Store",
            ["UseXpExplorer"] = "Открывать папки в окне файлов в стиле XP",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 установлен и покажет «Мои документы», "
                                    + "«Мой компьютер» и остальные места в старом виде.",
            ["UseXpExplorerMissing"] = "Не найден. Без windows-xp-explorer-win-11 папки открывает "
                                       + "проводник Windows.",
            ["UseXpExplorerBroken"] = "Найдено, но установка неполная, поэтому папки открывает проводник Windows.",
            ["AutoStart"] = "Запускать вместе с Windows",
            ["Language"] = "Язык",
            ["Close"] = "Закрыть",
            ["StoreApps"] = "Приложения Store",

            ["LangAutoWindows"] = "Автоматически (язык Windows)",
            ["LangAutoRetroBar"] = "Автоматически (RetroBar)",
            ["LangDetected"] = "В Windows выбран язык {0}.",
            ["LangShowing"] = "Меню говорит на языке {0}.",
            ["LangUntranslated"] = "Для языка {0} перевода пока нет, поэтому подставляется английский.",
            ["RetroBarFound"] = "RetroBar найден — тема «{0}» → «{1}».",
            ["RetroBarMissing"] = "RetroBar не найден.",

            ["SetupTitle"] = "Установка Retro Menu",
            ["SetupSubtitle"] = "Меню «Пуск» в стиле старых версий Windows.",
            ["SetupIntro"] = "Программа помещается в вашу собственную папку пользователя. Права "
                             + "администратора не нужны, и в системе ничего не изменяется.",
            ["SetupTarget"] = "Папка назначения",
            ["SetupDuring"] = "При установке",
            ["SetupStartMenu"] = "Создать ярлык в меню «Пуск»",
            ["SetupDesktop"] = "Создать ярлык на рабочем столе",
            ["SetupRetroBar"] = "Установить заодно RetroBar — панель задач в стиле XP",
            ["SetupRetroBarNote"] = "Загружается прямо с github.com/dremin/RetroBar. Контрольная "
                                    + "сумма загрузки потом появится в журнале.",
            ["SetupRetroBarPresent"] = "RetroBar уже установлен",
            ["SetupInstall"] = "Установить",
            ["SetupUpdate"] = "Обновить",
            ["SetupUpdateSubtitle"] = "Существующая установка будет обновлена.",
            ["SetupRemoveTitle"] = "Удаление Retro Menu",
            ["SetupRemoveSubtitle"] = "Программа будет удалена из вашей папки пользователя.",
            ["SetupRemoveButton"] = "Удалить",
            ["SetupRemoveText"] = "Retro Menu будет закрыто и удалено из {0}. Ваши настройки "
                                  + "сохранятся, чтобы более поздняя установка снова их нашла.",
            ["SetupWorking"] = "Идёт установка…",
            ["SetupRemoving"] = "Идёт удаление…",
            ["SetupDone"] = "Готово.",
            ["SetupRemoved"] = "Удалено.",
            ["SetupErrors"] = "Завершено с ошибками.",
            ["SetupFailed"] = "Не удалось: {0}",
            ["SetupStart"] = "Запустить",
        };
    }
}
