using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Svenska.</summary>
    internal static class Sv
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Alla program",
            ["Search"] = "Sök",
            ["SearchHint"] = "Sök bland program",
            ["SearchFiles"] = "Sök även i filer",
            ["BestMatch"] = "Bästa träff",
            ["AppsGroup"] = "Appar",
            ["SettingsGroup"] = "Inställningar",
            ["FilesGroup"] = "Filer",
            ["Searching"] = "Söker i filer…",
            ["NoIndex"] = "Windows Search är inte tillgängligt",
            ["NoResults"] = "Inga träffar",
            ["Loading"] = "Läser in…",

            ["ProgramFilter"] = "Filter:",
            ["ProgramGroups"] = "Grupper",
            ["ProgramCount"] = "{0} program",

            ["AdvancedSearch"] = "Avancerad sökning",
            ["SearchFor"] = "Sök efter:",
            ["Categories"] = "Det som söks",
            ["FileType"] = "Typ",
            ["AnyType"] = "Alla filer",
            ["TypeDocuments"] = "Dokument",
            ["TypePictures"] = "Bilder",
            ["TypeMusic"] = "Musik",
            ["TypeVideos"] = "Videoklipp",
            ["TypeFolders"] = "Mappar",
            ["Location"] = "Sök i",
            ["AnyLocation"] = "Överallt",
            ["Modified"] = "Ändrad",
            ["AnyTime"] = "När som helst",
            ["Today"] = "I dag",
            ["ThisWeek"] = "Den här veckan",
            ["ThisMonth"] = "Den här månaden",
            ["ThisYear"] = "I år",
            ["Back"] = "Tillbaka",
            ["Hits"] = "{0} träffar",

            ["Documents"] = "Mina dokument",
            ["RecentDocuments"] = "Senaste dokument",
            ["Pictures"] = "Mina bilder",
            ["Music"] = "Min musik",
            ["Computer"] = "Den här datorn",
            ["ControlPanel"] = "Kontrollpanelen",
            ["SetProgramAccess"] = "Ange programåtkomst och standardprogram",
            ["Connections"] = "Anslutningar",
            ["RemoteDesktop"] = "Fjärrskrivbord",
            ["SshConnection"] = "SSH-anslutning…",
            ["SshPrompt"] = "användare@värd:",
            ["SshTitle"] = "SSH-anslutning",
            ["SshSubtitle"] = "Anslutningen sker med Windows egen OpenSSH-klient.",
            ["SshKey"] = "Nyckelfil:",
            ["SshKeyHint"] = "Nycklar från din .ssh-mapp. Utan nyckel frågar ssh efter lösenordet.",
            ["SshNoKey"] = "(ingen – lösenord)",
            ["SshBrowse"] = "Välj nyckelfil…",
            ["SshConnectButton"] = "Anslut",
            ["SftpConnection"] = "SFTP-anslutning…",
            ["TelnetConnection"] = "Telnet-anslutning…",
            ["FtpConnection"] = "FTP-anslutning…",
            ["NetworkFolder"] = "Öppna nätverksmapp…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Port:",
            ["HostPrompt"] = "Dator:",
            ["FolderPrompt"] = "\\\\server\\utdelning:",
            ["ConnectSubtitle"] = "Windows har klienten med sig själv.",
            ["MapDrive"] = "Anslut nätverksenhet…",
            ["AllConnections"] = "Visa alla anslutningar",
            ["PrintersAndFaxes"] = "Skrivare och fax",
            ["Help"] = "Hjälp och support",
            ["SearchPlace"] = "Sök",
            ["Run"] = "Kör...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Program",
            ["Favorites"] = "Favoriter",
            ["Internet"] = "Internet",
            ["Email"] = "E-post",
            ["Empty"] = "(Tomt)",

            ["LogOff"] = "Logga ut",
            ["LogOffClassic"] = "Logga ut…",
            ["ShutDownClassic"] = "Stäng av…",
            ["ShutDown"] = "Stäng av datorn",
            ["PowerTitle"] = "Stäng av datorn",
            ["Standby"] = "Vänteläge",
            ["Hibernate"] = "Viloläge",
            ["TurnOff"] = "Stäng av",
            ["Restart"] = "Starta om",
            ["Lock"] = "Lås",
            ["Cancel"] = "Avbryt",
            ["PowerQuestion"] = "Vad ska datorn göra?",

            ["Open"] = "Öppna",
            ["RunAsAdmin"] = "Kör som administratör",
            ["Pin"] = "Lägg till bland favoriter",
            ["Unpin"] = "Ta bort från favoriter",
            ["MoveToFolder"] = "Flytta till mapp",
            ["NewFolder"] = "Ny mapp…",
            ["FolderDefaultName"] = "Mapp",
            ["OutOfFolder"] = "Flytta ut ur mappen",
            ["RenameFolder"] = "Byt namn på mappen…",
            ["DissolveFolder"] = "Lös upp mappen",
            ["FolderNamePrompt"] = "Mappens namn:",
            ["Ok"] = "OK",
            ["RemoveFromList"] = "Ta bort från den här listan",
            ["OpenFileLocation"] = "Öppna filens plats",

            ["TrayOpen"] = "Öppna Start-menyn",
            ["TraySettings"] = "Inställningar…",
            ["TrayRefresh"] = "Läs in programlistan på nytt",
            ["TrayExit"] = "Avsluta",

            ["SettingsTitle"] = "Retro Menu – Inställningar",
            ["Appearance"] = "Utseende",
            ["Theme"] = "Tema",
            ["FollowRetroBar"] = "Använd RetroBars tema",
            ["Behaviour"] = "Beteende",
            ["WinKey"] = "Windows-tangenten",
            ["WinKeyNeutralize"] = "Fånga upp (rekommenderas)",
            ["WinKeySwallow"] = "Svälj helt",
            ["WinKeyOff"] = "Rör den inte",
            ["FrequentCount"] = "Ofta använda: antal",
            ["ShowRecent"] = "Visa senast startade program",
            ["ShowTiles"] = "Favoriter som paneler till höger",
            ["ShowTilesHint"] = "En tredje panel visar favoriterna och deras mappar som paneler, precis som rutnätet med fästa appar i Windows 11.",
            ["TilesHeader"] = "Fäst",
            ["ShowRecentHint"] = "Vänsterkolumnen visar då det som startades senast i stället för det som startas oftast.",
            ["ShowSearchBox"] = "Visa sökrutan (XP hade ingen)",
            ["SearchFilesSetting"] = "Sökningen omfattar filer",
            ["MenuScale"] = "Menyns storlek",
            ["KeepTaskbar"] = "Visa aktivitetsfältet medan menyn är öppen",
            ["ShowStoreApps"] = "Ta med appar från Store",
            ["UseXpExplorer"] = "Öppna mappar i XP-filfönstret",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 finns och visar Mina dokument, "
                                    + "Den här datorn och de övriga platserna i gammal skepnad.",
            ["UseXpExplorerMissing"] = "Hittades inte. Utan windows-xp-explorer-win-11 öppnas "
                                       + "mapparna av Utforskaren.",
            ["UseXpExplorerBroken"] = "Hittades, men installationen är ofullständig, så mapparna öppnas av Utforskaren.",
            ["AutoStart"] = "Starta med Windows",
            ["Language"] = "Språk",
            ["Close"] = "Stäng",
            ["StoreApps"] = "Store-appar",

            ["LangAutoWindows"] = "Automatiskt (Windows språk)",
            ["LangAutoRetroBar"] = "Automatiskt (RetroBar)",
            ["LangDetected"] = "Windows är inställt på {0}.",
            ["LangShowing"] = "Menyn talar {0}.",
            ["LangUntranslated"] = "{0} är inte översatt ännu, så engelskan träder in.",
            ["RetroBarFound"] = "RetroBar hittades – temat ”{0}” → ”{1}”.",
            ["RetroBarMissing"] = "RetroBar hittades inte.",

            ["SetupTitle"] = "Installera Retro Menu",
            ["SetupSubtitle"] = "En Start-meny i stil med äldre Windows-versioner.",
            ["SetupIntro"] = "Programmet läggs i din egen användarmapp. Det behövs inga "
                             + "administratörsrättigheter och ingenting i systemet ändras.",
            ["SetupTarget"] = "Målmapp",
            ["SetupDuring"] = "Under installationen",
            ["SetupStartMenu"] = "Skapa en genväg på Start-menyn",
            ["SetupDesktop"] = "Skapa en genväg på skrivbordet",
            ["SetupRetroBar"] = "Installera även RetroBar – aktivitetsfältet i XP-stil",
            ["SetupRetroBarNote"] = "Hämtas direkt från github.com/dremin/RetroBar. Kontrollsumman "
                                    + "för hämtningen syns sedan i loggen.",
            ["SetupRetroBarPresent"] = "RetroBar finns redan",
            ["SetupInstall"] = "Installera",
            ["SetupUpdate"] = "Uppdatera",
            ["SetupUpdateSubtitle"] = "En befintlig installation uppdateras.",
            ["SetupRemoveTitle"] = "Ta bort Retro Menu",
            ["SetupRemoveSubtitle"] = "Programmet tas bort från din användarmapp.",
            ["SetupRemoveButton"] = "Ta bort",
            ["SetupRemoveText"] = "Retro Menu avslutas och tas bort från {0}. Dina inställningar "
                                  + "sparas, så att en senare installation hittar dem igen.",
            ["SetupWorking"] = "Installerar…",
            ["SetupRemoving"] = "Tar bort…",
            ["SetupDone"] = "Klart.",
            ["SetupRemoved"] = "Borttaget.",
            ["SetupErrors"] = "Avslutades med fel.",
            ["SetupFailed"] = "Misslyckades: {0}",
            ["SetupStart"] = "Starta",
        };
    }
}
