using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Türkçe.</summary>
    internal static class Tr
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Tüm Programlar",
            ["Search"] = "Ara",
            ["SearchHint"] = "Programlarda ara",
            ["SearchFiles"] = "Dosyalarda da ara",
            ["BestMatch"] = "En iyi eşleşme",
            ["AppsGroup"] = "Uygulamalar",
            ["SettingsGroup"] = "Ayarlar",
            ["FilesGroup"] = "Dosyalar",
            ["Searching"] = "Dosyalarda aranıyor…",
            ["NoIndex"] = "Windows Araması kullanılamıyor",
            ["NoResults"] = "Sonuç yok",
            ["Loading"] = "Yükleniyor…",

            ["ProgramFilter"] = "Süzgeç:",
            ["ProgramGroups"] = "Gruplar",
            ["ProgramCount"] = "{0} program",

            ["AdvancedSearch"] = "Gelişmiş arama",
            ["SearchFor"] = "Şunu ara:",
            ["Categories"] = "Aranan",
            ["FileType"] = "Tür",
            ["AnyType"] = "Tüm dosyalar",
            ["TypeDocuments"] = "Belgeler",
            ["TypePictures"] = "Resimler",
            ["TypeMusic"] = "Müzik",
            ["TypeVideos"] = "Videolar",
            ["TypeFolders"] = "Klasörler",
            ["Location"] = "Şurada ara",
            ["AnyLocation"] = "Her yerde",
            ["Modified"] = "Değiştirilme",
            ["AnyTime"] = "Herhangi bir zaman",
            ["Today"] = "Bugün",
            ["ThisWeek"] = "Bu hafta",
            ["ThisMonth"] = "Bu ay",
            ["ThisYear"] = "Bu yıl",
            ["Back"] = "Geri",
            ["Hits"] = "{0} sonuç",

            ["Documents"] = "Belgelerim",
            ["RecentDocuments"] = "Son Kullanılan Belgeler",
            ["Pictures"] = "Resimlerim",
            ["Music"] = "Müziğim",
            ["Computer"] = "Bilgisayarım",
            ["ControlPanel"] = "Denetim Masası",
            ["SetProgramAccess"] = "Program Erişimini ve Varsayılanları Ayarla",
            ["Connections"] = "Bağlantılar",
            ["RemoteDesktop"] = "Uzak Masaüstü",
            ["SshConnection"] = "SSH bağlantısı…",
            ["SshPrompt"] = "kullanıcı@sunucu:",
            ["SshTitle"] = "SSH bağlantısı",
            ["SshSubtitle"] = "Bağlantıyı Windows'un kendi OpenSSH istemcisi kurar.",
            ["SshKey"] = "Anahtar dosyası:",
            ["SshKeyHint"] = ".ssh klasörünüzdeki anahtarlar. Anahtar yoksa ssh parolayı sorar.",
            ["SshNoKey"] = "(yok – parola)",
            ["SshBrowse"] = "Anahtar dosyası seç…",
            ["SshConnectButton"] = "Bağlan",
            ["SftpConnection"] = "SFTP bağlantısı…",
            ["TelnetConnection"] = "Telnet bağlantısı…",
            ["FtpConnection"] = "FTP bağlantısı…",
            ["NetworkFolder"] = "Ağ klasörü aç…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Bağlantı noktası:",
            ["HostPrompt"] = "Bilgisayar:",
            ["FolderPrompt"] = "\\\\sunucu\\paylaşım:",
            ["ConnectSubtitle"] = "İstemciyi Windows kendisi getirir.",
            ["MapDrive"] = "Ağ sürücüsü bağla…",
            ["AllConnections"] = "Tüm bağlantıları göster",
            ["PrintersAndFaxes"] = "Yazıcılar ve Fakslar",
            ["Help"] = "Yardım ve Destek",
            ["SearchPlace"] = "Ara",
            ["Run"] = "Çalıştır...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Programlar",
            ["Favorites"] = "Sık Kullanılanlar",
            ["Internet"] = "Internet",
            ["Email"] = "E-posta",
            ["Empty"] = "(Boş)",

            ["LogOff"] = "Oturumu Kapat",
            ["LogOffClassic"] = "Oturumu Kapat…",
            ["ShutDownClassic"] = "Kapat…",
            ["ShutDown"] = "Bilgisayarı Kapat",
            ["PowerTitle"] = "Bilgisayarı kapat",
            ["Standby"] = "Bekleme",
            ["Hibernate"] = "Hazırda Beklet",
            ["TurnOff"] = "Kapat",
            ["Restart"] = "Yeniden Başlat",
            ["Lock"] = "Kilitle",
            ["SwitchUser"] = "Kullanıcı Değiştir",
            ["LogOffTitle"] = "Windows Oturumunu Kapat",
            ["Cancel"] = "İptal",
            ["PowerQuestion"] = "Bilgisayar ne yapsın?",

            ["Open"] = "Aç",
            ["RunAsAdmin"] = "Yönetici olarak çalıştır",
            ["Pin"] = "Sık kullanılanlara ekle",
            ["Unpin"] = "Sık kullanılanlardan kaldır",
            ["MoveToFolder"] = "Klasöre taşı",
            ["NewFolder"] = "Yeni klasör…",
            ["FolderDefaultName"] = "Klasör",
            ["OutOfFolder"] = "Klasörden çıkar",
            ["RenameFolder"] = "Klasörü yeniden adlandır…",
            ["DissolveFolder"] = "Klasörü dağıt",
            ["FolderNamePrompt"] = "Klasörün adı:",
            ["Ok"] = "Tamam",
            ["RemoveFromList"] = "Bu listeden kaldır",
            ["OpenFileLocation"] = "Dosya konumunu aç",

            ["TrayOpen"] = "Başlat menüsünü aç",
            ["TraySettings"] = "Ayarlar…",
            ["TrayRefresh"] = "Program listesini yeniden oku",
            ["TrayExit"] = "Çıkış",

            ["SettingsTitle"] = "Retro Menu – Ayarlar",
            ["Appearance"] = "Görünüm",
            ["Theme"] = "Tema",
            ["FollowRetroBar"] = "RetroBar'ın temasını kullan",
            ["Behaviour"] = "Davranış",
            ["WinKey"] = "Windows tuşu",
            ["WinKeyNeutralize"] = "Yakala (önerilen)",
            ["WinKeySwallow"] = "Tamamen yut",
            ["WinKeyOff"] = "Dokunma",
            ["FrequentCount"] = "Sık kullanılanlar: sayı",
            ["ShowRecent"] = "Son başlatılan programları göster",
            ["ShowTiles"] = "Sık kullanılanlar sağda kutucuk olarak",
            ["ShowTilesHint"] = "Üçüncü bir bölme, sık kullanılanları ve klasörlerini kutucuk olarak gösterir; Windows 11'in sabitlenmiş uygulama ızgarası gibi.",
            ["TilesHeader"] = "Sabitlenmiş",
            ["ShowRecentHint"] = "Sol sütunda o zaman en çok başlatılan değil, en son başlatılan yer alır.",
            ["ShowSearchBox"] = "Arama kutusunu göster (XP'de yoktu)",
            ["SearchFilesSetting"] = "Arama dosyaları da kapsar",
            ["MenuScale"] = "Menü boyutu",
            ["KeepTaskbar"] = "Menü açıkken görev çubuğunu göster",
            ["ShowStoreApps"] = "Store uygulamalarını da listele",
            ["UseXpExplorer"] = "Klasörleri XP dosya penceresinde aç",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 kurulu; Belgelerim, Bilgisayarım ve "
                                    + "diğer yerleri eski görünümüyle gösterecek.",
            ["UseXpExplorerMissing"] = "Bulunamadı. windows-xp-explorer-win-11 olmadan klasörleri "
                                       + "Windows Gezgini açar.",
            ["UseXpExplorerBroken"] = "Bulundu, ancak kurulum eksik; klasörleri Windows Gezgini açıyor.",
            ["AutoStart"] = "Windows ile başlat",
            ["Language"] = "Dil",
            ["Close"] = "Kapat",
            ["StoreApps"] = "Store uygulamaları",

            ["LangAutoWindows"] = "Otomatik (Windows dili)",
            ["LangAutoRetroBar"] = "Otomatik (RetroBar)",
            ["LangDetected"] = "Windows {0} olarak ayarlı.",
            ["LangShowing"] = "Menü {0} konuşuyor.",
            ["LangUntranslated"] = "{0} için henüz çeviri yok, bu yüzden İngilizce devreye giriyor.",
            ["RetroBarFound"] = "RetroBar bulundu – tema \"{0}\" → \"{1}\".",
            ["RetroBarMissing"] = "RetroBar bulunamadı.",

            ["SetupTitle"] = "Retro Menu kurulumu",
            ["SetupSubtitle"] = "Eski Windows sürümlerinin tarzında bir Başlat menüsü.",
            ["SetupIntro"] = "Program kendi kullanıcı klasörünüze yerleştirilir. Yönetici hakkı "
                             + "gerekmez ve sistemde hiçbir şey değiştirilmez.",
            ["SetupTarget"] = "Hedef klasör",
            ["SetupDuring"] = "Kurulum sırasında",
            ["SetupStartMenu"] = "Başlat menüsünde kısayol oluştur",
            ["SetupDesktop"] = "Masaüstünde kısayol oluştur",
            ["SetupRetroBar"] = "RetroBar'ı da kur – XP tarzı görev çubuğu",
            ["SetupRetroBarNote"] = "Doğrudan github.com/dremin/RetroBar adresinden indirilir. "
                                    + "İndirmenin sağlama toplamı sonra günlükte görünür.",
            ["SetupRetroBarPresent"] = "RetroBar zaten kurulu",
            ["SetupInstall"] = "Kur",
            ["SetupUpdate"] = "Güncelle",
            ["SetupUpdateSubtitle"] = "Var olan bir kurulum güncellenecek.",
            ["SetupRemoveTitle"] = "Retro Menu'yü kaldır",
            ["SetupRemoveSubtitle"] = "Program kullanıcı klasörünüzden kaldırılacak.",
            ["SetupRemoveButton"] = "Kaldır",
            ["SetupRemoveText"] = "Retro Menu kapatılacak ve {0} konumundan kaldırılacak. Ayarlarınız "
                                  + "korunur, böylece sonraki bir kurulum onları yeniden bulur.",
            ["SetupWorking"] = "Kuruluyor…",
            ["SetupRemoving"] = "Kaldırılıyor…",
            ["SetupDone"] = "Bitti.",
            ["SetupRemoved"] = "Kaldırıldı.",
            ["SetupErrors"] = "Hatalarla tamamlandı.",
            ["SetupFailed"] = "Başarısız: {0}",
            ["SetupStart"] = "Başlat",
        };
    }
}
