using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>Українська.</summary>
    internal static class Uk
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "Усі програми",
            ["Search"] = "Пошук",
            ["SearchHint"] = "Пошук програм",
            ["SearchFiles"] = "Шукати також у файлах",
            ["BestMatch"] = "Найкращий збіг",
            ["AppsGroup"] = "Програми",
            ["SettingsGroup"] = "Параметри",
            ["FilesGroup"] = "Файли",
            ["Searching"] = "Пошук у файлах…",
            ["NoIndex"] = "Пошук Windows недоступний",
            ["NoResults"] = "Нічого не знайдено",
            ["Loading"] = "Завантаження…",

            ["ProgramFilter"] = "Фільтр:",
            ["ProgramGroups"] = "Групи",
            ["ProgramCount"] = "Програм: {0}",

            ["AdvancedSearch"] = "Розширений пошук",
            ["SearchFor"] = "Шукати:",
            ["Categories"] = "Що шукаємо",
            ["FileType"] = "Тип",
            ["AnyType"] = "Усі файли",
            ["TypeDocuments"] = "Документи",
            ["TypePictures"] = "Зображення",
            ["TypeMusic"] = "Музика",
            ["TypeVideos"] = "Відео",
            ["TypeFolders"] = "Папки",
            ["Location"] = "Шукати в",
            ["AnyLocation"] = "Скрізь",
            ["Modified"] = "Змінено",
            ["AnyTime"] = "Будь-коли",
            ["Today"] = "Сьогодні",
            ["ThisWeek"] = "Цього тижня",
            ["ThisMonth"] = "Цього місяця",
            ["ThisYear"] = "Цього року",
            ["Back"] = "Назад",
            ["Hits"] = "Знайдено: {0}",

            ["Documents"] = "Мої документи",
            ["RecentDocuments"] = "Останні документи",
            ["Pictures"] = "Мої рисунки",
            ["Music"] = "Моя музика",
            ["Computer"] = "Мій комп'ютер",
            ["ControlPanel"] = "Панель керування",
            ["SetProgramAccess"] = "Вибір програм за промовчанням",
            ["Connections"] = "Підключення",
            ["RemoteDesktop"] = "Віддалений робочий стіл",
            ["SshConnection"] = "Підключення SSH…",
            ["SshPrompt"] = "користувач@вузол:",
            ["SshTitle"] = "Підключення SSH",
            ["SshSubtitle"] = "Підключається клієнт OpenSSH, вбудований у Windows.",
            ["SshKey"] = "Файл ключа:",
            ["SshKeyHint"] = "Ключі з папки .ssh. Без ключа ssh запитає пароль.",
            ["SshNoKey"] = "(немає — пароль)",
            ["SshBrowse"] = "Вибрати файл ключа…",
            ["SshConnectButton"] = "Підключитися",
            ["SftpConnection"] = "З'єднання SFTP…",
            ["TelnetConnection"] = "З'єднання Telnet…",
            ["FtpConnection"] = "З'єднання FTP…",
            ["NetworkFolder"] = "Відкрити мережеву теку…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "Порт:",
            ["HostPrompt"] = "Комп'ютер:",
            ["FolderPrompt"] = "\\\\сервер\\ресурс:",
            ["ConnectSubtitle"] = "Клієнт входить до складу Windows.",
            ["MapDrive"] = "Підключити мережевий диск…",
            ["AllConnections"] = "Показати всі підключення",
            ["PrintersAndFaxes"] = "Принтери й факси",
            ["Help"] = "Довідка та підтримка",
            ["SearchPlace"] = "Пошук",
            ["Run"] = "Виконати...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "Програми",
            ["Favorites"] = "Вибране",
            ["Internet"] = "Інтернет",
            ["Email"] = "Електронна пошта",
            ["Empty"] = "(Порожньо)",

            ["LogOff"] = "Вихід із системи",
            ["LogOffClassic"] = "Вихід із системи…",
            ["ShutDownClassic"] = "Завершення роботи…",
            ["ShutDown"] = "Вимкнути комп'ютер",
            ["PowerTitle"] = "Вимкнути комп'ютер",
            ["Standby"] = "Режим очікування",
            ["Hibernate"] = "Режим сну",
            ["TurnOff"] = "Вимкнути",
            ["Restart"] = "Перезавантажити",
            ["Lock"] = "Заблокувати",
            ["SwitchUser"] = "Змінити користувача",
            ["LogOffTitle"] = "Вихід із Windows",
            ["Cancel"] = "Скасувати",
            ["PowerQuestion"] = "Що має зробити комп'ютер?",

            ["Open"] = "Відкрити",
            ["RunAsAdmin"] = "Запуск від імені адміністратора",
            ["Pin"] = "Додати до вибраного",
            ["Unpin"] = "Видалити з вибраного",
            ["MoveToFolder"] = "Перемістити до папки",
            ["NewFolder"] = "Нова папка…",
            ["FolderDefaultName"] = "Папка",
            ["OutOfFolder"] = "Винести з папки",
            ["RenameFolder"] = "Перейменувати папку…",
            ["DissolveFolder"] = "Розформувати папку",
            ["FolderNamePrompt"] = "Ім'я папки:",
            ["Ok"] = "ОК",
            ["RemoveFromList"] = "Видалити з цього списку",
            ["OpenFileLocation"] = "Відкрити розташування файлу",

            ["TrayOpen"] = "Відкрити меню «Пуск»",
            ["TraySettings"] = "Параметри…",
            ["TrayRefresh"] = "Перечитати список програм",
            ["TrayExit"] = "Вихід",

            ["SettingsTitle"] = "Retro Menu – параметри",
            ["Appearance"] = "Оформлення",
            ["Theme"] = "Тема",
            ["FollowRetroBar"] = "Брати тему з RetroBar",
            ["Behaviour"] = "Поведінка",
            ["WinKey"] = "Клавіша Windows",
            ["WinKeyNeutralize"] = "Перехоплювати (рекомендовано)",
            ["WinKeySwallow"] = "Повністю поглинати",
            ["WinKeyOff"] = "Не чіпати",
            ["FrequentCount"] = "Часто використовувані: кількість",
            ["ShowRecent"] = "Показувати нещодавно запущені програми",
            ["ShowTiles"] = "Вибране плитками праворуч",
            ["ShowTilesHint"] = "Третя панель показує вибране та його папки плитками — так само, як сітка закріплених програм у Windows 11.",
            ["TilesHeader"] = "Закріплено",
            ["ShowRecentHint"] = "Тоді в лівому стовпці буде те, що запускали востаннє, а не те, що запускають найчастіше.",
            ["ShowSearchBox"] = "Показувати поле пошуку (у XP його не було)",
            ["SearchFilesSetting"] = "Пошук охоплює файли",
            ["MenuScale"] = "Розмір меню",
            ["KeepTaskbar"] = "Показувати панель завдань, доки меню відкрите",
            ["ShowStoreApps"] = "Перелічувати програми зі Store",
            ["UseXpExplorer"] = "Відкривати папки у вікні файлів у стилі XP",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 встановлено, і він покаже «Мої документи», "
                                    + "«Мій комп'ютер» та інші місця в давньому вигляді.",
            ["UseXpExplorerMissing"] = "Не знайдено. Без windows-xp-explorer-win-11 папки відкриває "
                                       + "провідник Windows.",
            ["UseXpExplorerBroken"] = "Знайдено, але встановлення неповне, тому папки відкриває провідник Windows.",
            ["AutoStart"] = "Запускати разом із Windows",
            ["Language"] = "Мова",
            ["Close"] = "Закрити",
            ["StoreApps"] = "Програми Store",

            ["LangAutoWindows"] = "Автоматично (мова Windows)",
            ["LangAutoRetroBar"] = "Автоматично (RetroBar)",
            ["LangDetected"] = "У Windows вибрано мову {0}.",
            ["LangShowing"] = "Меню говорить мовою {0}.",
            ["LangUntranslated"] = "Для мови {0} перекладу ще немає, тому вмикається англійська.",
            ["RetroBarFound"] = "RetroBar знайдено — тема «{0}» → «{1}».",
            ["RetroBarMissing"] = "RetroBar не знайдено.",

            ["SetupTitle"] = "Встановлення Retro Menu",
            ["SetupSubtitle"] = "Меню «Пуск» у стилі старих версій Windows.",
            ["SetupIntro"] = "Програма потрапляє до вашої власної папки користувача. Права "
                             + "адміністратора не потрібні, і в системі нічого не змінюється.",
            ["SetupTarget"] = "Папка призначення",
            ["SetupDuring"] = "Під час встановлення",
            ["SetupStartMenu"] = "Створити ярлик у меню «Пуск»",
            ["SetupDesktop"] = "Створити ярлик на робочому столі",
            ["SetupRetroBar"] = "Встановити заодно RetroBar — панель завдань у стилі XP",
            ["SetupRetroBarNote"] = "Завантажується просто з github.com/dremin/RetroBar. Контрольна "
                                    + "сума завантаження потім з'явиться в журналі.",
            ["SetupRetroBarPresent"] = "RetroBar уже встановлено",
            ["SetupInstall"] = "Встановити",
            ["SetupUpdate"] = "Оновити",
            ["SetupUpdateSubtitle"] = "Наявне встановлення буде оновлено.",
            ["SetupRemoveTitle"] = "Видалення Retro Menu",
            ["SetupRemoveSubtitle"] = "Програму буде видалено з вашої папки користувача.",
            ["SetupRemoveButton"] = "Видалити",
            ["SetupRemoveText"] = "Retro Menu буде закрито й видалено з {0}. Ваші налаштування "
                                  + "залишаться, щоб пізніше встановлення знову їх знайшло.",
            ["SetupWorking"] = "Триває встановлення…",
            ["SetupRemoving"] = "Триває видалення…",
            ["SetupDone"] = "Готово.",
            ["SetupRemoved"] = "Видалено.",
            ["SetupErrors"] = "Завершено з помилками.",
            ["SetupFailed"] = "Не вдалося: {0}",
            ["SetupStart"] = "Запустити",
        };
    }
}
