using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>简体中文.</summary>
    internal static class ZhHans
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "所有程序",
            ["Search"] = "搜索",
            ["SearchHint"] = "搜索程序",
            ["SearchFiles"] = "同时搜索文件",
            ["BestMatch"] = "最佳匹配",
            ["AppsGroup"] = "应用",
            ["SettingsGroup"] = "设置",
            ["FilesGroup"] = "文件",
            ["Searching"] = "正在文件中搜索…",
            ["NoIndex"] = "Windows 搜索不可用",
            ["NoResults"] = "没有匹配项",
            ["Loading"] = "正在加载…",

            ["ProgramFilter"] = "筛选：",
            ["ProgramGroups"] = "分组",
            ["ProgramCount"] = "{0} 个程序",

            ["AdvancedSearch"] = "高级搜索",
            ["SearchFor"] = "搜索内容:",
            ["Categories"] = "查找对象",
            ["FileType"] = "类型",
            ["AnyType"] = "所有文件",
            ["TypeDocuments"] = "文档",
            ["TypePictures"] = "图片",
            ["TypeMusic"] = "音乐",
            ["TypeVideos"] = "视频",
            ["TypeFolders"] = "文件夹",
            ["Location"] = "搜索范围",
            ["AnyLocation"] = "所有位置",
            ["Modified"] = "修改时间",
            ["AnyTime"] = "不限时间",
            ["Today"] = "今天",
            ["ThisWeek"] = "本周",
            ["ThisMonth"] = "本月",
            ["ThisYear"] = "今年",
            ["Back"] = "返回",
            ["Hits"] = "{0} 个结果",

            ["Documents"] = "我的文档",
            ["RecentDocuments"] = "我最近的文档",
            ["Pictures"] = "图片收藏",
            ["Music"] = "我的音乐",
            ["Computer"] = "我的电脑",
            ["ControlPanel"] = "控制面板",
            ["SetProgramAccess"] = "设定程序访问和默认值",
            ["Connections"] = "连接",
            ["RemoteDesktop"] = "远程桌面",
            ["SshConnection"] = "SSH 连接…",
            ["SshPrompt"] = "用户@主机:",
            ["SshTitle"] = "SSH 连接",
            ["SshSubtitle"] = "由 Windows 自带的 OpenSSH 建立连接。",
            ["SshKey"] = "密钥文件:",
            ["SshKeyHint"] = ".ssh 文件夹中的密钥。没有密钥时,ssh 会询问密码。",
            ["SshNoKey"] = "(无 – 密码)",
            ["SshBrowse"] = "选择密钥文件…",
            ["SshConnectButton"] = "连接",
            ["SftpConnection"] = "SFTP 连接…",
            ["TelnetConnection"] = "Telnet 连接…",
            ["FtpConnection"] = "FTP 连接…",
            ["NetworkFolder"] = "打开网络文件夹…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "端口：",
            ["HostPrompt"] = "计算机：",
            ["FolderPrompt"] = "\\\\服务器\\共享:",
            ["ConnectSubtitle"] = "客户端由 Windows 自带。",
            ["MapDrive"] = "映射网络驱动器…",
            ["AllConnections"] = "显示所有连接",
            ["PrintersAndFaxes"] = "打印机和传真",
            ["Help"] = "帮助和支持",
            ["SearchPlace"] = "搜索",
            ["Run"] = "运行...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "程序",
            ["Favorites"] = "收藏夹",
            ["Internet"] = "Internet",
            ["Email"] = "电子邮件",
            ["Empty"] = "(空)",

            ["LogOff"] = "注销",
            ["LogOffClassic"] = "注销…",
            ["ShutDownClassic"] = "关机…",
            ["ShutDown"] = "关闭计算机",
            ["PowerTitle"] = "关闭计算机",
            ["Standby"] = "待机",
            ["Hibernate"] = "休眠",
            ["TurnOff"] = "关闭",
            ["Restart"] = "重新启动",
            ["Lock"] = "锁定",
            ["SwitchUser"] = "切换用户",
            ["LogOffTitle"] = "注销 Windows",
            ["Cancel"] = "取消",
            ["PowerQuestion"] = "希望计算机做什么?",

            ["Open"] = "打开",
            ["RunAsAdmin"] = "以管理员身份运行",
            ["Pin"] = "添加到收藏夹",
            ["Unpin"] = "从收藏夹中移除",
            ["MoveToFolder"] = "移动到文件夹",
            ["NewFolder"] = "新建文件夹…",
            ["FolderDefaultName"] = "文件夹",
            ["OutOfFolder"] = "移出文件夹",
            ["RenameFolder"] = "重命名文件夹…",
            ["DissolveFolder"] = "解散文件夹",
            ["FolderNamePrompt"] = "文件夹名称:",
            ["Ok"] = "确定",
            ["RemoveFromList"] = "从此列表中删除",
            ["OpenFileLocation"] = "打开文件位置",

            ["TrayOpen"] = "打开开始菜单",
            ["TraySettings"] = "设置…",
            ["TrayRefresh"] = "重新读取程序列表",
            ["TrayExit"] = "退出",

            ["SettingsTitle"] = "Retro Menu – 设置",
            ["Appearance"] = "外观",
            ["Theme"] = "主题",
            ["FollowRetroBar"] = "沿用 RetroBar 的主题",
            ["Behaviour"] = "行为",
            ["WinKey"] = "Windows 键",
            ["WinKeyNeutralize"] = "拦截(推荐)",
            ["WinKeySwallow"] = "完全吞掉",
            ["WinKeyOff"] = "不去碰它",
            ["FrequentCount"] = "常用程序: 数量",
            ["ShowRecent"] = "显示最近启动的程序",
            ["ShowTiles"] = "收藏夹以磁贴显示在右侧",
            ["ShowTilesHint"] = "第三块区域把收藏夹及其文件夹排成磁贴,就像 Windows 11 的已固定应用网格。",
            ["TilesHeader"] = "已固定",
            ["ShowRecentHint"] = "左栏随后列出最后启动的程序,而不是启动次数最多的程序。",
            ["ShowSearchBox"] = "显示搜索框(XP 没有)",
            ["SearchFilesSetting"] = "搜索包含文件",
            ["MenuScale"] = "菜单大小",
            ["KeepTaskbar"] = "菜单打开时显示任务栏",
            ["ShowStoreApps"] = "一并列出应用商店的应用",
            ["UseXpExplorer"] = "在 XP 文件窗口中打开文件夹",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 已安装,会以旧日的样子显示我的文档、"
                                    + "我的电脑等位置。",
            ["UseXpExplorerMissing"] = "未找到。没有 windows-xp-explorer-win-11 时,文件夹由 "
                                       + "Windows 资源管理器打开。",
            ["UseXpExplorerBroken"] = "找到了,但安装不完整,因此文件夹由 Windows 资源管理器打开。",
            ["AutoStart"] = "随 Windows 一起启动",
            ["Language"] = "语言",
            ["Close"] = "关闭",
            ["StoreApps"] = "应用商店应用",

            ["LangAutoWindows"] = "自动(Windows 语言)",
            ["LangAutoRetroBar"] = "自动(RetroBar)",
            ["LangDetected"] = "Windows 的语言是 {0}。",
            ["LangShowing"] = "菜单说的是 {0}。",
            ["LangUntranslated"] = "{0} 还没有译文,因此改用英语。",
            ["RetroBarFound"] = "找到 RetroBar – 主题“{0}”→“{1}”。",
            ["RetroBarMissing"] = "未找到 RetroBar。",

            ["SetupTitle"] = "安装 Retro Menu",
            ["SetupSubtitle"] = "一个仿旧版 Windows 样式的开始菜单。",
            ["SetupIntro"] = "程序会放进你自己的用户文件夹。不需要管理员权限,系统也不会有任何改动。",
            ["SetupTarget"] = "目标文件夹",
            ["SetupDuring"] = "安装时",
            ["SetupStartMenu"] = "在开始菜单中创建快捷方式",
            ["SetupDesktop"] = "在桌面上创建快捷方式",
            ["SetupRetroBar"] = "一并安装 RetroBar – XP 风格的任务栏",
            ["SetupRetroBarNote"] = "直接从 github.com/dremin/RetroBar 下载。下载文件的校验和随后会"
                                    + "出现在日志中。",
            ["SetupRetroBarPresent"] = "RetroBar 已经装好了",
            ["SetupInstall"] = "安装",
            ["SetupUpdate"] = "更新",
            ["SetupUpdateSubtitle"] = "将更新现有的安装。",
            ["SetupRemoveTitle"] = "删除 Retro Menu",
            ["SetupRemoveSubtitle"] = "程序将从你的用户文件夹中删除。",
            ["SetupRemoveButton"] = "删除",
            ["SetupRemoveText"] = "Retro Menu 将退出并从 {0} 中删除。你的设置会保留下来,"
                                  + "以后重新安装时还能找到。",
            ["SetupWorking"] = "正在安装…",
            ["SetupRemoving"] = "正在删除…",
            ["SetupDone"] = "完成。",
            ["SetupRemoved"] = "已删除。",
            ["SetupErrors"] = "结束,但有错误。",
            ["SetupFailed"] = "失败: {0}",
            ["SetupStart"] = "启动",
        };
    }
}
