using System.Collections.Generic;

namespace RetroMenu.Services.Strings
{
    /// <summary>繁體中文.</summary>
    internal static class ZhHant
    {
        internal static readonly Dictionary<string, string> Table = new Dictionary<string, string>
        {
            ["AllPrograms"] = "所有程式",
            ["Search"] = "搜尋",
            ["SearchHint"] = "搜尋程式",
            ["SearchFiles"] = "一併搜尋檔案",
            ["BestMatch"] = "最佳比對結果",
            ["AppsGroup"] = "應用程式",
            ["SettingsGroup"] = "設定",
            ["FilesGroup"] = "檔案",
            ["Searching"] = "正在檔案中搜尋…",
            ["NoIndex"] = "Windows 搜尋無法使用",
            ["NoResults"] = "沒有相符項目",
            ["Loading"] = "正在載入…",

            ["ProgramFilter"] = "篩選：",
            ["ProgramGroups"] = "群組",
            ["ProgramCount"] = "{0} 個程式",

            ["AdvancedSearch"] = "進階搜尋",
            ["SearchFor"] = "搜尋內容:",
            ["Categories"] = "尋找對象",
            ["FileType"] = "類型",
            ["AnyType"] = "所有檔案",
            ["TypeDocuments"] = "文件",
            ["TypePictures"] = "圖片",
            ["TypeMusic"] = "音樂",
            ["TypeVideos"] = "影片",
            ["TypeFolders"] = "資料夾",
            ["Location"] = "搜尋範圍",
            ["AnyLocation"] = "所有位置",
            ["Modified"] = "修改時間",
            ["AnyTime"] = "不限時間",
            ["Today"] = "今天",
            ["ThisWeek"] = "本週",
            ["ThisMonth"] = "本月",
            ["ThisYear"] = "今年",
            ["Back"] = "返回",
            ["Hits"] = "{0} 個結果",

            ["Documents"] = "我的文件",
            ["RecentDocuments"] = "我最近的文件",
            ["Pictures"] = "我的圖片",
            ["Music"] = "我的音樂",
            ["Computer"] = "我的電腦",
            ["ControlPanel"] = "控制台",
            ["SetProgramAccess"] = "設定程式存取及預設值",
            ["Connections"] = "連線",
            ["RemoteDesktop"] = "遠端桌面",
            ["SshConnection"] = "SSH 連線…",
            ["SshPrompt"] = "使用者@主機:",
            ["SshTitle"] = "SSH 連線",
            ["SshSubtitle"] = "由 Windows 內建的 OpenSSH 建立連線。",
            ["SshKey"] = "金鑰檔案:",
            ["SshKeyHint"] = ".ssh 資料夾中的金鑰。沒有金鑰時,ssh 會詢問密碼。",
            ["SshNoKey"] = "(無 – 密碼)",
            ["SshBrowse"] = "選擇金鑰檔案…",
            ["SshConnectButton"] = "連線",
            ["SftpConnection"] = "SFTP 連線…",
            ["TelnetConnection"] = "Telnet 連線…",
            ["FtpConnection"] = "FTP 連線…",
            ["NetworkFolder"] = "開啟網路資料夾…",
            ["WslShell"] = "Linux (WSL)",
            ["ConnectPort"] = "連接埠：",
            ["HostPrompt"] = "電腦：",
            ["FolderPrompt"] = "\\\\伺服器\\共用:",
            ["ConnectSubtitle"] = "用戶端由 Windows 自行提供。",
            ["MapDrive"] = "連線網路磁碟機…",
            ["AllConnections"] = "顯示所有連線",
            ["PrintersAndFaxes"] = "印表機和傳真",
            ["Help"] = "說明及支援",
            ["SearchPlace"] = "搜尋",
            ["Run"] = "執行...",
            ["WindowsUpdate"] = "Windows Update",
            ["Programs"] = "程式集",
            ["Favorites"] = "我的最愛",
            ["Internet"] = "網際網路",
            ["Email"] = "電子郵件",
            ["Empty"] = "(空的)",

            ["LogOff"] = "登出",
            ["LogOffClassic"] = "登出…",
            ["ShutDownClassic"] = "關機…",
            ["ShutDown"] = "電腦關機",
            ["PowerTitle"] = "電腦關機",
            ["Standby"] = "待命",
            ["Hibernate"] = "休眠",
            ["TurnOff"] = "關機",
            ["Restart"] = "重新啟動",
            ["Lock"] = "鎖定",
            ["SwitchUser"] = "切換使用者",
            ["LogOffTitle"] = "登出 Windows",
            ["Cancel"] = "取消",
            ["PowerQuestion"] = "您希望電腦做什麼?",

            ["Open"] = "開啟",
            ["RunAsAdmin"] = "以系統管理員身分執行",
            ["Pin"] = "加入我的最愛",
            ["Unpin"] = "從我的最愛移除",
            ["MoveToFolder"] = "移動到資料夾",
            ["NewFolder"] = "新增資料夾…",
            ["FolderDefaultName"] = "資料夾",
            ["OutOfFolder"] = "移出資料夾",
            ["RenameFolder"] = "重新命名資料夾…",
            ["DissolveFolder"] = "解散資料夾",
            ["FolderNamePrompt"] = "資料夾名稱:",
            ["Ok"] = "確定",
            ["RemoveFromList"] = "從這個清單移除",
            ["OpenFileLocation"] = "開啟檔案位置",

            ["TrayOpen"] = "開啟開始功能表",
            ["TraySettings"] = "設定…",
            ["TrayRefresh"] = "重新讀取程式清單",
            ["TrayExit"] = "結束",

            ["SettingsTitle"] = "Retro Menu – 設定",
            ["Appearance"] = "外觀",
            ["Theme"] = "佈景主題",
            ["FollowRetroBar"] = "沿用 RetroBar 的佈景主題",
            ["Behaviour"] = "行為",
            ["WinKey"] = "Windows 鍵",
            ["WinKeyNeutralize"] = "攔截(建議)",
            ["WinKeySwallow"] = "完全吞下",
            ["WinKeyOff"] = "不去動它",
            ["FrequentCount"] = "常用程式: 數量",
            ["ShowRecent"] = "顯示最近啟動的程式",
            ["ShowTiles"] = "我的最愛以磚樣顯示在右側",
            ["ShowTilesHint"] = "第三個區域把我的最愛及其資料夾排成磚樣,就像 Windows 11 的釘選應用程式格線。",
            ["TilesHeader"] = "已釘選",
            ["ShowRecentHint"] = "左欄接著列出最後啟動的程式,而不是啟動次數最多的程式。",
            ["ShowSearchBox"] = "顯示搜尋方塊(XP 沒有)",
            ["SearchFilesSetting"] = "搜尋包含檔案",
            ["MenuScale"] = "功能表大小",
            ["KeepTaskbar"] = "功能表開啟時顯示工作列",
            ["ShowStoreApps"] = "一併列出市集應用程式",
            ["UseXpExplorer"] = "在 XP 檔案視窗中開啟資料夾",
            ["UseXpExplorerHint"] = "windows-xp-explorer-win-11 已安裝,會以昔日的樣貌顯示我的文件、"
                                    + "我的電腦等位置。",
            ["UseXpExplorerMissing"] = "找不到。沒有 windows-xp-explorer-win-11 時,資料夾由 "
                                       + "Windows 檔案總管開啟。",
            ["UseXpExplorerBroken"] = "找到了,但安裝不完整,因此資料夾由 Windows 檔案總管開啟。",
            ["AutoStart"] = "隨 Windows 一起啟動",
            ["Language"] = "語言",
            ["Close"] = "關閉",
            ["StoreApps"] = "市集應用程式",

            ["LangAutoWindows"] = "自動(Windows 語言)",
            ["LangAutoRetroBar"] = "自動(RetroBar)",
            ["LangDetected"] = "Windows 的語言是 {0}。",
            ["LangShowing"] = "功能表說的是 {0}。",
            ["LangUntranslated"] = "{0} 還沒有譯文,因此改用英文。",
            ["RetroBarFound"] = "找到 RetroBar – 佈景主題「{0}」→「{1}」。",
            ["RetroBarMissing"] = "找不到 RetroBar。",

            ["SetupTitle"] = "安裝 Retro Menu",
            ["SetupSubtitle"] = "一個仿舊版 Windows 樣式的開始功能表。",
            ["SetupIntro"] = "程式會放進您自己的使用者資料夾。不需要系統管理員權限,系統也不會有任何變動。",
            ["SetupTarget"] = "目標資料夾",
            ["SetupDuring"] = "安裝時",
            ["SetupStartMenu"] = "在開始功能表中建立捷徑",
            ["SetupDesktop"] = "在桌面上建立捷徑",
            ["SetupRetroBar"] = "一併安裝 RetroBar – XP 風格的工作列",
            ["SetupRetroBarNote"] = "直接從 github.com/dremin/RetroBar 下載。下載檔案的總和檢查碼隨後"
                                    + "會出現在記錄中。",
            ["SetupRetroBarPresent"] = "RetroBar 已經裝好了",
            ["SetupInstall"] = "安裝",
            ["SetupUpdate"] = "更新",
            ["SetupUpdateSubtitle"] = "將更新現有的安裝。",
            ["SetupRemoveTitle"] = "移除 Retro Menu",
            ["SetupRemoveSubtitle"] = "程式將從您的使用者資料夾中移除。",
            ["SetupRemoveButton"] = "移除",
            ["SetupRemoveText"] = "Retro Menu 將結束並從 {0} 中移除。您的設定會保留下來,"
                                  + "日後重新安裝時還找得到。",
            ["SetupWorking"] = "正在安裝…",
            ["SetupRemoving"] = "正在移除…",
            ["SetupDone"] = "完成。",
            ["SetupRemoved"] = "已移除。",
            ["SetupErrors"] = "結束,但有錯誤。",
            ["SetupFailed"] = "失敗: {0}",
            ["SetupStart"] = "啟動",
        };
    }
}
